/* Present (presente): reference tables and quiz sentences.
   Latin American Spanish: the plural “you” is ustedes, which takes the ellos form.
   In tables, [square brackets] mark the part of the form to highlight.
   In sentences, word{gloss} gives the hover translation and ___ is the gap. */

const PRESENT_TENSE = {
  id: 'present', pl: 'Presente', en: 'Present',
  intro: 'The presente covers what you do in general, what is happening now, and even plans for the near future: mañana trabajo. Regular verbs drop -ar, -er or -ir and add one ending per person. Many common verbs change a vowel in the stem, a group of verbs is irregular only in the yo form, and ser, estar and ir are irregular throughout. In Latin America “you” in the plural is ustedes, which takes the ellos form.',

  groups: [
    {
      id: 'present-reg', pl: 'Regulares', en: 'Regular verbs', q: 'hablo, comes, vive',
      summary: 'Drop the -ar, -er or -ir and add the ending for the person. -ar verbs use a: hablo, hablas, habla, hablamos, hablan. -er and -ir verbs use e, and share every ending except nosotros: comemos, vivimos.',
      tables: [
        { title: 'hablar, comer, vivir: three sets of endings',
          cols: [{ label: '-ar', tint: 'all' }, { label: '-er', tint: 'all' }, { label: '-ir', tint: 'all' }],
          rows: [
            { who: 'yo', cells: ['habl[o]', 'com[o]', 'viv[o]'] },
            { who: 'tú', cells: ['habl[as]', 'com[es]', 'viv[es]'] },
            { who: 'él / ella / usted', cells: ['habl[a]', 'com[e]', 'viv[e]'] },
            { who: 'nosotros', cells: ['habl[amos]', 'com[emos]', 'viv[imos]'] },
            { who: 'ellos / ellas / ustedes', cells: ['habl[an]', 'com[en]', 'viv[en]'] },
          ] },
        { title: 'Other regular verbs',
          cols: [{ label: 'yo', tint: 'all' }, { label: 'nosotros', tint: 'all' }, { label: 'ellos', tint: 'all' }],
          rows: [
            { who: 'trabajar, to work', cells: ['trabaj[o]', 'trabaj[amos]', 'trabaj[an]'] },
            { who: 'estudiar, to study', cells: ['estudi[o]', 'estudi[amos]', 'estudi[an]'] },
            { who: 'aprender, to learn', cells: ['aprend[o]', 'aprend[emos]', 'aprend[en]'] },
            { who: 'leer, to read', cells: ['le[o]', 'le[emos]', 'le[en]'] },
            { who: 'escribir, to write', cells: ['escrib[o]', 'escrib[imos]', 'escrib[en]'] },
            { who: 'abrir, to open', cells: ['abr[o]', 'abr[imos]', 'abr[en]'] },
          ] },
        { title: 'What the presente is used for',
          cols: [{ label: 'Example', tint: 'all' }, { label: 'English', tint: 'all' }],
          rows: [
            { who: 'habits', cells: ['Siempre desayuno a las siete.', 'I always have breakfast at seven.'] },
            { who: 'right now', cells: ['¿Qué haces? Leo el periódico.', 'What are you doing? I’m reading the paper.'] },
            { who: 'facts', cells: ['El agua hierve a cien grados.', 'Water boils at a hundred degrees.'] },
            { who: 'near future', cells: ['Mañana trabajo hasta tarde.', 'Tomorrow I’m working late.'] },
            { who: 'since when', cells: ['Vivo aquí desde 2020.', 'I have lived here since 2020.'] },
          ] },
      ],
      rules: [
        { t: 'Yo always ends in -o', ex: 'Trabajo en un banco.', en: 'I work in a bank.' },
        { t: '-er and -ir verbs differ only in the nosotros form', ex: 'Comemos juntos y vivimos cerca.', en: 'We eat together and we live nearby.' },
        { t: 'Ustedes takes the ellos form', ex: '¿Ustedes hablan inglés?', en: 'Do you all speak English?' },
        { t: 'The presente can describe what is happening right now', ex: '¿Qué lees?', en: 'What are you reading?' },
        { t: 'Desde and hace + presente for something that is still going on', ex: 'Estudio español hace dos años.', en: 'I have been studying Spanish for two years.' },
      ],
      watch: [
        'Hablo (I speak) has no accent; habló (he spoke) does. The accent changes the tense.',
        'English “I have lived here since 2020” is the presente in Spanish: vivo aquí desde 2020, not he vivido.',
        'The pronoun is usually left out because the ending shows the person: hablo, not yo hablo, unless you want to stress who.',
      ],
    },
    {
      id: 'present-stem', pl: 'Cambio de raíz', en: 'Stem-changing verbs', q: 'quiero, puedo, pido',
      summary: 'In many common verbs the stressed vowel of the stem changes: e becomes ie (querer → quiero), o becomes ue (poder → puedo), or e becomes i (pedir → pido). The change happens in every person except nosotros, where the stress falls on the ending. Jugar is the only verb where u becomes ue.',
      tables: [
        { title: 'The three stem changes',
          cols: [{ label: 'e → ie: querer', tint: 'all' }, { label: 'o → ue: poder', tint: 'all' }, { label: 'e → i: pedir', tint: 'all' }],
          rows: [
            { who: 'yo', cells: ['qu[ie]ro', 'p[ue]do', 'p[i]do'] },
            { who: 'tú', cells: ['qu[ie]res', 'p[ue]des', 'p[i]des'] },
            { who: 'él / ella / usted', cells: ['qu[ie]re', 'p[ue]de', 'p[i]de'] },
            { who: 'nosotros', cells: ['queremos', 'podemos', 'pedimos'] },
            { who: 'ellos / ellas / ustedes', cells: ['qu[ie]ren', 'p[ue]den', 'p[i]den'] },
          ] },
        { title: 'More stem-changing verbs',
          cols: [{ label: 'yo', tint: 'all' }, { label: 'nosotros', tint: 'all' }, { label: 'ellos', tint: 'all' }],
          rows: [
            { who: 'pensar, to think (e → ie)', cells: ['p[ie]nso', 'pensamos', 'p[ie]nsan'] },
            { who: 'empezar, to begin (e → ie)', cells: ['emp[ie]zo', 'empezamos', 'emp[ie]zan'] },
            { who: 'preferir, to prefer (e → ie)', cells: ['pref[ie]ro', 'preferimos', 'pref[ie]ren'] },
            { who: 'entender, to understand (e → ie)', cells: ['ent[ie]ndo', 'entendemos', 'ent[ie]nden'] },
            { who: 'dormir, to sleep (o → ue)', cells: ['d[ue]rmo', 'dormimos', 'd[ue]rmen'] },
            { who: 'volver, to come back (o → ue)', cells: ['v[ue]lvo', 'volvemos', 'v[ue]lven'] },
            { who: 'costar, to cost (o → ue)', cells: ['—', '—', 'c[ue]stan'] },
            { who: 'encontrar, to find (o → ue)', cells: ['enc[ue]ntro', 'encontramos', 'enc[ue]ntran'] },
            { who: 'jugar, to play (u → ue)', cells: ['j[ue]go', 'jugamos', 'j[ue]gan'] },
            { who: 'servir, to serve (e → i)', cells: ['s[i]rvo', 'servimos', 's[i]rven'] },
            { who: 'repetir, to repeat (e → i)', cells: ['rep[i]to', 'repetimos', 'rep[i]ten'] },
          ] },
      ],
      rules: [
        { t: 'The stem changes in yo, tú, él and ellos', ex: 'Quiero un café, pero mis amigos quieren té.', en: 'I want a coffee, but my friends want tea.' },
        { t: 'Nosotros keeps the plain stem', ex: 'Podemos ir mañana.', en: 'We can go tomorrow.' },
        { t: 'The endings stay regular', ex: 'Duermo ocho horas.', en: 'I sleep eight hours.' },
        { t: 'Jugar changes u to ue', ex: 'Los niños juegan en el parque.', en: 'The children are playing in the park.' },
      ],
      watch: [
        'The dictionary does not show the change: you have to learn which verbs have it. Querer, poder, pensar, dormir, volver and pedir are the ones you will use most.',
        'Only the stressed vowel changes. In nosotros the stress moves to the ending, so the stem stays: pensamos, dormimos.',
        'Tener and venir change e to ie too (tienes, viene), but their yo form is irregular: tengo, vengo.',
      ],
    },
    {
      id: 'present-yo', pl: 'Yo irregular', en: 'Irregular yo form', q: 'hago, tengo, conozco',
      summary: 'A group of very common verbs is irregular only in the yo form. Many add a g: hago, pongo, salgo, traigo, tengo, vengo, digo. Verbs in -cer and -cir add a z before the c: conozco, conduzco. A few are simply short: doy, veo, sé. The other persons are regular, apart from the stem changes of tener, venir and decir.',
      tables: [
        { title: 'Verbs with -go in the yo form',
          cols: [{ label: 'yo', tint: 'all' }, { label: 'tú', tint: 'all' }, { label: 'ellos', tint: 'all' }],
          rows: [
            { who: 'hacer, to do, make', cells: ['ha[go]', 'haces', 'hacen'] },
            { who: 'poner, to put', cells: ['pon[go]', 'pones', 'ponen'] },
            { who: 'salir, to go out', cells: ['sal[go]', 'sales', 'salen'] },
            { who: 'traer, to bring', cells: ['trai[go]', 'traes', 'traen'] },
            { who: 'oír, to hear', cells: ['oi[go]', 'o[y]es', 'o[y]en'] },
            { who: 'tener, to have', cells: ['ten[go]', 't[ie]nes', 't[ie]nen'] },
            { who: 'venir, to come', cells: ['ven[go]', 'v[ie]nes', 'v[ie]nen'] },
            { who: 'decir, to say', cells: ['di[go]', 'd[i]ces', 'd[i]cen'] },
          ] },
        { title: '-zco verbs and short yo forms',
          cols: [{ label: 'yo', tint: 'all' }, { label: 'tú', tint: 'all' }, { label: 'ellos', tint: 'all' }],
          rows: [
            { who: 'conocer, to know (a person, a place)', cells: ['cono[zc]o', 'conoces', 'conocen'] },
            { who: 'conducir, to drive', cells: ['condu[zc]o', 'conduces', 'conducen'] },
            { who: 'parecer, to seem', cells: ['pare[zc]o', 'pareces', 'parecen'] },
            { who: 'saber, to know (a fact)', cells: ['[sé]', 'sabes', 'saben'] },
            { who: 'dar, to give', cells: ['d[oy]', 'das', 'dan'] },
            { who: 'ver, to see', cells: ['v[eo]', 'ves', 'ven'] },
          ] },
      ],
      rules: [
        { t: 'Only the yo form is irregular', ex: 'Hago la cena y tú haces el postre.', en: 'I make dinner and you make dessert.' },
        { t: 'Tener, venir and decir also change their stem in the other persons', ex: 'Tengo un hermano; ¿tú cuántos tienes?', en: 'I have one brother; how many do you have?' },
        { t: '-cer and -cir verbs add z in the yo form', ex: 'No conozco a tu novio.', en: 'I don’t know your boyfriend.' },
        { t: 'Sé (I know) carries an accent to tell it apart from se', ex: 'No sé dónde está.', en: 'I don’t know where it is.' },
      ],
      watch: [
        'Saber is for facts and skills (sé nadar); conocer is for people and places (conozco Lima).',
        'Salgo, not salo; pongo, not pono. If a verb looks like it wants a g in the yo form, it probably does.',
        'Compound verbs follow their base verb: proponer → propongo, deshacer → deshago, reconocer → reconozco.',
      ],
    },
    {
      id: 'present-irr', pl: 'Ser, estar, ir', en: 'Irregular verbs', q: 'soy, estoy, voy',
      summary: 'The three most common verbs are irregular in almost every person. Ser (soy, eres, es) is for identity, origin, profession and time. Estar (estoy, estás, está) is for location and changing states. Ir (voy, vas, va) is to go, and also builds the near future: voy a comer.',
      tables: [
        { title: 'ser, estar, ir',
          cols: [{ label: 'ser', tint: 'all' }, { label: 'estar', tint: 'all' }, { label: 'ir', tint: 'all' }],
          rows: [
            { who: 'yo', cells: ['[soy]', 'est[oy]', '[voy]'] },
            { who: 'tú', cells: ['[eres]', 'est[ás]', '[vas]'] },
            { who: 'él / ella / usted', cells: ['[es]', 'est[á]', '[va]'] },
            { who: 'nosotros', cells: ['[somos]', 'estamos', '[vamos]'] },
            { who: 'ellos / ellas / ustedes', cells: ['[son]', 'est[án]', '[van]'] },
          ] },
        { title: 'ser or estar?',
          cols: [{ label: 'ser', tint: 'all' }, { label: 'estar', tint: 'all' }],
          rows: [
            { who: 'Used for', cells: ['who or what something is: identity, origin, job, material, time, events', 'where something is, and states that can change: mood, health, results'] },
            { who: 'Example', cells: ['Soy de Cali. Son las tres.', 'Estoy en Cali. Estoy cansado.'] },
            { who: 'English', cells: ['I’m from Cali. It’s three o’clock.', 'I’m in Cali. I’m tired.'] },
            { who: 'Watch', cells: ['La fiesta es en mi casa (an event takes place)', 'La casa está en el centro (a place is located)'] },
          ] },
      ],
      rules: [
        { t: 'Ser for identity, origin and profession', ex: 'Mi madre es médica.', en: 'My mother is a doctor.' },
        { t: 'Estar for location', ex: 'El banco está en la esquina.', en: 'The bank is on the corner.' },
        { t: 'Estar for feelings and states that change', ex: 'Estamos muy contentos.', en: 'We are very happy.' },
        { t: 'Ir a + place, and ir a + infinitive for plans', ex: 'Voy al gimnasio y luego voy a cocinar.', en: 'I’m going to the gym and then I’m going to cook.' },
      ],
      watch: [
        'Estás, está and están carry an accent; estamos does not.',
        'Some adjectives change meaning: es aburrido (he is boring) but está aburrido (he is bored); es listo (clever) but está listo (ready).',
        'Events use ser even though they happen somewhere: el concierto es en el estadio.',
        'Vamos also means let’s go: ¡Vamos!',
      ],
    },
    {
      id: 'present-reflex', pl: 'Reflexivos', en: 'Reflexive verbs', q: 'me levanto, te duchas',
      summary: 'Reflexive verbs carry a pronoun that matches the person: me, te, se, nos, se. The pronoun goes before the conjugated verb: me levanto, nos acostamos. The verb itself follows the usual patterns, including stem changes: me acuesto, se viste. Many daily-routine verbs are reflexive.',
      tables: [
        { title: 'Pronoun + verb',
          cols: [{ label: 'Pronoun', tint: 'all' }, { label: '-ar: levantarse', tint: 'all' }, { label: '-er: ponerse', tint: 'all' }, { label: '-ir: vestirse (e → i)', tint: 'all' }],
          rows: [
            { who: 'yo', cells: ['[me]', '[me] levanto', '[me] pongo', '[me] visto'] },
            { who: 'tú', cells: ['[te]', '[te] levantas', '[te] pones', '[te] vistes'] },
            { who: 'él / ella / usted', cells: ['[se]', '[se] levanta', '[se] pone', '[se] viste'] },
            { who: 'nosotros', cells: ['[nos]', '[nos] levantamos', '[nos] ponemos', '[nos] vestimos'] },
            { who: 'ellos / ellas / ustedes', cells: ['[se]', '[se] levantan', '[se] ponen', '[se] visten'] },
          ] },
        { title: 'Everyday reflexive verbs',
          cols: [{ label: 'yo', tint: 'all' }, { label: 'nosotros', tint: 'all' }, { label: 'ellos', tint: 'all' }],
          rows: [
            { who: 'despertarse, to wake up (e → ie)', cells: ['me desp[ie]rto', 'nos despertamos', 'se desp[ie]rtan'] },
            { who: 'ducharse, to shower', cells: ['me ducho', 'nos duchamos', 'se duchan'] },
            { who: 'acostarse, to go to bed (o → ue)', cells: ['me ac[ue]sto', 'nos acostamos', 'se ac[ue]stan'] },
            { who: 'sentirse, to feel (e → ie)', cells: ['me s[ie]nto', 'nos sentimos', 'se s[ie]nten'] },
            { who: 'llamarse, to be called', cells: ['me llamo', 'nos llamamos', 'se llaman'] },
            { who: 'lavarse, to wash', cells: ['me lavo', 'nos lavamos', 'se lavan'] },
            { who: 'dormirse, to fall asleep (o → ue)', cells: ['me d[ue]rmo', 'nos dormimos', 'se d[ue]rmen'] },
            { who: 'irse, to leave', cells: ['me voy', 'nos vamos', 'se van'] },
          ] },
      ],
      rules: [
        { t: 'The pronoun matches the person and goes before the verb', ex: 'Me ducho por la mañana.', en: 'I shower in the morning.' },
        { t: 'With an infinitive the pronoun can attach to its end', ex: 'Quiero acostarme temprano.', en: 'I want to go to bed early.' },
        { t: 'Stem changes still apply', ex: 'Los niños se acuestan a las ocho.', en: 'The children go to bed at eight.' },
        { t: 'Ustedes takes se, like ellos', ex: '¿A qué hora se levantan ustedes?', en: 'What time do you all get up?' },
      ],
      watch: [
        'With body parts and clothes Spanish uses the article, not a possessive: me lavo las manos, not mis manos.',
        'Some verbs change meaning with se: ir (to go) and irse (to leave); dormir (to sleep) and dormirse (to fall asleep).',
        'Me llamo Ana literally means I call myself Ana.',
      ],
    },
  ],

  sentences: [
    // Regulares
    { c: 'present-reg', s: 'Todos{every|m.pl} los{the|m.pl} días{day|m.pl} ___ con{with} mi{my} mamá{mom|f} por{on the} teléfono{phone|m}.', base: 'hablar', hint: 'yo', gloss: 'to speak', a: ['hablo'], p: 'yo', en: 'I talk to my mom on the phone every day.', why: 'Todos los días is a habit: presente. Yo with an -ar verb takes -o.' },
    { c: 'present-reg', s: 'Mi{my} hermano{brother|m} ___ en{in} un{a|m} banco{bank|m}.', base: 'trabajar', gloss: 'to work', a: ['trabaja'], p: 'él', en: 'My brother works in a bank.', why: 'A general fact about now: presente. Él with an -ar verb takes -a.' },
    { c: 'present-reg', s: '¿Tú{you} ___ carne{meat|f} o{or} eres{are you} vegetariana{vegetarian|f}?', base: 'comer', gloss: 'to eat', a: ['comes'], p: 'tú', en: 'Do you eat meat or are you a vegetarian?', why: 'Tú with an -er verb takes -es: comes.' },
    { c: 'present-reg', s: 'Mis{my} abuelos{grandparents|m.pl} ___ en{in} un{a|m} pueblo{village|m} cerca{near} de{of} Medellín{Medellín}.', base: 'vivir', gloss: 'to live', a: ['viven'], p: 'ellos', en: 'My grandparents live in a village near Medellín.', why: 'Ellos with an -ir verb takes -en, the same as -er verbs.' },
    { c: 'present-reg', s: 'Nosotros{we} ___ en{in} un{a|m} apartamento{apartment|m} pequeño{small|m}.', base: 'vivir', gloss: 'to live', a: ['vivimos'], p: 'nosotros', en: 'We live in a small apartment.', why: 'Nosotros is the one form where -ir differs from -er: vivimos, not vivemos.' },
    { c: 'present-reg', s: 'Los{on} domingos{Sunday|m.pl} ___ en{at} casa{home|f} de{of} mis{my} suegros{in-laws|m.pl}.', base: 'comer', hint: 'nosotros', gloss: 'to eat', a: ['comemos'], p: 'nosotros', en: 'On Sundays we eat at my in-laws’ house.', why: 'A weekly habit: presente. Nosotros with an -er verb takes -emos.' },
    { c: 'present-reg', s: '¿Ustedes{you all} ___ inglés{English|m}?', base: 'hablar', gloss: 'to speak', a: ['hablan'], p: 'ellos', en: 'Do you all speak English?', why: 'Ustedes takes the ellos form: hablan.' },
    { c: 'present-reg', s: 'Mi{my} hija{daughter|f} ___ un{a|m} libro{book|m} cada{every} semana{week|f}.', base: 'leer', gloss: 'to read', a: ['lee'], p: 'él', en: 'My daughter reads a book every week.', why: 'Leer is regular in the presente: le- plus -e gives lee.' },
    { c: 'present-reg', s: '___ español{Spanish|m} desde{since} hace{ago} dos{two} años{year|m.pl}.', base: 'estudiar', hint: 'yo', gloss: 'to study', a: ['Estudio', 'estudio'], p: 'yo', en: 'I have been studying Spanish for two years.', why: 'Something that started in the past and is still going on takes the presente in Spanish, not the perfecto: estudio.' },
    { c: 'present-reg', s: '¿A{at} qué{what} hora{time|f} ___ la{the|f} tienda{shop|f}?', base: 'abrir', gloss: 'to open', a: ['abre'], p: 'él', en: 'What time does the shop open?', why: 'A regular schedule: presente. Él with an -ir verb takes -e: abre.' },
    { c: 'present-reg', s: 'Tú{you} ___ muy{very} bien{well}; ¿dónde{where} aprendiste{did you learn}?', base: 'bailar', gloss: 'to dance', a: ['bailas'], p: 'tú', en: 'You dance really well; where did you learn?', why: 'Tú with an -ar verb takes -as: bailas.' },
    { c: 'present-reg', s: 'Mañana{tomorrow} ___ temprano{early}, así_que{so} no{not} puedo{I can} salir{go out} esta{this|f} noche{night|f}.', base: 'trabajar', hint: 'yo', gloss: 'to work', a: ['trabajo'], p: 'yo', en: 'I’m working early tomorrow, so I can’t go out tonight.', why: 'The presente also covers fixed plans for the near future: mañana trabajo.' },

    // Cambio de raíz
    { c: 'present-stem', s: '___ un{a|m} tinto{black coffee|m}, por_favor{please}.', base: 'querer', hint: 'yo', gloss: 'to want', a: ['Quiero', 'quiero'], p: 'yo', en: 'I’d like a black coffee, please.', why: 'Querer changes e to ie in the stressed stem: quiero.' },
    { c: 'present-stem', s: '¿Me{me} ___ ayudar{help} con{with} estas{these|f.pl} cajas{boxes|f.pl}?', base: 'poder', hint: 'tú', gloss: 'can, to be able to', a: ['puedes'], p: 'tú', en: 'Can you help me with these boxes?', why: 'Poder changes o to ue: puedes.' },
    { c: 'present-stem', s: 'Nosotros{we} no{not} ___ ir{go} a{to} la{the|f} reunión{meeting|f} mañana{tomorrow}.', base: 'poder', gloss: 'can, to be able to', a: ['podemos'], p: 'nosotros', en: 'We can’t go to the meeting tomorrow.', why: 'Nosotros keeps the plain stem because the stress falls on the ending: podemos.' },
    { c: 'present-stem', s: 'En{in} este{this|m} restaurante{restaurant|m} siempre{always} ___ la{the|f} bandeja{platter|f} paisa{from Antioquia|f}.', base: 'pedir', hint: 'yo', gloss: 'to order, ask for', a: ['pido'], p: 'yo', en: 'In this restaurant I always order the bandeja paisa.', why: 'Pedir changes e to i: pido.' },
    { c: 'present-stem', s: 'Los{the|m.pl} niños{children|m.pl} ___ fútbol{football|m} en{in} el{the|m} parque{park|m} todas{every|f.pl} las{the|f.pl} tardes{afternoon|f.pl}.', base: 'jugar', gloss: 'to play', a: ['juegan'], p: 'ellos', en: 'The children play football in the park every afternoon.', why: 'Jugar is the only verb where u becomes ue: juegan.' },
    { c: 'present-stem', s: '¿Cuánto{how much} ___ estos{these|m.pl} zapatos{shoes|m.pl}?', base: 'costar', gloss: 'to cost', a: ['cuestan'], p: 'ellos', en: 'How much do these shoes cost?', why: 'Costar changes o to ue, and the subject zapatos is plural: cuestan.' },
    { c: 'present-stem', s: 'Mi{my} papá{dad|m} ___ ocho{eight} horas{hour|f.pl} todas{every|f.pl} las{the|f.pl} noches{night|f.pl}.', base: 'dormir', gloss: 'to sleep', a: ['duerme'], p: 'él', en: 'My dad sleeps eight hours every night.', why: 'Dormir changes o to ue: duerme.' },
    { c: 'present-stem', s: 'La{the|f} película{film|f} ___ a{at} las{the|f.pl} ocho{eight}.', base: 'empezar', gloss: 'to begin', a: ['empieza'], p: 'él', en: 'The film starts at eight.', why: 'Empezar changes e to ie: empieza.' },
    { c: 'present-stem', s: 'No{not} ___ lo_que{what} dices{you say}; ¿puedes{can you} repetirlo{repeat it}?', base: 'entender', hint: 'yo', gloss: 'to understand', a: ['entiendo'], p: 'yo', en: 'I don’t understand what you’re saying; can you repeat it?', why: 'Entender changes e to ie: entiendo.' },
    { c: 'present-stem', s: '¿Qué{what} ___ de{about} mi{my} idea{idea|f}?', base: 'pensar', hint: 'tú', gloss: 'to think', a: ['piensas'], p: 'tú', en: 'What do you think of my idea?', why: 'Pensar changes e to ie: piensas.' },
    { c: 'present-stem', s: 'Nosotros{we} ___ a{to} casa{home|f} a{at} las{the|f.pl} seis{six}.', base: 'volver', gloss: 'to come back', a: ['volvemos'], p: 'nosotros', en: 'We get home at six.', why: 'Nosotros keeps the plain stem: volvemos, not vuelvemos.' },
    { c: 'present-stem', s: 'En{in} esta{this|f} cafetería{café|f} ___ el{the|m} mejor{best} café{coffee|m} de{in} la{the|f} ciudad{city|f}.', base: 'servir', hint: 'ellos', gloss: 'to serve', a: ['sirven'], p: 'ellos', en: 'This café serves the best coffee in the city.', why: 'Servir changes e to i: sirven. The subject is an unnamed they.' },

    // Yo irregular
    { c: 'present-yo', s: 'Los{on} sábados{Saturday|m.pl} ___ ejercicio{exercise|m} en{in} el{the|m} parque{park|m}.', base: 'hacer', hint: 'yo', gloss: 'to do, make', a: ['hago'], p: 'yo', en: 'On Saturdays I exercise in the park.', why: 'Hacer is irregular only in the yo form: hago.' },
    { c: 'present-yo', s: '___ dos{two} hermanos{brothers|m.pl} y{and} una{a|f} hermana{sister|f}.', base: 'tener', hint: 'yo', gloss: 'to have', a: ['Tengo', 'tengo'], p: 'yo', en: 'I have two brothers and a sister.', why: 'Tener adds a g in the yo form: tengo.' },
    { c: 'present-yo', s: '¿Cuántos{how many|m.pl} años{year|m.pl} ___?', base: 'tener', hint: 'tú', gloss: 'to have', a: ['tienes'], p: 'tú', en: 'How old are you?', why: 'Outside the yo form tener changes e to ie: tienes. Age uses tener in Spanish.' },
    { c: 'present-yo', s: 'Siempre{always} ___ de{from} la{the|f} oficina{office|f} a{at} las{the|f.pl} cinco{five}.', base: 'salir', hint: 'yo', gloss: 'to leave, go out', a: ['salgo'], p: 'yo', en: 'I always leave the office at five.', why: 'Salir adds a g in the yo form: salgo.' },
    { c: 'present-yo', s: 'No{not} ___ a{(to)} tu{your} novio{boyfriend|m}; ¿cómo{what} se{himself} llama{is he called}?', base: 'conocer', hint: 'yo', gloss: 'to know (a person)', a: ['conozco'], p: 'yo', en: 'I don’t know your boyfriend; what’s his name?', why: 'Verbs in -cer add z in the yo form: conozco. Conocer is for people and places.' },
    { c: 'present-yo', s: 'No{not} ___ dónde{where} están{are} mis{my} llaves{keys|f.pl}.', base: 'saber', hint: 'yo', gloss: 'to know (a fact)', a: ['sé'], p: 'yo', en: 'I don’t know where my keys are.', why: 'Saber has the short yo form sé, with an accent to tell it apart from the pronoun se.' },
    { c: 'present-yo', s: 'Yo{I} ___ la{the|f} ensalada{salad|f} y{and} tú{you} traes{bring} el{the|m} postre{dessert|m}.', base: 'traer', gloss: 'to bring', a: ['traigo'], p: 'yo', en: 'I’ll bring the salad and you bring the dessert.', why: 'Traer adds -ig- in the yo form: traigo.' },
    { c: 'present-yo', s: '¿Dónde{where} ___ las{the|f.pl} llaves{keys|f.pl}? ¿En{on} la{the|f} mesa{table|f}?', base: 'poner', hint: 'yo', gloss: 'to put', a: ['pongo'], p: 'yo', en: 'Where shall I put the keys? On the table?', why: 'Poner adds a g in the yo form: pongo.' },
    { c: 'present-yo', s: 'Mis{my} primos{cousins|m.pl} ___ a{to} visitarnos{visit us} en{at} Navidad{Christmas|f}.', base: 'venir', gloss: 'to come', a: ['vienen'], p: 'ellos', en: 'My cousins are coming to visit us at Christmas.', why: 'Outside the yo form venir changes e to ie: vienen.' },
    { c: 'present-yo', s: 'Siempre{always} te{you} ___ la{the|f} verdad{truth|f}.', base: 'decir', hint: 'yo', gloss: 'to tell, say', a: ['digo'], p: 'yo', en: 'I always tell you the truth.', why: 'Decir has the yo form digo.' },
    { c: 'present-yo', s: '¿Qué{what} ___ tú{you} en{in} la{the|f} foto{photo|f}?', base: 'ver', gloss: 'to see', a: ['ves'], p: 'tú', en: 'What do you see in the photo?', why: 'Ver is irregular only in yo (veo); tú is regular: ves.' },
    { c: 'present-yo', s: 'Yo{I} ___ al{to the|m} trabajo{work|m} porque{because} el{the|m} bus{bus|m} tarda{takes} mucho{a long time}.', base: 'conducir', gloss: 'to drive', a: ['conduzco'], p: 'yo', en: 'I drive to work because the bus takes too long.', why: 'Verbs in -cir add z in the yo form: conduzco.' },

    // Ser, estar, ir
    { c: 'present-irr', s: '___ de{from} Barranquilla{Barranquilla}, pero{but} vivo{I live} en{in} Bogotá{Bogotá}.', base: 'ser', hint: 'yo', gloss: 'to be', a: ['Soy', 'soy'], p: 'yo', en: 'I’m from Barranquilla, but I live in Bogotá.', why: 'Origin takes ser: soy de Barranquilla.' },
    { c: 'present-irr', s: '___ en{in} Bogotá{Bogotá} por{for} trabajo{work|m} esta{this|f} semana{week|f}.', base: 'estar', hint: 'yo', gloss: 'to be', a: ['Estoy', 'estoy'], p: 'yo', en: 'I’m in Bogotá for work this week.', why: 'Location takes estar: estoy.' },
    { c: 'present-irr', s: 'Mi{my} madre{mother|f} ___ médica{doctor|f}.', base: 'ser', gloss: 'to be', a: ['es'], p: 'él', en: 'My mother is a doctor.', why: 'A profession takes ser: es.' },
    { c: 'present-irr', s: '¿Cómo{how} ___ tú{you}? ¿Mejor{better}?', base: 'estar', gloss: 'to be', a: ['estás'], p: 'tú', en: 'How are you? Better?', why: 'Health and feelings take estar. Estás carries an accent.' },
    { c: 'present-irr', s: 'Nosotros{we} ___ hermanos{siblings|m.pl}, aunque{although} no{not} nos{each other} parecemos{we look like}.', base: 'ser', gloss: 'to be', a: ['somos'], p: 'nosotros', en: 'We’re siblings, although we don’t look alike.', why: 'Identity and relationships take ser: somos.' },
    { c: 'present-irr', s: 'Los{the|m.pl} niños{children|m.pl} ___ muy{very} cansados{tired|m.pl} después_de{after} la{the|f} excursión{trip|f}.', base: 'estar', gloss: 'to be', a: ['están'], p: 'ellos', en: 'The children are very tired after the trip.', why: 'A temporary state takes estar: están, with an accent.' },
    { c: 'present-irr', s: 'Todos{every|m.pl} los{the|m.pl} viernes{Friday|m.pl} ___ al{to the|m} cine{cinema|m} con{with} mis{my} amigas{friends|f.pl}.', base: 'ir', hint: 'yo', gloss: 'to go', a: ['voy'], p: 'yo', en: 'Every Friday I go to the cinema with my friends.', why: 'Ir is irregular: yo voy.' },
    { c: 'present-irr', s: '¿Ustedes{you all} ___ a{to} la{the|f} playa{beach|f} este{this|m} fin_de_semana{weekend|m}?', base: 'ir', gloss: 'to go', a: ['van'], p: 'ellos', en: 'Are you all going to the beach this weekend?', why: 'Ustedes takes the ellos form of ir: van.' },
    { c: 'present-irr', s: 'La{the|f} fiesta{party|f} ___ en{at} mi{my} casa{house|f} el{on the|m} sábado{Saturday|m}.', base: 'ser', gloss: 'to be', a: ['es'], p: 'él', en: 'The party is at my house on Saturday.', why: 'An event takes ser even when you say where it happens: la fiesta es en mi casa.' },
    { c: 'present-irr', s: 'El{the|m} banco{bank|m} ___ en{on} la{the|f} esquina{corner|f}.', base: 'estar', gloss: 'to be', a: ['está'], p: 'él', en: 'The bank is on the corner.', why: 'The location of a place takes estar: está.' },
    { c: 'present-irr', s: '___ las{the|f.pl} tres{three} y{and} media{half|f}.', base: 'ser', gloss: 'to be', a: ['Son', 'son'], p: 'ellos', en: 'It’s half past three.', why: 'Time takes ser, plural with any hour but one: son las tres.' },
    { c: 'present-irr', s: 'Tú{you} ___ muy{very} inteligente{clever}, pero{but} un{a bit} poco{little} perezoso{lazy|m}.', base: 'ser', gloss: 'to be', a: ['eres'], p: 'tú', en: 'You’re very clever, but a bit lazy.', why: 'Character traits take ser: tú eres.' },

    // Reflexivos
    { c: 'present-reflex', s: 'Entre_semana{on weekdays} ___ a{at} las{the|f.pl} seis{six}.', base: 'levantarse', hint: 'yo', gloss: 'to get up', a: ['me levanto'], p: 'yo', en: 'On weekdays I get up at six.', why: 'Yo takes me before the verb: me levanto.' },
    { c: 'present-reflex', s: '¿A{at} qué{what} hora{time|f} ___ tú{you}?', base: 'levantarse', gloss: 'to get up', a: ['te levantas'], p: 'tú', en: 'What time do you get up?', why: 'Tú takes te: te levantas.' },
    { c: 'present-reflex', s: 'Mi{my} hermana{sister|f} ___ por{in} la{the|f} noche{night|f}.', base: 'ducharse', gloss: 'to shower', a: ['se ducha'], p: 'él', en: 'My sister showers at night.', why: 'Él and ella take se: se ducha.' },
    { c: 'present-reflex', s: 'Los{the|m.pl} niños{children|m.pl} ___ a{at} las{the|f.pl} ocho{eight}.', base: 'acostarse', gloss: 'to go to bed', a: ['se acuestan'], p: 'ellos', en: 'The children go to bed at eight.', why: 'Ellos takes se, and acostarse changes o to ue: se acuestan.' },
    { c: 'present-reflex', s: '___ Andrés{Andrés}, ¿y{and} tú{you}?', base: 'llamarse', hint: 'yo', gloss: 'to be called', a: ['Me llamo', 'me llamo'], p: 'yo', en: 'My name is Andrés, and yours?', why: 'Llamarse is reflexive: me llamo, literally I call myself.' },
    { c: 'present-reflex', s: 'Los{on} domingos{Sunday|m.pl} ___ tarde{late}.', base: 'despertarse', hint: 'nosotros', gloss: 'to wake up', a: ['nos despertamos'], p: 'nosotros', en: 'On Sundays we wake up late.', why: 'Nosotros takes nos, and keeps the plain stem: nos despertamos.' },
    { c: 'present-reflex', s: 'Hoy{today} no{not} ___ bien{well}; creo{I think} que{that} tengo{I have} gripa{the flu|f}.', base: 'sentirse', hint: 'yo', gloss: 'to feel', a: ['me siento'], p: 'yo', en: 'I don’t feel well today; I think I have the flu.', why: 'Sentirse changes e to ie and takes me: me siento.' },
    { c: 'present-reflex', s: 'Mi{my} abuelo{grandfather|m} siempre{always} ___ elegante{smartly} para{for} ir{going} a{to} misa{mass|f}.', base: 'vestirse', gloss: 'to get dressed', a: ['se viste'], p: 'él', en: 'My grandfather always dresses smartly to go to mass.', why: 'Vestirse changes e to i and takes se: se viste.' },
    { c: 'present-reflex', s: 'Ya{already} es{it is} tarde{late}; nosotros{we} ___.', base: 'irse', gloss: 'to leave', a: ['nos vamos'], p: 'nosotros', en: 'It’s late now; we’re off.', why: 'Irse means to leave: nos vamos.' },
    { c: 'present-reflex', s: '¿Ustedes{you all} ya{already} ___ la{the|f} chaqueta{jacket|f}? Hace{it is} frío{cold|m}.', base: 'ponerse', gloss: 'to put on', a: ['se ponen'], p: 'ellos', en: 'Are you all putting your jackets on? It’s cold.', why: 'Ustedes takes se, like ellos: se ponen.' },
    { c: 'present-reflex', s: 'Antes_de{before} comer{eating} ___ las{the|f.pl} manos{hands|f.pl}.', base: 'lavarse', hint: 'yo', gloss: 'to wash', a: ['me lavo'], p: 'yo', en: 'I wash my hands before eating.', why: 'Lavarse takes me for yo. With body parts Spanish uses las manos, not mis manos.' },
    { c: 'present-reflex', s: 'Siempre{always} ___ en{in} el{the|m} cine{cinema|m}; las{the|f.pl} películas{films|f.pl} te{you} aburren{bore}.', base: 'dormirse', hint: 'tú', gloss: 'to fall asleep', a: ['te duermes'], p: 'tú', en: 'You always fall asleep at the cinema; films bore you.', why: 'Dormirse is to fall asleep. Tú takes te, and dormir changes o to ue: te duermes.' },
  ],
};
