/* Present (presente): reference tables and quiz sentences.
   Latin American Spanish: the plural “you” is ustedes, which takes the ellos form.
   In tables, [square brackets] mark the part of the form to highlight.
   In sentences, word{gloss} gives the hover translation and ___ is the gap. */

const PRESENT_TENSE = {
  id: 'present', pl: 'Presente', en: 'Present',
  intro: 'The presente covers what you do in general, what is happening now, and even plans for the near future: mañana trabajo. Regular verbs drop -ar, -er or -ir and add one ending per person. Many common verbs change a vowel in the stem, a group of verbs is irregular only in the yo form, and ser, estar and ir are irregular throughout. In Latin America “you” in the plural is ustedes, which takes the ellos form.',

  groups: [
    {
      id: 'present-reg', pl: 'Regulares', short: 'Regul.', ini: 'R', en: 'Regular verbs', q: 'hablo, comes, vive',
      summary: 'Drop the -ar, -er or -ir and add the ending for the person. -ar verbs use a: hablo, hablas, habla, hablamos, hablan. -er and -ir verbs use e, and share every ending except nosotros: comemos, vivimos.',
      tables: [
        { title: 'hablar, comer, vivir: three sets of endings',
          cols: [{ label: '-ar', tint: 'all' }, { label: '-er', tint: 'all' }, { label: '-ir', tint: 'all' }],
          rows: [
            { who: 'yo', cells: ['habl[o]', 'com[o]', 'viv[o]'] },
            { who: 'tú', cells: ['habl[as]', 'com[es]', 'viv[es]'] },
            { who: 'él / ella / usted', cells: ['habl[a]', 'com[e]', 'viv[e]'] },
            { who: 'nosotros', cells: ['habl[amos]', 'com[emos]', 'viv[imos]'] },
            { who: 'ellos / ellas / ustedes', cells: ['habl[an]', 'com[en]', 'viv[en]'] },
          ] },
        { title: 'Other regular verbs',
          cols: [{ label: 'yo', tint: 'all' }, { label: 'nosotros', tint: 'all' }, { label: 'ellos', tint: 'all' }],
          forms: [{ cols: [{ label: 'presente', tint: 'all' }], who: ['yo', 'tú', 'él / ella / usted', 'nosotros', 'ellos / ellas / ustedes'] }],
          rows: [
            { who: 'trabajar, to work', cells: ['trabaj[o]', 'trabaj[amos]', 'trabaj[an]'],
              forms: ['trabaj[o]', 'trabaj[as]', 'trabaj[a]', 'trabaj[amos]', 'trabaj[an]'] },
            { who: 'estudiar, to study', cells: ['estudi[o]', 'estudi[amos]', 'estudi[an]'],
              forms: ['estudi[o]', 'estudi[as]', 'estudi[a]', 'estudi[amos]', 'estudi[an]'] },
            { who: 'aprender, to learn', cells: ['aprend[o]', 'aprend[emos]', 'aprend[en]'],
              forms: ['aprend[o]', 'aprend[es]', 'aprend[e]', 'aprend[emos]', 'aprend[en]'] },
            { who: 'leer, to read', cells: ['le[o]', 'le[emos]', 'le[en]'],
              forms: ['le[o]', 'le[es]', 'le[e]', 'le[emos]', 'le[en]'] },
            { who: 'escribir, to write', cells: ['escrib[o]', 'escrib[imos]', 'escrib[en]'],
              forms: ['escrib[o]', 'escrib[es]', 'escrib[e]', 'escrib[imos]', 'escrib[en]'] },
            { who: 'abrir, to open', cells: ['abr[o]', 'abr[imos]', 'abr[en]'],
              forms: ['abr[o]', 'abr[es]', 'abr[e]', 'abr[imos]', 'abr[en]'] },
          ] },
        { title: 'What the presente is used for',
          cols: [{ label: 'Example', tint: 'all' }, { label: 'English', tint: 'all' }],
          rows: [
            { who: 'habits', cells: ['Siempre desayuno a las siete.', 'I always have breakfast at seven.'] },
            { who: 'right now', cells: ['¿Qué haces? Leo el periódico.', 'What are you doing? I’m reading the paper.'] },
            { who: 'facts', cells: ['El agua hierve a cien grados.', 'Water boils at a hundred degrees.'] },
            { who: 'near future', cells: ['Mañana trabajo hasta tarde.', 'Tomorrow I’m working late.'] },
            { who: 'since when', cells: ['Vivo aquí desde 2020.', 'I have lived here since 2020.'] },
          ] },
      ],
      rules: [
        { t: 'Yo always ends in -o', ex: 'Trabajo en un banco.', en: 'I work in a bank.' },
        { t: '-er and -ir verbs differ only in the nosotros form', ex: 'Comemos juntos y vivimos cerca.', en: 'We eat together and we live nearby.' },
        { t: 'Ustedes takes the ellos form', ex: '¿Ustedes hablan inglés?', en: 'Do you all speak English?' },
        { t: 'The presente can describe what is happening right now', ex: '¿Qué lees?', en: 'What are you reading?' },
        { t: 'Desde and hace + presente for something that is still going on', ex: 'Estudio español hace dos años.', en: 'I have been studying Spanish for two years.' },
      ],
      watch: [
        'Hablo (I speak) has no accent; habló (he spoke) does. The accent changes the tense.',
        'English “I have lived here since 2020” is the presente in Spanish: vivo aquí desde 2020, not he vivido.',
        'The pronoun is usually left out because the ending shows the person: hablo, not yo hablo, unless you want to stress who.',
      ],
    },
    {
      id: 'present-stem', pl: 'Cambio de raíz', short: 'Raíz', ini: 'C', en: 'Stem-changing verbs', q: 'quiero, puedo, pido',
      summary: 'In many common verbs the stressed vowel of the stem changes: e becomes ie (querer → quiero), o becomes ue (poder → puedo), or e becomes i (pedir → pido). The change happens in every person except nosotros, where the stress falls on the ending. Jugar is the only verb where u becomes ue.',
      tables: [
        { title: 'The three stem changes',
          cols: [{ label: 'e → ie: querer', tint: 'all' }, { label: 'o → ue: poder', tint: 'all' }, { label: 'e → i: pedir', tint: 'all' }],
          rows: [
            { who: 'yo', cells: ['qu[ie]ro', 'p[ue]do', 'p[i]do'] },
            { who: 'tú', cells: ['qu[ie]res', 'p[ue]des', 'p[i]des'] },
            { who: 'él / ella / usted', cells: ['qu[ie]re', 'p[ue]de', 'p[i]de'] },
            { who: 'nosotros', cells: ['queremos', 'podemos', 'pedimos'] },
            { who: 'ellos / ellas / ustedes', cells: ['qu[ie]ren', 'p[ue]den', 'p[i]den'] },
          ] },
        { title: 'More stem-changing verbs',
          cols: [{ label: 'yo', tint: 'all' }, { label: 'nosotros', tint: 'all' }, { label: 'ellos', tint: 'all' }],
          forms: [{ cols: [{ label: 'presente', tint: 'all' }], who: ['yo', 'tú', 'él / ella / usted', 'nosotros', 'ellos / ellas / ustedes'] }],
          rows: [
            { who: 'pensar, to think (e → ie)', cells: ['p[ie]nso', 'pensamos', 'p[ie]nsan'],
              forms: ['p[ie]nso', 'p[ie]nsas', 'p[ie]nsa', 'pensamos', 'p[ie]nsan'] },
            { who: 'empezar, to begin (e → ie)', cells: ['emp[ie]zo', 'empezamos', 'emp[ie]zan'],
              forms: ['emp[ie]zo', 'emp[ie]zas', 'emp[ie]za', 'empezamos', 'emp[ie]zan'] },
            { who: 'preferir, to prefer (e → ie)', cells: ['pref[ie]ro', 'preferimos', 'pref[ie]ren'],
              forms: ['pref[ie]ro', 'pref[ie]res', 'pref[ie]re', 'preferimos', 'pref[ie]ren'] },
            { who: 'entender, to understand (e → ie)', cells: ['ent[ie]ndo', 'entendemos', 'ent[ie]nden'],
              forms: ['ent[ie]ndo', 'ent[ie]ndes', 'ent[ie]nde', 'entendemos', 'ent[ie]nden'] },
            { who: 'dormir, to sleep (o → ue)', cells: ['d[ue]rmo', 'dormimos', 'd[ue]rmen'],
              forms: ['d[ue]rmo', 'd[ue]rmes', 'd[ue]rme', 'dormimos', 'd[ue]rmen'] },
            { who: 'volver, to come back (o → ue)', cells: ['v[ue]lvo', 'volvemos', 'v[ue]lven'],
              forms: ['v[ue]lvo', 'v[ue]lves', 'v[ue]lve', 'volvemos', 'v[ue]lven'] },
            { who: 'costar, to cost (o → ue)', cells: ['—', '—', 'c[ue]stan'],
              forms: ['c[ue]sto', 'c[ue]stas', 'c[ue]sta', 'costamos', 'c[ue]stan'] },
            { who: 'encontrar, to find (o → ue)', cells: ['enc[ue]ntro', 'encontramos', 'enc[ue]ntran'],
              forms: ['enc[ue]ntro', 'enc[ue]ntras', 'enc[ue]ntra', 'encontramos', 'enc[ue]ntran'] },
            { who: 'jugar, to play (u → ue)', cells: ['j[ue]go', 'jugamos', 'j[ue]gan'],
              forms: ['j[ue]go', 'j[ue]gas', 'j[ue]ga', 'jugamos', 'j[ue]gan'] },
            { who: 'servir, to serve (e → i)', cells: ['s[i]rvo', 'servimos', 's[i]rven'],
              forms: ['s[i]rvo', 's[i]rves', 's[i]rve', 'servimos', 's[i]rven'] },
            { who: 'repetir, to repeat (e → i)', cells: ['rep[i]to', 'repetimos', 'rep[i]ten'],
              forms: ['rep[i]to', 'rep[i]tes', 'rep[i]te', 'repetimos', 'rep[i]ten'] },
          ] },
      ],
      rules: [
        { t: 'The stem changes in yo, tú, él and ellos', ex: 'Quiero un café, pero mis amigos quieren té.', en: 'I want a coffee, but my friends want tea.' },
        { t: 'Nosotros keeps the plain stem', ex: 'Podemos ir mañana.', en: 'We can go tomorrow.' },
        { t: 'The endings stay regular', ex: 'Duermo ocho horas.', en: 'I sleep eight hours.' },
        { t: 'Jugar changes u to ue', ex: 'Los niños juegan en el parque.', en: 'The children are playing in the park.' },
      ],
      watch: [
        'The dictionary does not show the change: you have to learn which verbs have it. Querer, poder, pensar, dormir, volver and pedir are the ones you will use most.',
        'Only the stressed vowel changes. In nosotros the stress moves to the ending, so the stem stays: pensamos, dormimos.',
        'Tener and venir change e to ie too (tienes, viene), but their yo form is irregular: tengo, vengo.',
      ],
    },
    {
      id: 'present-yo', pl: 'Yo irregular', short: 'Yo irr.', ini: 'Y', en: 'Irregular yo form', q: 'hago, tengo, conozco',
      summary: 'A group of very common verbs is irregular only in the yo form. Many add a g: hago, pongo, salgo, traigo, tengo, vengo, digo. Verbs in -cer and -cir add a z before the c: conozco, conduzco. A few are simply short: doy, veo, sé. The other persons are regular, apart from the stem changes of tener, venir and decir.',
      tables: [
        { title: 'Verbs with -go in the yo form',
          cols: [{ label: 'yo', tint: 'all' }, { label: 'tú', tint: 'all' }, { label: 'ellos', tint: 'all' }],
          forms: [{ cols: [{ label: 'presente', tint: 'all' }], who: ['yo', 'tú', 'él / ella / usted', 'nosotros', 'ellos / ellas / ustedes'] }],
          rows: [
            { who: 'hacer, to do, make', cells: ['ha[go]', 'haces', 'hacen'],
              forms: ['ha[go]', 'haces', 'hace', 'hacemos', 'hacen'] },
            { who: 'poner, to put', cells: ['pon[go]', 'pones', 'ponen'],
              forms: ['pon[go]', 'pones', 'pone', 'ponemos', 'ponen'] },
            { who: 'salir, to go out', cells: ['sal[go]', 'sales', 'salen'],
              forms: ['sal[go]', 'sales', 'sale', 'salimos', 'salen'] },
            { who: 'traer, to bring', cells: ['trai[go]', 'traes', 'traen'],
              forms: ['trai[go]', 'traes', 'trae', 'traemos', 'traen'] },
            { who: 'oír, to hear', cells: ['oi[go]', 'o[y]es', 'o[y]en'],
              forms: ['oi[go]', 'o[y]es', 'o[y]e', 'oímos', 'o[y]en'] },
            { who: 'tener, to have', cells: ['ten[go]', 't[ie]nes', 't[ie]nen'],
              forms: ['ten[go]', 't[ie]nes', 't[ie]ne', 'tenemos', 't[ie]nen'] },
            { who: 'venir, to come', cells: ['ven[go]', 'v[ie]nes', 'v[ie]nen'],
              forms: ['ven[go]', 'v[ie]nes', 'v[ie]ne', 'venimos', 'v[ie]nen'] },
            { who: 'decir, to say', cells: ['di[go]', 'd[i]ces', 'd[i]cen'],
              forms: ['di[go]', 'd[i]ces', 'd[i]ce', 'decimos', 'd[i]cen'] },
          ] },
        { title: '-zco verbs and short yo forms',
          cols: [{ label: 'yo', tint: 'all' }, { label: 'tú', tint: 'all' }, { label: 'ellos', tint: 'all' }],
          forms: [{ cols: [{ label: 'presente', tint: 'all' }], who: ['yo', 'tú', 'él / ella / usted', 'nosotros', 'ellos / ellas / ustedes'] }],
          rows: [
            { who: 'conocer, to know (a person, a place)', cells: ['cono[zc]o', 'conoces', 'conocen'],
              forms: ['cono[zc]o', 'conoces', 'conoce', 'conocemos', 'conocen'] },
            { who: 'conducir, to drive', cells: ['condu[zc]o', 'conduces', 'conducen'],
              forms: ['condu[zc]o', 'conduces', 'conduce', 'conducimos', 'conducen'] },
            { who: 'parecer, to seem', cells: ['pare[zc]o', 'pareces', 'parecen'],
              forms: ['pare[zc]o', 'pareces', 'parece', 'parecemos', 'parecen'] },
            { who: 'saber, to know (a fact)', cells: ['[sé]', 'sabes', 'saben'],
              forms: ['[sé]', 'sabes', 'sabe', 'sabemos', 'saben'] },
            { who: 'dar, to give', cells: ['d[oy]', 'das', 'dan'],
              forms: ['d[oy]', 'das', 'da', 'damos', 'dan'] },
            { who: 'ver, to see', cells: ['v[eo]', 'ves', 'ven'],
              forms: ['v[eo]', 'ves', 've', 'vemos', 'ven'] },
          ] },
      ],
      rules: [
        { t: 'Only the yo form is irregular', ex: 'Hago la cena y tú haces el postre.', en: 'I make dinner and you make dessert.' },
        { t: 'Tener, venir and decir also change their stem in the other persons', ex: 'Tengo un hermano; ¿tú cuántos tienes?', en: 'I have one brother; how many do you have?' },
        { t: '-cer and -cir verbs add z in the yo form', ex: 'No conozco a tu novio.', en: 'I don’t know your boyfriend.' },
        { t: 'Sé (I know) carries an accent to tell it apart from se', ex: 'No sé dónde está.', en: 'I don’t know where it is.' },
      ],
      watch: [
        'Saber is for facts and skills (sé nadar); conocer is for people and places (conozco Lima).',
        'Salgo, not salo; pongo, not pono. If a verb looks like it wants a g in the yo form, it probably does.',
        'Compound verbs follow their base verb: proponer → propongo, deshacer → deshago, reconocer → reconozco.',
      ],
    },
    {
      id: 'present-irr', pl: 'Ser, estar, ir', short: 'Irreg.', ini: 'I', en: 'Irregular verbs', q: 'soy, estoy, voy',
      summary: 'The three most common verbs are irregular in almost every person. Ser (soy, eres, es) is for identity, origin, profession and time. Estar (estoy, estás, está) is for location and changing states. Ir (voy, vas, va) is to go, and also builds the near future: voy a comer.',
      tables: [
        { title: 'ser, estar, ir',
          cols: [{ label: 'ser', tint: 'all' }, { label: 'estar', tint: 'all' }, { label: 'ir', tint: 'all' }],
          rows: [
            { who: 'yo', cells: ['[soy]', 'est[oy]', '[voy]'] },
            { who: 'tú', cells: ['[eres]', 'est[ás]', '[vas]'] },
            { who: 'él / ella / usted', cells: ['[es]', 'est[á]', '[va]'] },
            { who: 'nosotros', cells: ['[somos]', 'estamos', '[vamos]'] },
            { who: 'ellos / ellas / ustedes', cells: ['[son]', 'est[án]', '[van]'] },
          ] },
        { title: 'ser or estar?',
          cols: [{ label: 'ser', tint: 'all' }, { label: 'estar', tint: 'all' }],
          rows: [
            { who: 'Used for', cells: ['who or what something is: identity, origin, job, material, time, events', 'where something is, and states that can change: mood, health, results'] },
            { who: 'Example', cells: ['Soy de Cali. Son las tres.', 'Estoy en Cali. Estoy cansado.'] },
            { who: 'English', cells: ['I’m from Cali. It’s three o’clock.', 'I’m in Cali. I’m tired.'] },
            { who: 'Watch', cells: ['La fiesta es en mi casa (an event takes place)', 'La casa está en el centro (a place is located)'] },
          ] },
      ],
      rules: [
        { t: 'Ser for identity, origin and profession', ex: 'Mi madre es médica.', en: 'My mother is a doctor.' },
        { t: 'Estar for location', ex: 'El banco está en la esquina.', en: 'The bank is on the corner.' },
        { t: 'Estar for feelings and states that change', ex: 'Estamos muy contentos.', en: 'We are very happy.' },
        { t: 'Ir a + place, and ir a + infinitive for plans', ex: 'Voy al gimnasio y luego voy a cocinar.', en: 'I’m going to the gym and then I’m going to cook.' },
      ],
      watch: [
        'Estás, está and están carry an accent; estamos does not.',
        'Some adjectives change meaning: es aburrido (he is boring) but está aburrido (he is bored); es listo (clever) but está listo (ready).',
        'Events use ser even though they happen somewhere: el concierto es en el estadio.',
        'Vamos also means let’s go: ¡Vamos!',
      ],
    },
    {
      id: 'present-reflex', pl: 'Reflexivos', short: 'Reflex.', ini: 'Se', en: 'Reflexive verbs', q: 'me levanto, te duchas',
      summary: 'Reflexive verbs carry a pronoun that matches the person: me, te, se, nos, se. The pronoun goes before the conjugated verb: me levanto, nos acostamos. The verb itself follows the usual patterns, including stem changes: me acuesto, se viste. Many daily-routine verbs are reflexive.',
      tables: [
        { title: 'Pronoun + verb',
          cols: [{ label: 'Pronoun', tint: 'all' }, { label: '-ar: levantarse', tint: 'all' }, { label: '-er: ponerse', tint: 'all' }, { label: '-ir: vestirse (e → i)', tint: 'all' }],
          rows: [
            { who: 'yo', cells: ['[me]', '[me] levanto', '[me] pongo', '[me] visto'] },
            { who: 'tú', cells: ['[te]', '[te] levantas', '[te] pones', '[te] vistes'] },
            { who: 'él / ella / usted', cells: ['[se]', '[se] levanta', '[se] pone', '[se] viste'] },
            { who: 'nosotros', cells: ['[nos]', '[nos] levantamos', '[nos] ponemos', '[nos] vestimos'] },
            { who: 'ellos / ellas / ustedes', cells: ['[se]', '[se] levantan', '[se] ponen', '[se] visten'] },
          ] },
        { title: 'Everyday reflexive verbs',
          cols: [{ label: 'yo', tint: 'all' }, { label: 'nosotros', tint: 'all' }, { label: 'ellos', tint: 'all' }],
          forms: [{ cols: [{ label: 'presente', tint: 'all' }], who: ['yo', 'tú', 'él / ella / usted', 'nosotros', 'ellos / ellas / ustedes'] }],
          rows: [
            { who: 'despertarse, to wake up (e → ie)', cells: ['me desp[ie]rto', 'nos despertamos', 'se desp[ie]rtan'],
              forms: ['me desp[ie]rto', 'te desp[ie]rtas', 'se desp[ie]rta', 'nos despertamos', 'se desp[ie]rtan'] },
            { who: 'ducharse, to shower', cells: ['me ducho', 'nos duchamos', 'se duchan'],
              forms: ['me duch[o]', 'te duch[as]', 'se duch[a]', 'nos duch[amos]', 'se duch[an]'] },
            { who: 'acostarse, to go to bed (o → ue)', cells: ['me ac[ue]sto', 'nos acostamos', 'se ac[ue]stan'],
              forms: ['me ac[ue]sto', 'te ac[ue]stas', 'se ac[ue]sta', 'nos acostamos', 'se ac[ue]stan'] },
            { who: 'sentirse, to feel (e → ie)', cells: ['me s[ie]nto', 'nos sentimos', 'se s[ie]nten'],
              forms: ['me s[ie]nto', 'te s[ie]ntes', 'se s[ie]nte', 'nos sentimos', 'se s[ie]nten'] },
            { who: 'llamarse, to be called', cells: ['me llamo', 'nos llamamos', 'se llaman'],
              forms: ['me llam[o]', 'te llam[as]', 'se llam[a]', 'nos llam[amos]', 'se llam[an]'] },
            { who: 'lavarse, to wash', cells: ['me lavo', 'nos lavamos', 'se lavan'],
              forms: ['me lav[o]', 'te lav[as]', 'se lav[a]', 'nos lav[amos]', 'se lav[an]'] },
            { who: 'dormirse, to fall asleep (o → ue)', cells: ['me d[ue]rmo', 'nos dormimos', 'se d[ue]rmen'],
              forms: ['me d[ue]rmo', 'te d[ue]rmes', 'se d[ue]rme', 'nos dormimos', 'se d[ue]rmen'] },
            { who: 'irse, to leave', cells: ['me voy', 'nos vamos', 'se van'],
              forms: ['me [voy]', 'te [vas]', 'se [va]', 'nos [vamos]', 'se [van]'] },
          ] },
      ],
      rules: [
        { t: 'The pronoun matches the person and goes before the verb', ex: 'Me ducho por la mañana.', en: 'I shower in the morning.' },
        { t: 'With an infinitive the pronoun can attach to its end', ex: 'Quiero acostarme temprano.', en: 'I want to go to bed early.' },
        { t: 'Stem changes still apply', ex: 'Los niños se acuestan a las ocho.', en: 'The children go to bed at eight.' },
        { t: 'Ustedes takes se, like ellos', ex: '¿A qué hora se levantan ustedes?', en: 'What time do you all get up?' },
      ],
      watch: [
        'With body parts and clothes Spanish uses the article, not a possessive: me lavo las manos, not mis manos.',
        'Some verbs change meaning with se: ir (to go) and irse (to leave); dormir (to sleep) and dormirse (to fall asleep).',
        'Me llamo Ana literally means I call myself Ana.',
      ],
    },
  ],

  sentences: [
    // Regulares
    { c: 'present-reg', s: 'Todos{every|m.pl} los{the|m.pl} días{day|m.pl} ___ con{with} mi{my} mamá{mom|f} por{on the} teléfono{phone|m}.', base: 'hablar', hint: 'yo', gloss: 'to speak', a: ['hablo'], p: 'yo', en: 'I talk to my mom on the phone every day.', why: 'Todos los días is a habit: presente. Yo with an -ar verb takes -o.' },
    { c: 'present-reg', s: 'Mi{my} hermano{brother|m} ___ en{in} un{a|m} banco{bank|m}.', base: 'trabajar', gloss: 'to work', a: ['trabaja'], p: 'él', en: 'My brother works in a bank.', why: 'A general fact about now: presente. Él with an -ar verb takes -a.' },
    { c: 'present-reg', s: '¿Tú{you} ___ carne{meat|f} o{or} eres{are you} vegetariana{vegetarian|f}?', base: 'comer', gloss: 'to eat', a: ['comes'], p: 'tú', en: 'Do you eat meat or are you a vegetarian?', why: 'Tú with an -er verb takes -es: comes.' },
    { c: 'present-reg', s: 'Mis{my} abuelos{grandparents|m.pl} ___ en{in} un{a|m} pueblo{village|m} cerca{near} de{of} Medellín{Medellín}.', base: 'vivir', gloss: 'to live', a: ['viven'], p: 'ellos', en: 'My grandparents live in a village near Medellín.', why: 'Ellos with an -ir verb takes -en, the same as -er verbs.' },
    { c: 'present-reg', s: 'Nosotros{we} ___ en{in} un{a|m} apartamento{apartment|m} pequeño{small|m}.', base: 'vivir', gloss: 'to live', a: ['vivimos'], p: 'nosotros', en: 'We live in a small apartment.', why: 'Nosotros is the one form where -ir differs from -er: vivimos, not vivemos.' },
    { c: 'present-reg', s: 'Los{on} domingos{Sunday|m.pl} ___ en{at} casa{home|f} de{of} mis{my} suegros{in-laws|m.pl}.', base: 'comer', hint: 'nosotros', gloss: 'to eat', a: ['comemos'], p: 'nosotros', en: 'On Sundays we eat at my in-laws’ house.', why: 'A weekly habit: presente. Nosotros with an -er verb takes -emos.' },
    { c: 'present-reg', s: '¿Ustedes{you all} ___ inglés{English|m}?', base: 'hablar', gloss: 'to speak', a: ['hablan'], p: 'ellos', en: 'Do you all speak English?', why: 'Ustedes takes the ellos form: hablan.' },
    { c: 'present-reg', s: 'Mi{my} hija{daughter|f} ___ un{a|m} libro{book|m} cada{every} semana{week|f}.', base: 'leer', gloss: 'to read', a: ['lee'], p: 'él', en: 'My daughter reads a book every week.', why: 'Leer is regular in the presente: le- plus -e gives lee.' },
    { c: 'present-reg', s: '___ español{Spanish|m} desde{since} hace{ago} dos{two} años{year|m.pl}.', base: 'estudiar', hint: 'yo', gloss: 'to study', a: ['Estudio', 'estudio'], p: 'yo', en: 'I have been studying Spanish for two years.', why: 'Something that started in the past and is still going on takes the presente in Spanish, not the perfecto: estudio.' },
    { c: 'present-reg', s: '¿A{at} qué{what} hora{time|f} ___ la{the|f} tienda{shop|f}?', base: 'abrir', gloss: 'to open', a: ['abre'], p: 'él', en: 'What time does the shop open?', why: 'A regular schedule: presente. Él with an -ir verb takes -e: abre.' },
    { c: 'present-reg', s: 'Tú{you} ___ muy{very} bien{well}; ¿dónde{where} aprendiste{did you learn}?', base: 'bailar', gloss: 'to dance', a: ['bailas'], p: 'tú', en: 'You dance really well; where did you learn?', why: 'Tú with an -ar verb takes -as: bailas.' },
    { c: 'present-reg', s: 'Mañana{tomorrow} ___ temprano{early}, así_que{so} no{not} puedo{I can} salir{go out} esta{this|f} noche{night|f}.', base: 'trabajar', hint: 'yo', gloss: 'to work', a: ['trabajo'], p: 'yo', en: 'I’m working early tomorrow, so I can’t go out tonight.', why: 'The presente also covers fixed plans for the near future: mañana trabajo.' },
    { c: 'present-reg', s: '¿Tú{you} ___ mucho{a lot of|m} café{coffee|m}?', base: 'beber', gloss: 'to drink', a: ['bebes'], p: 'tú', en: 'Do you drink a lot of coffee?', why: 'Tú with an -er verb takes -es: bebes.' },
    { c: 'present-reg', s: 'Nosotros{we} ___ la{the|f} cena{dinner|f} juntos{together|m.pl} todas{every|f.pl} las{the|f.pl} noches{night|f.pl}.', base: 'preparar', gloss: 'to make, prepare', a: ['preparamos'], p: 'nosotros', en: 'We make dinner together every night.', why: 'A daily habit: presente. Nosotros with an -ar verb takes -amos: preparamos.' },
    { c: 'present-reg', s: 'Mi{my} hermana{sister|f} ___ medicina{medicine|f} en{at} la{the|f} universidad{university|f}.', base: 'estudiar', gloss: 'to study', a: ['estudia'], p: 'él', en: 'My sister studies medicine at university.', why: 'Él and ella with an -ar verb take -a: estudia.' },
    { c: 'present-reg', s: '___ a{(personal a)} mi{my} abuela{grandmother|f} todos{every|m.pl} los{the|m.pl} domingos{Sunday|m.pl}.', base: 'llamar', hint: 'yo', gloss: 'to call', a: ['Llamo', 'llamo'], p: 'yo', en: 'I call my grandmother every Sunday.', why: 'A weekly habit: presente. Yo with an -ar verb takes -o: llamo.' },
    { c: 'present-reg', s: 'Los{the|m.pl} estudiantes{students|m.pl} ___ las{the|f.pl} respuestas{answers|f.pl} en{in} el{the|m} cuaderno{notebook|m}.', base: 'escribir', gloss: 'to write', a: ['escriben'], p: 'ellos', en: 'The students write the answers in their notebooks.', why: 'Ellos with an -ir verb takes -en, the same as -er verbs: escriben.' },
    { c: 'present-reg', s: '¿Ustedes{you all} ___ las{the|f.pl} noticias{news|f.pl} en{on} el{the|m} celular{phone|m}?', base: 'leer', gloss: 'to read', a: ['leen'], p: 'ellos', en: 'Do you all read the news on your phones?', why: 'Ustedes takes the ellos form, and leer is regular in the presente: leen.' },
    { c: 'present-reg', s: 'Nosotros{we} ___ muchas{many|f.pl} cartas{letters|f.pl} de{from} nuestros{our|m.pl} amigos{friends|m.pl} en{in} Chile{Chile}.', base: 'recibir', gloss: 'to receive, get', a: ['recibimos'], p: 'nosotros', en: 'We get a lot of letters from our friends in Chile.', why: 'Nosotros with an -ir verb takes -imos: recibimos, not recibemos.' },
    { c: 'present-reg', s: 'Tú{you} ___ mucho{a lot}, pero{but} no{not} escuchas{you listen} nada{at all}.', base: 'hablar', gloss: 'to talk', a: ['hablas'], p: 'tú', en: 'You talk a lot, but you don’t listen at all.', why: 'Tú with an -ar verb takes -as: hablas.' },
    { c: 'present-reg', s: 'Los{on} sábados{Saturday|m.pl} ___ toda{the whole|f} la{the|f} casa{house|f}.', base: 'limpiar', hint: 'yo', gloss: 'to clean', a: ['limpio'], p: 'yo', en: 'On Saturdays I clean the whole house.', why: 'A weekly habit: presente. Yo with an -ar verb takes -o: limpio.' },
    { c: 'present-reg', s: 'Mi{my} esposo{husband|m} ___ muy{very} bien{well}; sus{his} arepas{arepas|f.pl} son{are} famosas{famous|f.pl}.', base: 'cocinar', gloss: 'to cook', a: ['cocina'], p: 'él', en: 'My husband cooks really well; his arepas are famous.', why: 'A general fact about someone: presente. Él with an -ar verb takes -a: cocina.' },
    { c: 'present-reg', s: '¿Tú{you} ___ música{music|f} mientras{while} trabajas{you work}?', base: 'escuchar', gloss: 'to listen to', a: ['escuchas'], p: 'tú', en: 'Do you listen to music while you work?', why: 'Tú with an -ar verb takes -as: escuchas. Escuchar needs no word for to: escuchar música.' },
    { c: 'present-reg', s: 'Nosotros{we} ___ el{the|m} arriendo{rent|m} el{on the|m} primero{first|m} de{of} cada{every} mes{month|m}.', base: 'pagar', gloss: 'to pay', a: ['pagamos'], p: 'nosotros', en: 'We pay the rent on the first of every month.', why: 'A monthly routine: presente. Nosotros with an -ar verb takes -amos: pagamos.' },
    { c: 'present-reg', s: 'Mis{my} vecinos{neighbours|m.pl} ___ frutas{fruit|f.pl} en{at} el{the|m} mercado{market|m} los{on|m.pl} domingos{Sunday|m.pl}.', base: 'vender', gloss: 'to sell', a: ['venden'], p: 'ellos', en: 'My neighbours sell fruit at the market on Sundays.', why: 'Ellos with an -er verb takes -en: venden.' },
    { c: 'present-reg', s: 'Ella{she} ___ cinco{five} kilómetros{kilometres|m.pl} cada{every} mañana{morning|f} antes_de{before} trabajar{working}.', base: 'correr', gloss: 'to run', a: ['corre'], p: 'él', en: 'She runs five kilometres every morning before work.', why: 'A daily habit: presente. Ella with an -er verb takes -e: corre.' },
    { c: 'present-reg', s: '¿Ustedes{you all} ___ en{by} tren{train|m} o{or} en{by} avión{plane|m}?', base: 'viajar', gloss: 'to travel', a: ['viajan'], p: 'ellos', en: 'Are you all travelling by train or by plane?', why: 'Ustedes takes the ellos form: viajan.' },
    { c: 'present-reg', s: 'El{the|m} bus{bus|m} ___ cada{every} quince{fifteen} minutos{minutes|m.pl}.', base: 'pasar', gloss: 'to pass, come by', a: ['pasa'], p: 'él', en: 'The bus comes every fifteen minutes.', why: 'A regular timetable: presente. Él with an -ar verb takes -a: pasa.' },
    { c: 'present-reg', s: 'Siempre{always} ___ el{the|m} pan{bread|m} en{at} la{the|f} panadería{bakery|f} de{on} la{the|f} esquina{corner|f}.', base: 'comprar', hint: 'yo', gloss: 'to buy', a: ['compro'], p: 'yo', en: 'I always buy bread at the bakery on the corner.', why: 'Siempre signals a habit: presente. Yo with an -ar verb takes -o: compro.' },
    { c: 'present-reg', s: 'Nosotros{we} siempre{always} ___ la{the|f} cuenta{bill|f} entre{among} todos{all of us|m.pl}.', base: 'dividir', gloss: 'to split, divide', a: ['dividimos'], p: 'nosotros', en: 'We always split the bill between all of us.', why: 'Nosotros with an -ir verb takes -imos: dividimos, not dividemos.' },
    { c: 'present-reg', s: '¿Tú{you} ___ en{in} los{the|m.pl} fantasmas{ghosts|m.pl}?', base: 'creer', gloss: 'to believe', a: ['crees'], p: 'tú', en: 'Do you believe in ghosts?', why: 'Creer is regular in the presente: cre- plus -es gives crees.' },
    { c: 'present-reg', s: 'Mi{my} jefe{boss|m} nunca{never} ___ los{the|m.pl} correos{emails|m.pl} los{on|m.pl} fines_de_semana{weekends|m.pl}.', base: 'responder', gloss: 'to answer, reply to', a: ['responde'], p: 'él', en: 'My boss never answers emails at the weekend.', why: 'Nunca describes a habit: presente. Él with an -er verb takes -e: responde.' },
    { c: 'present-reg', s: 'Los{the|m.pl} niños{children|m.pl} ___ en{in} la{the|f} piscina{pool|f} todos{every|m.pl} los{the|m.pl} veranos{summer|m.pl}.', base: 'nadar', gloss: 'to swim', a: ['nadan'], p: 'ellos', en: 'The children swim in the pool every summer.', why: 'Ellos with an -ar verb takes -an: nadan.' },
    { c: 'present-reg', s: '___ ayuda{help|f} con{with} esta{this|f} maleta{suitcase|f}; pesa{it weighs} mucho{a lot}.', base: 'necesitar', hint: 'yo', gloss: 'to need', a: ['Necesito', 'necesito'], p: 'yo', en: 'I need help with this suitcase; it’s very heavy.', why: 'Something true right now: presente. Yo with an -ar verb takes -o: necesito.' },
    { c: 'present-reg', s: 'Nosotros{we} ___ a{at} la{the|f} oficina{office|f} a{at} las{the|f.pl} ocho{eight} en_punto{sharp}.', base: 'llegar', gloss: 'to arrive', a: ['llegamos'], p: 'nosotros', en: 'We get to the office at eight sharp.', why: 'A daily routine: presente. Nosotros with an -ar verb takes -amos: llegamos.' },
    { c: 'present-reg', s: '¿Ustedes{you all} ___ en{at} casa{home|f} o{or} en{at} una{a|f} cafetería{café|f}?', base: 'desayunar', gloss: 'to have breakfast', a: ['desayunan'], p: 'ellos', en: 'Do you all have breakfast at home or at a café?', why: 'Ustedes takes the ellos form: desayunan.' },
    { c: 'present-reg', s: 'Mi{my} tía{aunt|f} ___ boleros{boleros|m.pl} mientras{while} cocina{she cooks}.', base: 'cantar', gloss: 'to sing', a: ['canta'], p: 'él', en: 'My aunt sings boleros while she cooks.', why: 'Ella with an -ar verb takes -a: canta.' },
    { c: 'present-reg', s: 'Siempre{always} ___ las{the|f.pl} contraseñas{passwords|f.pl}; tengo{I have} que{to} anotarlas{write them down}.', base: 'olvidar', hint: 'yo', gloss: 'to forget', a: ['olvido'], p: 'yo', en: 'I always forget my passwords; I have to write them down.', why: 'Siempre signals a habit: presente. Yo with an -ar verb takes -o: olvido.' },
    { c: 'present-reg', s: 'Tú{you} ___ muy{very} rápido{fast}; en{in} un{a|m} mes{month|m} ya{already} hablas{you speak} bastante{quite a lot}.', base: 'aprender', gloss: 'to learn', a: ['aprendes'], p: 'tú', en: 'You learn really fast; in a month you already speak quite a lot.', why: 'Tú with an -er verb takes -es: aprendes.' },
    { c: 'present-reg', s: 'Los{the|m.pl} turistas{tourists|m.pl} ___ a{to} Monserrate{Monserrate} en{by} teleférico{cable car|m}.', base: 'subir', gloss: 'to go up', a: ['suben'], p: 'ellos', en: 'The tourists go up Monserrate by cable car.', why: 'Ellos with an -ir verb takes -en, the same as -er verbs: suben.' },
    { c: 'present-reg', s: '¿Usted{you (formal)} ___ algo{something} de{to} tomar{drink}?', base: 'desear', gloss: 'to wish, would like', a: ['desea'], p: 'él', en: 'Would you like something to drink?', why: 'Usted takes the él form: desea. Waiters often use desear to sound polite.' },

    // Cambio de raíz
    { c: 'present-stem', s: '___ un{a|m} tinto{black coffee|m}, por_favor{please}.', base: 'querer', hint: 'yo', gloss: 'to want', a: ['Quiero', 'quiero'], p: 'yo', en: 'I’d like a black coffee, please.', why: 'Querer changes e to ie in the stressed stem: quiero.' },
    { c: 'present-stem', s: '¿Me{me} ___ ayudar{help} con{with} estas{these|f.pl} cajas{boxes|f.pl}?', base: 'poder', hint: 'tú', gloss: 'can, to be able to', a: ['puedes'], p: 'tú', en: 'Can you help me with these boxes?', why: 'Poder changes o to ue: puedes.' },
    { c: 'present-stem', s: 'Nosotros{we} no{not} ___ ir{go} a{to} la{the|f} reunión{meeting|f} mañana{tomorrow}.', base: 'poder', gloss: 'can, to be able to', a: ['podemos'], p: 'nosotros', en: 'We can’t go to the meeting tomorrow.', why: 'Nosotros keeps the plain stem because the stress falls on the ending: podemos.' },
    { c: 'present-stem', s: 'En{in} este{this|m} restaurante{restaurant|m} siempre{always} ___ la{the|f} bandeja{platter|f} paisa{from Antioquia|f}.', base: 'pedir', hint: 'yo', gloss: 'to order, ask for', a: ['pido'], p: 'yo', en: 'In this restaurant I always order the bandeja paisa.', why: 'Pedir changes e to i: pido.' },
    { c: 'present-stem', s: 'Los{the|m.pl} niños{children|m.pl} ___ fútbol{football|m} en{in} el{the|m} parque{park|m} todas{every|f.pl} las{the|f.pl} tardes{afternoon|f.pl}.', base: 'jugar', gloss: 'to play', a: ['juegan'], p: 'ellos', en: 'The children play football in the park every afternoon.', why: 'Jugar is the only verb where u becomes ue: juegan.' },
    { c: 'present-stem', s: '¿Cuánto{how much} ___ estos{these|m.pl} zapatos{shoes|m.pl}?', base: 'costar', gloss: 'to cost', a: ['cuestan'], p: 'ellos', en: 'How much do these shoes cost?', why: 'Costar changes o to ue, and the subject zapatos is plural: cuestan.' },
    { c: 'present-stem', s: 'Mi{my} papá{dad|m} ___ ocho{eight} horas{hour|f.pl} todas{every|f.pl} las{the|f.pl} noches{night|f.pl}.', base: 'dormir', gloss: 'to sleep', a: ['duerme'], p: 'él', en: 'My dad sleeps eight hours every night.', why: 'Dormir changes o to ue: duerme.' },
    { c: 'present-stem', s: 'La{the|f} película{film|f} ___ a{at} las{the|f.pl} ocho{eight}.', base: 'empezar', gloss: 'to begin', a: ['empieza'], p: 'él', en: 'The film starts at eight.', why: 'Empezar changes e to ie: empieza.' },
    { c: 'present-stem', s: 'No{not} ___ lo_que{what} dices{you say}; ¿puedes{can you} repetirlo{repeat it}?', base: 'entender', hint: 'yo', gloss: 'to understand', a: ['entiendo'], p: 'yo', en: 'I don’t understand what you’re saying; can you repeat it?', why: 'Entender changes e to ie: entiendo.' },
    { c: 'present-stem', s: '¿Qué{what} ___ de{about} mi{my} idea{idea|f}?', base: 'pensar', hint: 'tú', gloss: 'to think', a: ['piensas'], p: 'tú', en: 'What do you think of my idea?', why: 'Pensar changes e to ie: piensas.' },
    { c: 'present-stem', s: 'Nosotros{we} ___ a{to} casa{home|f} a{at} las{the|f.pl} seis{six}.', base: 'volver', gloss: 'to come back', a: ['volvemos'], p: 'nosotros', en: 'We get home at six.', why: 'Nosotros keeps the plain stem: volvemos, not vuelvemos.' },
    { c: 'present-stem', s: 'En{in} esta{this|f} cafetería{café|f} ___ el{the|m} mejor{best} café{coffee|m} de{in} la{the|f} ciudad{city|f}.', base: 'servir', hint: 'ellos', gloss: 'to serve', a: ['sirven'], p: 'ellos', en: 'This café serves the best coffee in the city.', why: 'Servir changes e to i: sirven. The subject is an unnamed they.' },
    { c: 'present-stem', s: '¿A{at} qué{what} hora{time|f} ___ el{the|m} supermercado{supermarket|m}?', base: 'cerrar', gloss: 'to close', a: ['cierra'], p: 'él', en: 'What time does the supermarket close?', why: 'Cerrar changes e to ie: cierra.' },
    { c: 'present-stem', s: 'Mis{my} hijos{children|m.pl} ___ la{the|f} pizza{pizza|f} a{to} la{the|f} pasta{pasta|f}.', base: 'preferir', gloss: 'to prefer', a: ['prefieren'], p: 'ellos', en: 'My children prefer pizza to pasta.', why: 'Preferir changes e to ie: prefieren. Preferir A a B is to prefer A to B.' },
    { c: 'present-stem', s: '¡Siempre{always} ___ las{the|f.pl} llaves{keys|f.pl}!', base: 'perder', hint: 'tú', gloss: 'to lose', a: ['pierdes'], p: 'tú', en: 'You’re always losing your keys!', why: 'Perder changes e to ie: pierdes.' },
    { c: 'present-stem', s: 'Nosotros{we} ___ salir{to leave} temprano{early} para{to} evitar{avoid} el{the|m} tráfico{traffic|m}.', base: 'preferir', gloss: 'to prefer', a: ['preferimos'], p: 'nosotros', en: 'We prefer to leave early to avoid the traffic.', why: 'Nosotros keeps the plain stem because the stress falls on the ending: preferimos.' },
    { c: 'present-stem', s: 'Mi{my} abuela{grandmother|f} siempre{always} ___ los{the|m.pl} mismos{same|m.pl} cuentos{stories|m.pl}.', base: 'repetir', gloss: 'to repeat', a: ['repite'], p: 'él', en: 'My grandmother always tells the same stories over and over.', why: 'Repetir changes e to i: repite.' },
    { c: 'present-stem', s: 'Nunca{never} ___ parqueadero{parking space|m} en{in} el{the|m} centro{centre|m}.', base: 'encontrar', hint: 'yo', gloss: 'to find', a: ['encuentro'], p: 'yo', en: 'I never find a parking space in the centre.', why: 'Encontrar changes o to ue: encuentro.' },
    { c: 'present-stem', s: 'Mi{my} papá{dad|m} nos{us} ___ chistes{jokes|m.pl} malos{bad|m.pl} en{at} cada{every} comida{meal|f}.', base: 'contar', gloss: 'to tell', a: ['cuenta'], p: 'él', en: 'My dad tells us bad jokes at every meal.', why: 'Contar changes o to ue: cuenta.' },
    { c: 'present-stem', s: '¿Ustedes{you all} me{me} ___ cuando{when} hablo{I speak} rápido{fast}?', base: 'entender', gloss: 'to understand', a: ['entienden'], p: 'ellos', en: 'Do you all understand me when I speak fast?', why: 'Ustedes takes the ellos form, and entender changes e to ie: entienden.' },
    { c: 'present-stem', s: 'Normalmente{usually} ___ en{at} la{the|f} oficina{office|f} a{at} la{the|f} una{one}.', base: 'almorzar', hint: 'yo', gloss: 'to have lunch', a: ['almuerzo'], p: 'yo', en: 'I usually have lunch at the office at one.', why: 'Almorzar changes o to ue: almuerzo.' },
    { c: 'present-stem', s: '¿Tú{you} ___ el{the|m} nombre{name|m} de{of} ese{that|m} restaurante{restaurant|m}?', base: 'recordar', gloss: 'to remember', a: ['recuerdas'], p: 'tú', en: 'Do you remember the name of that restaurant?', why: 'Recordar changes o to ue: recuerdas.' },
    { c: 'present-stem', s: 'En{in} Bogotá{Bogotá} ___ casi{almost} todas{every|f.pl} las{the|f.pl} tardes{afternoon|f.pl}.', base: 'llover', gloss: 'to rain', a: ['llueve'], p: 'él', en: 'In Bogotá it rains almost every afternoon.', why: 'Llover changes o to ue and is only used in the él form: llueve.' },
    { c: 'present-stem', s: 'La{the|f} cocina{kitchen|f} ___ a{of} canela{cinnamon|f}; ¿qué{what} estás{are you} preparando{making}?', base: 'oler', gloss: 'to smell', a: ['huele'], p: 'él', en: 'The kitchen smells of cinnamon; what are you making?', why: 'Oler changes o to ue, and a word can’t start with ue in Spanish, so it adds an h: huele.' },
    { c: 'present-stem', s: 'Me{me} ___ la{the|f} cabeza{head|f} desde{since} esta{this|f} mañana{morning|f}.', base: 'doler', gloss: 'to hurt', a: ['duele'], p: 'él', en: 'My head has been hurting since this morning.', why: 'Doler works like gustar: the head is the subject, so él. It changes o to ue: me duele.' },
    { c: 'present-stem', s: 'Nosotros{we} ___ los{the|m.pl} libros{books|m.pl} a{to} la{the|f} biblioteca{library|f} el{on the|m} lunes{Monday|m}.', base: 'devolver', gloss: 'to return, give back', a: ['devolvemos'], p: 'nosotros', en: 'We’re taking the books back to the library on Monday.', why: 'Nosotros keeps the plain stem: devolvemos, not devuelvemos.' },
    { c: 'present-stem', s: 'Mis{my} papás{parents|m.pl} ___ a{to} Cartagena{Cartagena} para{for} las{the|f.pl} vacaciones{holidays|f.pl}.', base: 'volar', gloss: 'to fly', a: ['vuelan'], p: 'ellos', en: 'My parents are flying to Cartagena for the holidays.', why: 'Volar changes o to ue: vuelan.' },
    { c: 'present-stem', s: '¿Me{me} ___ en{on} el{the|m} mapa{map|m} dónde{where} queda{is} tu{your} casa{house|f}?', base: 'mostrar', hint: 'tú', gloss: 'to show', a: ['muestras'], p: 'tú', en: 'Can you show me on the map where your house is?', why: 'Mostrar changes o to ue: muestras.' },
    { c: 'present-stem', s: '___ mucho{very much} no{not} poder{being able to} ir{go} a{to} tu{your} boda{wedding|f}.', base: 'sentir', hint: 'yo', gloss: 'to be sorry, feel', a: ['Siento', 'siento'], p: 'yo', en: 'I’m very sorry I can’t go to your wedding.', why: 'Sentir changes e to ie: siento, as in lo siento.' },
    { c: 'present-stem', s: 'Mis{my} sobrinos{nephews|m.pl} ___ con{of} ser{being} futbolistas{footballers|m.pl} profesionales{professional|m.pl}.', base: 'soñar', gloss: 'to dream', a: ['sueñan'], p: 'ellos', en: 'My nephews dream of being professional footballers.', why: 'Soñar changes o to ue: sueñan. You dream con something in Spanish.' },
    { c: 'present-stem', s: 'Les{you all} ___ el{the|m} ajiaco{ajiaco|m}; es{it is} el{the|m} mejor{best} plato{dish|m} de{on} la{the|f} carta{menu|f}.', base: 'recomendar', hint: 'yo', gloss: 'to recommend', a: ['recomiendo'], p: 'yo', en: 'I recommend the ajiaco; it’s the best dish on the menu.', why: 'Recomendar changes the stressed e to ie: recomiendo.' },
    { c: 'present-stem', s: 'Nosotros{we} ___ tenis{tennis|m} los{on|m.pl} martes{Tuesday|m.pl} y{and} jueves{Thursday|m.pl}.', base: 'jugar', gloss: 'to play', a: ['jugamos'], p: 'nosotros', en: 'We play tennis on Tuesdays and Thursdays.', why: 'Jugar changes u to ue, but not in nosotros: jugamos.' },
    { c: 'present-stem', s: '¿Tú{you} ___ venir{to come} a{to} cenar{dinner} el{on|m} viernes{Friday|m}?', base: 'querer', gloss: 'to want', a: ['quieres'], p: 'tú', en: 'Do you want to come to dinner on Friday?', why: 'Querer changes e to ie: quieres.' },
    { c: 'present-stem', s: 'Los{the|m.pl} meseros{waiters|m.pl} ___ a{(to)} los{the|m.pl} clientes{customers|m.pl} con{with} una{a|f} sonrisa{smile|f}.', base: 'atender', gloss: 'to serve, attend to', a: ['atienden'], p: 'ellos', en: 'The waiters serve the customers with a smile.', why: 'Atender changes e to ie: atienden.' },
    { c: 'present-stem', s: 'Las{the|f.pl} clases{classes|f.pl} ___ el{on the|m} lunes{Monday|m} a{at} las{the|f.pl} siete{seven}.', base: 'comenzar', gloss: 'to begin', a: ['comienzan'], p: 'ellos', en: 'Classes start on Monday at seven.', why: 'Comenzar changes e to ie, and clases is plural: comienzan.' },
    { c: 'present-stem', s: 'Mi{my} hija{daughter|f} siempre{always} ___ el{the|m} vestido{dress|m} más{most} caro{expensive|m} de{in} la{the|f} tienda{shop|f}.', base: 'elegir', gloss: 'to choose', a: ['elige'], p: 'él', en: 'My daughter always chooses the most expensive dress in the shop.', why: 'Elegir changes e to i: elige.' },
    { c: 'present-stem', s: 'Nosotros{we} ___ que{that} es{it is} una{a|f} buena{good|f} idea{idea|f}.', base: 'pensar', gloss: 'to think', a: ['pensamos'], p: 'nosotros', en: 'We think it’s a good idea.', why: 'Nosotros keeps the plain stem because the stress falls on the ending: pensamos.' },
    { c: 'present-stem', s: '¿Cuánto{how much} ___ tu{your} hermano{brother|m}? Casi{almost} dos{two} metros{metres|m.pl}.', base: 'medir', gloss: 'to measure, be tall', a: ['mide'], p: 'él', en: 'How tall is your brother? Almost two metres.', why: 'Medir changes e to i: mide. Height is asked with medir: ¿cuánto mide?' },
    { c: 'present-stem', s: 'Cada{every} noche{night|f} ___ una{a|f} vela{candle|f} antes_de{before} dormir{sleeping}.', base: 'encender', hint: 'yo', gloss: 'to light, turn on', a: ['enciendo'], p: 'yo', en: 'Every night I light a candle before going to sleep.', why: 'Encender changes e to ie: enciendo.' },
    { c: 'present-stem', s: '¿Tú{you} ___ el{the|m} carro{car|m} o{or} lo{it|m} muevo{I move} yo{I}?', base: 'mover', gloss: 'to move', a: ['mueves'], p: 'tú', en: 'Will you move the car or shall I?', why: 'Mover changes o to ue: mueves.' },
    { c: 'present-stem', s: 'Usted{you (formal)} ___ derecho{straight on} dos{two} cuadras{blocks|f.pl} y{and} gira{turn} a{to} la{the|f} izquierda{left|f}.', base: 'seguir', gloss: 'to keep going, follow', a: ['sigue'], p: 'él', en: 'You go straight on for two blocks and turn left.', why: 'Seguir changes e to i: sigue. Directions are often given in the presente.' },

    // Yo irregular
    { c: 'present-yo', s: 'Los{on} sábados{Saturday|m.pl} ___ ejercicio{exercise|m} en{in} el{the|m} parque{park|m}.', base: 'hacer', hint: 'yo', gloss: 'to do, make', a: ['hago'], p: 'yo', en: 'On Saturdays I exercise in the park.', why: 'Hacer is irregular only in the yo form: hago.' },
    { c: 'present-yo', s: '___ dos{two} hermanos{brothers|m.pl} y{and} una{a|f} hermana{sister|f}.', base: 'tener', hint: 'yo', gloss: 'to have', a: ['Tengo', 'tengo'], p: 'yo', en: 'I have two brothers and a sister.', why: 'Tener adds a g in the yo form: tengo.' },
    { c: 'present-yo', s: '¿Cuántos{how many|m.pl} años{year|m.pl} ___?', base: 'tener', hint: 'tú', gloss: 'to have', a: ['tienes'], p: 'tú', en: 'How old are you?', why: 'Outside the yo form tener changes e to ie: tienes. Age uses tener in Spanish.' },
    { c: 'present-yo', s: 'Siempre{always} ___ de{from} la{the|f} oficina{office|f} a{at} las{the|f.pl} cinco{five}.', base: 'salir', hint: 'yo', gloss: 'to leave, go out', a: ['salgo'], p: 'yo', en: 'I always leave the office at five.', why: 'Salir adds a g in the yo form: salgo.' },
    { c: 'present-yo', s: 'No{not} ___ a{(to)} tu{your} novio{boyfriend|m}; ¿cómo{what} se{himself} llama{is he called}?', base: 'conocer', hint: 'yo', gloss: 'to know (a person)', a: ['conozco'], p: 'yo', en: 'I don’t know your boyfriend; what’s his name?', why: 'Verbs in -cer add z in the yo form: conozco. Conocer is for people and places.' },
    { c: 'present-yo', s: 'No{not} ___ dónde{where} están{are} mis{my} llaves{keys|f.pl}.', base: 'saber', hint: 'yo', gloss: 'to know (a fact)', a: ['sé'], p: 'yo', en: 'I don’t know where my keys are.', why: 'Saber has the short yo form sé, with an accent to tell it apart from the pronoun se.' },
    { c: 'present-yo', s: 'Yo{I} ___ la{the|f} ensalada{salad|f} y{and} tú{you} traes{bring} el{the|m} postre{dessert|m}.', base: 'traer', gloss: 'to bring', a: ['traigo'], p: 'yo', en: 'I’ll bring the salad and you bring the dessert.', why: 'Traer adds -ig- in the yo form: traigo.' },
    { c: 'present-yo', s: '¿Dónde{where} ___ las{the|f.pl} llaves{keys|f.pl}? ¿En{on} la{the|f} mesa{table|f}?', base: 'poner', hint: 'yo', gloss: 'to put', a: ['pongo'], p: 'yo', en: 'Where shall I put the keys? On the table?', why: 'Poner adds a g in the yo form: pongo.' },
    { c: 'present-yo', s: 'Mis{my} primos{cousins|m.pl} ___ a{to} visitarnos{visit us} en{at} Navidad{Christmas|f}.', base: 'venir', gloss: 'to come', a: ['vienen'], p: 'ellos', en: 'My cousins are coming to visit us at Christmas.', why: 'Outside the yo form venir changes e to ie: vienen.' },
    { c: 'present-yo', s: 'Siempre{always} te{you} ___ la{the|f} verdad{truth|f}.', base: 'decir', hint: 'yo', gloss: 'to tell, say', a: ['digo'], p: 'yo', en: 'I always tell you the truth.', why: 'Decir has the yo form digo.' },
    { c: 'present-yo', s: '¿Qué{what} ___ tú{you} en{in} la{the|f} foto{photo|f}?', base: 'ver', gloss: 'to see', a: ['ves'], p: 'tú', en: 'What do you see in the photo?', why: 'Ver is irregular only in yo (veo); tú is regular: ves.' },
    { c: 'present-yo', s: 'Yo{I} ___ al{to the|m} trabajo{work|m} porque{because} el{the|m} bus{bus|m} tarda{takes} mucho{a long time}.', base: 'conducir', gloss: 'to drive', a: ['conduzco'], p: 'yo', en: 'I drive to work because the bus takes too long.', why: 'Verbs in -cir add z in the yo form: conduzco.' },
    { c: 'present-yo', s: 'No{not} te{you} ___ bien{well}; hay{there is} mucho{a lot of|m} ruido{noise|m}.', base: 'oír', hint: 'yo', gloss: 'to hear', a: ['oigo'], p: 'yo', en: 'I can’t hear you well; there’s a lot of noise.', why: 'Oír adds -ig- in the yo form: oigo.' },
    { c: 'present-yo', s: '¿Qué{what} ___ tú{you} los{on|m.pl} fines_de_semana{weekends|m.pl}?', base: 'hacer', gloss: 'to do', a: ['haces'], p: 'tú', en: 'What do you do at the weekend?', why: 'Hacer is irregular only in the yo form (hago); tú is regular: haces.' },
    { c: 'present-yo', s: 'Siempre{always} le{her} ___ flores{flowers|f.pl} a{to} mi{my} mamá{mom|f} en{on} su{her} cumpleaños{birthday|m}.', base: 'dar', hint: 'yo', gloss: 'to give', a: ['doy'], p: 'yo', en: 'I always give my mom flowers on her birthday.', why: 'Dar has the short yo form doy.' },
    { c: 'present-yo', s: 'Esta{this|f} noche{night|f} ___ con{with} mi{my} novia{girlfriend|f} a{to} la{the|f} fiesta{party|f}.', base: 'venir', hint: 'yo', gloss: 'to come', a: ['vengo'], p: 'yo', en: 'Tonight I’m coming to the party with my girlfriend.', why: 'Venir adds a g in the yo form: vengo.' },
    { c: 'present-yo', s: 'Yo{I} ___ cansado{tired|m}, pero{but} estoy{I am} bien{fine}.', base: 'parecer', gloss: 'to seem, look', a: ['parezco'], p: 'yo', en: 'I look tired, but I’m fine.', why: 'Verbs in -cer add z in the yo form: parezco.' },
    { c: 'present-yo', s: 'En{at} mi{my} trabajo{job|m} ___ documentos{documents|m.pl} del{from the|m} inglés{English|m} al{into the|m} español{Spanish|m}.', base: 'traducir', hint: 'yo', gloss: 'to translate', a: ['traduzco'], p: 'yo', en: 'At work I translate documents from English into Spanish.', why: 'Verbs in -cir add z in the yo form: traduzco.' },
    { c: 'present-yo', s: '¿Tú{you} ___ dónde{where} queda{is} el{the|m} museo{museum|m}?', base: 'saber', gloss: 'to know (a fact)', a: ['sabes'], p: 'tú', en: 'Do you know where the museum is?', why: 'Saber is irregular only in the yo form (sé); tú is regular: sabes.' },
    { c: 'present-yo', s: 'Desde{from} mi{my} ventana{window|f} ___ las{the|f.pl} montañas{mountains|f.pl}.', base: 'ver', hint: 'yo', gloss: 'to see', a: ['veo'], p: 'yo', en: 'From my window I can see the mountains.', why: 'Ver keeps the e of the infinitive in the yo form: veo.' },
    { c: 'present-yo', s: 'Mis{my} amigos{friends|m.pl} siempre{always} me{me} ___ la{the|f} verdad{truth|f}.', base: 'decir', gloss: 'to tell, say', a: ['dicen'], p: 'ellos', en: 'My friends always tell me the truth.', why: 'Outside the yo form decir changes e to i: dicen.' },
    { c: 'present-yo', s: '¿Te{you} ___ un{a|m} tinto{black coffee|m} mientras{while} esperas{you wait}?', base: 'ofrecer', hint: 'yo', gloss: 'to offer', a: ['ofrezco'], p: 'yo', en: 'Can I offer you a coffee while you wait?', why: 'Verbs in -cer add z in the yo form: ofrezco.' },
    { c: 'present-yo', s: 'Le{you (formal)} ___ mucho{very much} su{your} ayuda{help|f}, doctora{doctor|f}.', base: 'agradecer', hint: 'yo', gloss: 'to be grateful for', a: ['agradezco'], p: 'yo', en: 'I’m very grateful for your help, doctor.', why: 'Verbs in -cer add z in the yo form: agradezco.' },
    { c: 'present-yo', s: 'Con{with} el{the|m} pelo{hair|m} corto{short|m} casi{hardly} no{not} te{you} ___.', base: 'reconocer', hint: 'yo', gloss: 'to recognise', a: ['reconozco'], p: 'yo', en: 'With short hair I hardly recognise you.', why: 'Reconocer follows conocer: reconozco.' },
    { c: 'present-yo', s: 'Cuando{when} patino{I skate}, siempre{always} ___.', base: 'caerse', hint: 'yo', gloss: 'to fall over', a: ['me caigo'], p: 'yo', en: 'When I skate, I always fall over.', why: 'Caer adds -ig- in the yo form, like traer, and caerse takes me: me caigo.' },
    { c: 'present-yo', s: 'Yo{I} no{not} ___ en{in} el{the|m} asiento{seat|m} trasero{back|m}; soy{I am} muy{very} alto{tall|m}.', base: 'caber', gloss: 'to fit', a: ['quepo'], p: 'yo', en: 'I don’t fit in the back seat; I’m very tall.', why: 'Caber has an odd yo form: quepo. The other persons are regular: cabes, cabe.' },
    { c: 'present-yo', s: 'Nunca{never} ___ la{the|f} maleta{suitcase|f} hasta{until} una{a|f} semana{week|f} después{later}.', base: 'deshacer', hint: 'yo', gloss: 'to unpack, undo', a: ['deshago'], p: 'yo', en: 'I never unpack my suitcase until a week later.', why: 'Deshacer follows hacer: deshago.' },
    { c: 'present-yo', s: '___ que{that} llegan{they arrive} tarde{late} por{because of} el{the|m} tráfico{traffic|m}.', base: 'suponer', hint: 'yo', gloss: 'to suppose', a: ['Supongo', 'supongo'], p: 'yo', en: 'I suppose they’re late because of the traffic.', why: 'Suponer follows poner and adds a g in the yo form: supongo.' },
    { c: 'present-yo', s: '¿A{at} qué{what} hora{time|f} ___ tu{your} vuelo{flight|m}?', base: 'salir', gloss: 'to leave', a: ['sale'], p: 'él', en: 'What time does your flight leave?', why: 'Salir is irregular only in the yo form (salgo); él is regular: sale.' },
    { c: 'present-yo', s: 'Mis{my} hijos{children|m.pl} ___ muy{very} rápido{fast}; la{the|f} ropa{clothes|f} ya{already} no{not} les{them} sirve{fits}.', base: 'crecer', gloss: 'to grow', a: ['crecen'], p: 'ellos', en: 'My children are growing so fast; their clothes don’t fit them any more.', why: 'Crecer is irregular only in yo (crezco); ellos is regular: crecen.' },
    { c: 'present-yo', s: '¿Qué{what} ___ tus{your} hijos{children|m.pl} después_de{after} clase{school|f}?', base: 'hacer', gloss: 'to do', a: ['hacen'], p: 'ellos', en: 'What do your children do after school?', why: 'Hacer is irregular only in the yo form (hago); ellos is regular: hacen.' },
    { c: 'present-yo', s: '¿Ustedes{you all} ___ ese{that|m} ruido{noise|m}? Viene{it comes} de{from} la{the|f} calle{street|f}.', base: 'oír', gloss: 'to hear', a: ['oyen'], p: 'ellos', en: 'Can you all hear that noise? It’s coming from the street.', why: 'Oír adds a y between vowels in the other persons: ustedes oyen.' },
    { c: 'present-yo', s: 'Nosotros{we} ___ la{the|f} mesa{table|f} y{and} ustedes{you all} lavan{wash} los{the|m.pl} platos{dishes|m.pl}.', base: 'poner', gloss: 'to put, set', a: ['ponemos'], p: 'nosotros', en: 'We’ll set the table and you all wash the dishes.', why: 'Poner is irregular only in the yo form (pongo); nosotros is regular: ponemos.' },
    { c: 'present-yo', s: 'Mi{my} jefe{boss|m} nos{us} ___ el{the|m} viernes{Friday|m} libre{off}.', base: 'dar', gloss: 'to give', a: ['da'], p: 'él', en: 'My boss gives us Friday off.', why: 'Dar is irregular only in the yo form (doy); él is da.' },
    { c: 'present-yo', s: '¿Tú{you} ___ la{the|f} torta{cake|f} o{or} la{it|f} compro{buy} yo{I}?', base: 'traer', gloss: 'to bring', a: ['traes'], p: 'tú', en: 'Will you bring the cake or shall I buy it?', why: 'Traer is irregular only in the yo form (traigo); tú is regular: traes.' },
    { c: 'present-yo', s: 'Mis{my} papás{parents|m.pl} ___ dos{two} perros{dogs|m.pl} y{and} un{a|m} gato{cat|m}.', base: 'tener', gloss: 'to have', a: ['tienen'], p: 'ellos', en: 'My parents have two dogs and a cat.', why: 'Outside the yo form tener changes e to ie: tienen.' },
    { c: 'present-yo', s: '¿Tú{you} ___ conmigo{with me} al{to the|m} concierto{concert|m} el{on|m} sábado{Saturday|m}?', base: 'venir', gloss: 'to come', a: ['vienes'], p: 'tú', en: 'Are you coming to the concert with me on Saturday?', why: 'Outside the yo form venir changes e to ie: vienes.' },
    { c: 'present-yo', s: '¿Usted{you (formal)} ___ cómo{how} llegar{to get} al{to the|m} aeropuerto{airport|m}?', base: 'saber', gloss: 'to know (a fact)', a: ['sabe'], p: 'él', en: 'Do you know how to get to the airport?', why: 'Saber is irregular only in the yo form (sé); usted takes the regular él form: sabe.' },
    { c: 'present-yo', s: 'Mi{my} esposa{wife|f} ___ el{the|m} carro{car|m} porque{because} yo{I} no{not} tengo{have} licencia{licence|f}.', base: 'conducir', gloss: 'to drive', a: ['conduce'], p: 'él', en: 'My wife drives the car because I don’t have a licence.', why: 'Conducir adds z only in the yo form (conduzco); ella is regular: conduce.' },
    { c: 'present-yo', s: '___ que{that} hagamos{we take} el{the|m} viaje{trip|m} en{in} marzo{March|m}; es{it is} más{more} barato{cheap|m}.', base: 'proponer', hint: 'yo', gloss: 'to propose, suggest', a: ['Propongo', 'propongo'], p: 'yo', en: 'I suggest we take the trip in March; it’s cheaper.', why: 'Proponer follows poner and adds a g in the yo form: propongo.' },
    { c: 'present-yo', s: 'Este{this|m} curso{course|m} ___ la{the|f} pena{trouble|f}; aprendes{you learn} muchísimo{a huge amount}.', base: 'valer', gloss: 'to be worth', a: ['vale'], p: 'él', en: 'This course is worth it; you learn a huge amount.', why: 'Valer is irregular only in the yo form (valgo); él is regular: vale. Valer la pena is to be worth it.' },
    { c: 'present-yo', s: 'Nosotros{we} ___ a{(to)} los{the|m.pl} vecinos{neighbours|m.pl} desde{since} hace{ago} años{years|m.pl}.', base: 'conocer', gloss: 'to know (a person)', a: ['conocemos'], p: 'nosotros', en: 'We have known the neighbours for years.', why: 'Conocer adds z only in the yo form (conozco); nosotros is regular: conocemos. Something still going on takes the presente.' },

    // Ser, estar, ir
    { c: 'present-irr', s: '___ de{from} Barranquilla{Barranquilla}, pero{but} vivo{I live} en{in} Bogotá{Bogotá}.', base: 'ser', hint: 'yo', gloss: 'to be', a: ['Soy', 'soy'], p: 'yo', en: 'I’m from Barranquilla, but I live in Bogotá.', why: 'Origin takes ser: soy de Barranquilla.' },
    { c: 'present-irr', s: '___ en{in} Bogotá{Bogotá} por{for} trabajo{work|m} esta{this|f} semana{week|f}.', base: 'estar', hint: 'yo', gloss: 'to be', a: ['Estoy', 'estoy'], p: 'yo', en: 'I’m in Bogotá for work this week.', why: 'Location takes estar: estoy.' },
    { c: 'present-irr', s: 'Mi{my} madre{mother|f} ___ médica{doctor|f}.', base: 'ser', gloss: 'to be', a: ['es'], p: 'él', en: 'My mother is a doctor.', why: 'A profession takes ser: es.' },
    { c: 'present-irr', s: '¿Cómo{how} ___ tú{you}? ¿Mejor{better}?', base: 'estar', gloss: 'to be', a: ['estás'], p: 'tú', en: 'How are you? Better?', why: 'Health and feelings take estar. Estás carries an accent.' },
    { c: 'present-irr', s: 'Nosotros{we} ___ hermanos{siblings|m.pl}, aunque{although} no{not} nos{each other} parecemos{we look like}.', base: 'ser', gloss: 'to be', a: ['somos'], p: 'nosotros', en: 'We’re siblings, although we don’t look alike.', why: 'Identity and relationships take ser: somos.' },
    { c: 'present-irr', s: 'Los{the|m.pl} niños{children|m.pl} ___ muy{very} cansados{tired|m.pl} después_de{after} la{the|f} excursión{trip|f}.', base: 'estar', gloss: 'to be', a: ['están'], p: 'ellos', en: 'The children are very tired after the trip.', why: 'A temporary state takes estar: están, with an accent.' },
    { c: 'present-irr', s: 'Todos{every|m.pl} los{the|m.pl} viernes{Friday|m.pl} ___ al{to the|m} cine{cinema|m} con{with} mis{my} amigas{friends|f.pl}.', base: 'ir', hint: 'yo', gloss: 'to go', a: ['voy'], p: 'yo', en: 'Every Friday I go to the cinema with my friends.', why: 'Ir is irregular: yo voy.' },
    { c: 'present-irr', s: '¿Ustedes{you all} ___ a{to} la{the|f} playa{beach|f} este{this|m} fin_de_semana{weekend|m}?', base: 'ir', gloss: 'to go', a: ['van'], p: 'ellos', en: 'Are you all going to the beach this weekend?', why: 'Ustedes takes the ellos form of ir: van.' },
    { c: 'present-irr', s: 'La{the|f} fiesta{party|f} ___ en{at} mi{my} casa{house|f} el{on the|m} sábado{Saturday|m}.', base: 'ser', gloss: 'to be', a: ['es'], p: 'él', en: 'The party is at my house on Saturday.', why: 'An event takes ser even when you say where it happens: la fiesta es en mi casa.' },
    { c: 'present-irr', s: 'El{the|m} banco{bank|m} ___ en{on} la{the|f} esquina{corner|f}.', base: 'estar', gloss: 'to be', a: ['está'], p: 'él', en: 'The bank is on the corner.', why: 'The location of a place takes estar: está.' },
    { c: 'present-irr', s: '___ las{the|f.pl} tres{three} y{and} media{half|f}.', base: 'ser', gloss: 'to be', a: ['Son', 'son'], p: 'ellos', en: 'It’s half past three.', why: 'Time takes ser, plural with any hour but one: son las tres.' },
    { c: 'present-irr', s: 'Tú{you} ___ muy{very} inteligente{clever}, pero{but} un{a bit} poco{little} perezoso{lazy|m}.', base: 'ser', gloss: 'to be', a: ['eres'], p: 'tú', en: 'You’re very clever, but a bit lazy.', why: 'Character traits take ser: tú eres.' },
    { c: 'present-irr', s: '¿De{from} dónde{where} ___ ustedes{you all}?', base: 'ser', gloss: 'to be', a: ['son'], p: 'ellos', en: 'Where are you all from?', why: 'Origin takes ser, and ustedes takes the ellos form: son.' },
    { c: 'present-irr', s: 'Hoy{today} ___ en{at} casa{home|f} todo{all|m} el{the|m} día{day|m}.', base: 'estar', hint: 'nosotros', gloss: 'to be', a: ['estamos'], p: 'nosotros', en: 'Today we’re at home all day.', why: 'Where someone is takes estar: estamos.' },
    { c: 'present-irr', s: '¿Adónde{where to} ___ tú{you} tan{so} elegante{smart}?', base: 'ir', gloss: 'to go', a: ['vas'], p: 'tú', en: 'Where are you going looking so smart?', why: 'Ir is irregular: tú vas.' },
    { c: 'present-irr', s: 'Nosotros{we} ___ al{to the|m} gimnasio{gym|m} tres{three} veces{times|f.pl} por{a} semana{week|f}.', base: 'ir', gloss: 'to go', a: ['vamos'], p: 'nosotros', en: 'We go to the gym three times a week.', why: 'Ir is irregular: nosotros vamos, with no accent.' },
    { c: 'present-irr', s: 'Mis{my} hermanos{brothers|m.pl} ___ altos{tall|m.pl} y{and} morenos{dark-haired|m.pl}.', base: 'ser', gloss: 'to be', a: ['son'], p: 'ellos', en: 'My brothers are tall and dark-haired.', why: 'What someone looks like takes ser: son.' },
    { c: 'present-irr', s: 'Esta{this|f} sopa{soup|f} ___ fría{cold|f}; ¿la{it|f} calientas{will you heat up}?', base: 'estar', gloss: 'to be', a: ['está'], p: 'él', en: 'This soup is cold; will you heat it up?', why: 'How food is right now takes estar: la sopa está fría.' },
    { c: 'present-irr', s: 'Siempre{always} ___ nervioso{nervous|m} antes_de{before} los{the|m.pl} exámenes{exams|m.pl}.', base: 'estar', hint: 'yo', gloss: 'to be', a: ['estoy'], p: 'yo', en: 'I’m always nervous before exams.', why: 'A feeling, even one that comes back every time, takes estar: estoy.' },
    { c: 'present-irr', s: 'Mi{my} hijo{son|m} ___ a{to} la{the|f} universidad{university|f} en{by} bus{bus|m}.', base: 'ir', gloss: 'to go', a: ['va'], p: 'él', en: 'My son goes to university by bus.', why: 'Ir is irregular: él va.' },
    { c: 'present-irr', s: 'Mi{my} oficina{office|f} ___ en{on} el{the|m} quinto{fifth|m} piso{floor|m}.', base: 'estar', gloss: 'to be', a: ['está'], p: 'él', en: 'My office is on the fifth floor.', why: 'Where a place is takes estar: está.' },
    { c: 'present-irr', s: '___ ingeniera{engineer|f} y{and} trabajo{I work} en{for} una{a|f} empresa{company|f} de{of} software{software|m}.', base: 'ser', hint: 'yo', gloss: 'to be', a: ['Soy', 'soy'], p: 'yo', en: 'I’m an engineer and I work for a software company.', why: 'A profession takes ser: soy. Spanish leaves out the article: soy ingeniera, not soy una ingeniera.' },
    { c: 'present-irr', s: '¿Tú{you} ___ de{from} aquí{here} o{or} de{from} otra{another|f} ciudad{city|f}?', base: 'ser', gloss: 'to be', a: ['eres'], p: 'tú', en: 'Are you from here or from another city?', why: 'Origin takes ser: tú eres.' },
    { c: 'present-irr', s: 'Nosotros{we} ___ de{on} vacaciones{holiday|f.pl} hasta{until} el{the|m} lunes{Monday|m}.', base: 'estar', gloss: 'to be', a: ['estamos'], p: 'nosotros', en: 'We’re on holiday until Monday.', why: 'Estar de vacaciones is a temporary situation: estamos, with no accent.' },
    { c: 'present-irr', s: 'Esta{this|f} camisa{shirt|f} ___ de{made of} algodón{cotton|m}.', base: 'ser', gloss: 'to be', a: ['es'], p: 'él', en: 'This shirt is made of cotton.', why: 'What something is made of takes ser: es de algodón.' },
    { c: 'present-irr', s: 'Mis{my} papás{parents|m.pl} ___ al{to the|m} mercado{market|m} los{on|m.pl} sábados{Saturday|m.pl} por{in} la{the|f} mañana{morning|f}.', base: 'ir', gloss: 'to go', a: ['van'], p: 'ellos', en: 'My parents go to the market on Saturday mornings.', why: 'Ir is irregular: ellos van.' },
    { c: 'present-irr', s: '___ alérgica{allergic|f} a{to} los{the|m.pl} mariscos{seafood|m.pl}.', base: 'ser', hint: 'yo', gloss: 'to be', a: ['Soy', 'soy'], p: 'yo', en: 'I’m allergic to seafood.', why: 'An allergy is a lasting trait, so ser: soy alérgica.' },
    { c: 'present-irr', s: '¿Tú{you} ___ al{to the|m} trabajo{work|m} en{by} bicicleta{bike|f}?', base: 'ir', gloss: 'to go', a: ['vas'], p: 'tú', en: 'Do you go to work by bike?', why: 'Ir is irregular: tú vas.' },
    { c: 'present-irr', s: '¡Ustedes{you all} ___ muy{very} amables{kind|m.pl}! Gracias{thanks} por{for} todo{everything}.', base: 'ser', gloss: 'to be', a: ['son'], p: 'ellos', en: 'You’re all very kind! Thanks for everything.', why: 'A character trait takes ser, and ustedes takes the ellos form: son.' },
    { c: 'present-irr', s: 'La{the|f} boda{wedding|f} ___ en{at} una{a|f} finca{farm|f} cerca{near} de{of} Cali{Cali}.', base: 'ser', gloss: 'to be', a: ['es'], p: 'él', en: 'The wedding is at a farm near Cali.', why: 'An event takes ser even when you say where it happens: la boda es en una finca.' },
    { c: 'present-irr', s: 'Ya{already} ___ en{on} camino{the way|m}; llego{I arrive} en{in} diez{ten} minutos{minutes|m.pl}.', base: 'estar', hint: 'yo', gloss: 'to be', a: ['estoy'], p: 'yo', en: 'I’m on my way; I’ll be there in ten minutes.', why: 'Where you are right now takes estar: estoy en camino.' },
    { c: 'present-irr', s: '___ muy{very} contentos{happy|m.pl} con{with} el{the|m} apartamento{apartment|m} nuevo{new|m}.', base: 'estar', hint: 'nosotros', gloss: 'to be', a: ['Estamos', 'estamos'], p: 'nosotros', en: 'We’re very happy with the new apartment.', why: 'A feeling takes estar: estamos contentos.' },
    { c: 'present-irr', s: 'Mi{my} hermana{sister|f} ___ embarazada{pregnant|f}; el{the|m} bebé{baby|m} nace{is due} en{in} mayo{May|m}.', base: 'estar', gloss: 'to be', a: ['está'], p: 'él', en: 'My sister is pregnant; the baby is due in May.', why: 'Pregnancy is a temporary state, so estar: está embarazada.' },
    { c: 'present-irr', s: 'Ya{already} ___ las{the|f.pl} diez{ten}; ¡vamos{we are going} a{to} llegar{arrive} tarde{late}!', base: 'ser', gloss: 'to be', a: ['son'], p: 'ellos', en: 'It’s already ten; we’re going to be late!', why: 'Time takes ser, plural with any hour but one: son las diez.' },
    { c: 'present-irr', s: '___ la{the|f} una{one} de{in} la{the|f} tarde{afternoon|f}.', base: 'ser', gloss: 'to be', a: ['Es', 'es'], p: 'él', en: 'It’s one in the afternoon.', why: 'Time takes ser, and one o’clock is singular: es la una.' },
    { c: 'present-irr', s: 'Esta{this|f} noche{night|f} ___ a{to} cocinar{cook} pasta{pasta|f}.', base: 'ir', hint: 'yo', gloss: 'to go', a: ['voy'], p: 'yo', en: 'Tonight I’m going to cook pasta.', why: 'Ir a plus an infinitive gives a plan: voy a cocinar.' },
    { c: 'present-irr', s: '¿Ustedes{you all} ___ cansados{tired|m.pl} del{from the|m} viaje{trip|m}?', base: 'estar', gloss: 'to be', a: ['están'], p: 'ellos', en: 'Are you all tired from the trip?', why: 'Tiredness is a temporary state, so estar, and ustedes takes the ellos form: están.' },
    { c: 'present-irr', s: 'Mi{my} jefe{boss|m} ___ muy{very} exigente{demanding}, pero{but} justo{fair|m}.', base: 'ser', gloss: 'to be', a: ['es'], p: 'él', en: 'My boss is very demanding, but fair.', why: 'Personality takes ser: es exigente.' },
    { c: 'present-irr', s: 'Nosotros{we} ___ a{to} ver{watch} el{the|m} partido{match|m} en{at} casa{house|f} de{of} Felipe{Felipe}.', base: 'ir', gloss: 'to go', a: ['vamos'], p: 'nosotros', en: 'We’re going to watch the match at Felipe’s place.', why: 'Ir is irregular: nosotros vamos. Ir a plus an infinitive gives a plan.' },
    { c: 'present-irr', s: 'Tú{you} ___ muy{very} callado{quiet|m} hoy{today}; ¿qué{what} te{to you} pasa{is happening}?', base: 'estar', gloss: 'to be', a: ['estás'], p: 'tú', en: 'You’re very quiet today; what’s wrong?', why: 'Hoy marks a passing mood, so estar: estás callado. Eres callado would mean you are a quiet person.' },
    { c: 'present-irr', s: 'Los{the|m.pl} niños{children|m.pl} ___ en{at} el{the|m} colegio{school|m} hasta{until} las{the|f.pl} tres{three}.', base: 'estar', gloss: 'to be', a: ['están'], p: 'ellos', en: 'The children are at school until three.', why: 'Where someone is takes estar: están.' },

    // Reflexivos
    { c: 'present-reflex', s: 'Entre_semana{on weekdays} ___ a{at} las{the|f.pl} seis{six}.', base: 'levantarse', hint: 'yo', gloss: 'to get up', a: ['me levanto'], p: 'yo', en: 'On weekdays I get up at six.', why: 'Yo takes me before the verb: me levanto.' },
    { c: 'present-reflex', s: '¿A{at} qué{what} hora{time|f} ___ tú{you}?', base: 'levantarse', gloss: 'to get up', a: ['te levantas'], p: 'tú', en: 'What time do you get up?', why: 'Tú takes te: te levantas.' },
    { c: 'present-reflex', s: 'Mi{my} hermana{sister|f} ___ por{in} la{the|f} noche{night|f}.', base: 'ducharse', gloss: 'to shower', a: ['se ducha'], p: 'él', en: 'My sister showers at night.', why: 'Él and ella take se: se ducha.' },
    { c: 'present-reflex', s: 'Los{the|m.pl} niños{children|m.pl} ___ a{at} las{the|f.pl} ocho{eight}.', base: 'acostarse', gloss: 'to go to bed', a: ['se acuestan'], p: 'ellos', en: 'The children go to bed at eight.', why: 'Ellos takes se, and acostarse changes o to ue: se acuestan.' },
    { c: 'present-reflex', s: '___ Andrés{Andrés}, ¿y{and} tú{you}?', base: 'llamarse', hint: 'yo', gloss: 'to be called', a: ['Me llamo', 'me llamo'], p: 'yo', en: 'My name is Andrés, and yours?', why: 'Llamarse is reflexive: me llamo, literally I call myself.' },
    { c: 'present-reflex', s: 'Los{on} domingos{Sunday|m.pl} ___ tarde{late}.', base: 'despertarse', hint: 'nosotros', gloss: 'to wake up', a: ['nos despertamos'], p: 'nosotros', en: 'On Sundays we wake up late.', why: 'Nosotros takes nos, and keeps the plain stem: nos despertamos.' },
    { c: 'present-reflex', s: 'Hoy{today} no{not} ___ bien{well}; creo{I think} que{that} tengo{I have} gripa{the flu|f}.', base: 'sentirse', hint: 'yo', gloss: 'to feel', a: ['me siento'], p: 'yo', en: 'I don’t feel well today; I think I have the flu.', why: 'Sentirse changes e to ie and takes me: me siento.' },
    { c: 'present-reflex', s: 'Mi{my} abuelo{grandfather|m} siempre{always} ___ elegante{smartly} para{for} ir{going} a{to} misa{mass|f}.', base: 'vestirse', gloss: 'to get dressed', a: ['se viste'], p: 'él', en: 'My grandfather always dresses smartly to go to mass.', why: 'Vestirse changes e to i and takes se: se viste.' },
    { c: 'present-reflex', s: 'Ya{already} es{it is} tarde{late}; nosotros{we} ___.', base: 'irse', gloss: 'to leave', a: ['nos vamos'], p: 'nosotros', en: 'It’s late now; we’re off.', why: 'Irse means to leave: nos vamos.' },
    { c: 'present-reflex', s: '¿Ustedes{you all} ya{already} ___ la{the|f} chaqueta{jacket|f}? Hace{it is} frío{cold|m}.', base: 'ponerse', gloss: 'to put on', a: ['se ponen'], p: 'ellos', en: 'Are you all putting your jackets on? It’s cold.', why: 'Ustedes takes se, like ellos: se ponen.' },
    { c: 'present-reflex', s: 'Antes_de{before} comer{eating} ___ las{the|f.pl} manos{hands|f.pl}.', base: 'lavarse', hint: 'yo', gloss: 'to wash', a: ['me lavo'], p: 'yo', en: 'I wash my hands before eating.', why: 'Lavarse takes me for yo. With body parts Spanish uses las manos, not mis manos.' },
    { c: 'present-reflex', s: 'Siempre{always} ___ en{in} el{the|m} cine{cinema|m}; las{the|f.pl} películas{films|f.pl} te{you} aburren{bore}.', base: 'dormirse', hint: 'tú', gloss: 'to fall asleep', a: ['te duermes'], p: 'tú', en: 'You always fall asleep at the cinema; films bore you.', why: 'Dormirse is to fall asleep. Tú takes te, and dormir changes o to ue: te duermes.' },
    { c: 'present-reflex', s: '¿Cómo{what} ___ tú{you}?', base: 'llamarse', gloss: 'to be called', a: ['te llamas'], p: 'tú', en: 'What’s your name?', why: 'Tú takes te: te llamas, literally what do you call yourself.' },
    { c: 'present-reflex', s: 'Mi{my} papá{dad|m} ___ todas{every|f.pl} las{the|f.pl} mañanas{morning|f.pl}.', base: 'afeitarse', gloss: 'to shave', a: ['se afeita'], p: 'él', en: 'My dad shaves every morning.', why: 'Él takes se: se afeita.' },
    { c: 'present-reflex', s: 'Nosotros{we} ___ mucho{a lot} en{at} las{the|f.pl} fiestas{parties|f.pl} de{of} la{the|f} oficina{office|f}.', base: 'divertirse', gloss: 'to have fun', a: ['nos divertimos'], p: 'nosotros', en: 'We have a lot of fun at the office parties.', why: 'Divertirse changes e to ie, but nosotros keeps the plain stem: nos divertimos.' },
    { c: 'present-reflex', s: 'Los{on|m.pl} lunes{Monday|m.pl} ___ a{at} las{the|f.pl} cinco{five}.', base: 'despertarse', hint: 'yo', gloss: 'to wake up', a: ['me despierto'], p: 'yo', en: 'On Mondays I wake up at five.', why: 'Despertarse changes e to ie and takes me: me despierto.' },
    { c: 'present-reflex', s: '¿Tú{you} ___ antes{before} o{or} después{after} del{of the|m} desayuno{breakfast|m}?', base: 'ducharse', gloss: 'to shower', a: ['te duchas'], p: 'tú', en: 'Do you shower before or after breakfast?', why: 'Tú takes te: te duchas.' },
    { c: 'present-reflex', s: 'Mi{my} hermana{sister|f} y{and} su{her} novio{boyfriend|m} ___ en{in} junio{June|m}.', base: 'casarse', gloss: 'to get married', a: ['se casan'], p: 'ellos', en: 'My sister and her boyfriend are getting married in June.', why: 'Two people together take the ellos form, and se: se casan. The presente also covers fixed plans.' },
    { c: 'present-reflex', s: 'Mi{my} abuela{grandmother|f} ___ de{about} todo{everything}.', base: 'quejarse', gloss: 'to complain', a: ['se queja'], p: 'él', en: 'My grandmother complains about everything.', why: 'Quejarse is always reflexive: ella se queja.' },
    { c: 'present-reflex', s: 'Nosotros{we} siempre{always} ___ en{in} la{the|f} primera{first|f} fila{row|f}.', base: 'sentarse', gloss: 'to sit down', a: ['nos sentamos'], p: 'nosotros', en: 'We always sit in the front row.', why: 'Sentarse changes e to ie, but nosotros keeps the plain stem: nos sentamos, not nos sientamos.' },
    { c: 'present-reflex', s: 'Si{if} no{not} ___ el{the|m} abrigo{coat|m}, vas{you are going} a{to} tener{be} frío{cold|m}.', base: 'ponerse', hint: 'tú', gloss: 'to put on', a: ['te pones'], p: 'tú', en: 'If you don’t put your coat on, you’re going to be cold.', why: 'Tú takes te, and poner is irregular only in the yo form: te pones.' },
    { c: 'present-reflex', s: 'Después_de{after} cada{every} comida{meal|f} ___ los{the|m.pl} dientes{teeth|m.pl}.', base: 'cepillarse', hint: 'yo', gloss: 'to brush', a: ['me cepillo'], p: 'yo', en: 'I brush my teeth after every meal.', why: 'Yo takes me: me cepillo. With body parts Spanish uses los dientes, not mis dientes.' },
    { c: 'present-reflex', s: 'Mi{my} compañera{colleague|f} ___ en{on} el{the|m} bus{bus|m} camino{on the way} al{to the|m} trabajo{work|m}.', base: 'maquillarse', gloss: 'to put on make-up', a: ['se maquilla'], p: 'él', en: 'My colleague puts her make-up on in the bus on the way to work.', why: 'Ella takes se: se maquilla.' },
    { c: 'present-reflex', s: '¿Tú{you} ___ de{(of)} mi{my} cumpleaños{birthday|m}?', base: 'acordarse', gloss: 'to remember', a: ['te acuerdas'], p: 'tú', en: 'Do you remember my birthday?', why: 'Acordarse changes o to ue and takes te for tú: te acuerdas. It is followed by de.' },
    { c: 'present-reflex', s: 'Nosotros{we} ___ a{to} un{a|m} apartamento{apartment|m} más{more} grande{big} en{in} enero{January|m}.', base: 'mudarse', gloss: 'to move (house)', a: ['nos mudamos'], p: 'nosotros', en: 'We’re moving to a bigger apartment in January.', why: 'Nosotros takes nos: nos mudamos. The presente covers fixed plans.' },
    { c: 'present-reflex', s: 'Mis{my} papás{parents|m.pl} ___ mucho{a lot} cuando{when} no{not} contesto{I answer} el{the|m} teléfono{phone|m}.', base: 'preocuparse', gloss: 'to worry', a: ['se preocupan'], p: 'ellos', en: 'My parents worry a lot when I don’t answer the phone.', why: 'Ellos takes se: se preocupan.' },
    { c: 'present-reflex', s: 'Si{if} llueve{it rains}, ___ en{at} casa{home|f} viendo{watching} películas{films|f.pl}.', base: 'quedarse', hint: 'nosotros', gloss: 'to stay', a: ['nos quedamos'], p: 'nosotros', en: 'If it rains, we stay at home watching films.', why: 'Quedarse is to stay. Nosotros takes nos: nos quedamos.' },
    { c: 'present-reflex', s: '___ muy{very} fácil{easily}; no{not} me{me} gustan{like} las{the|f.pl} películas{films|f.pl} de{of} terror{horror|m}.', base: 'asustarse', hint: 'yo', gloss: 'to get scared', a: ['Me asusto', 'me asusto'], p: 'yo', en: 'I get scared very easily; I don’t like horror films.', why: 'Asustarse is to get scared. Yo takes me: me asusto.' },
    { c: 'present-reflex', s: '¿Por_qué{why} ___ tanto{so much}? No{not} es{it is} para{for} tanto{such a big deal}.', base: 'enojarse', hint: 'tú', gloss: 'to get angry', a: ['te enojas'], p: 'tú', en: 'Why do you get so angry? It’s not that big a deal.', why: 'Enojarse is to get angry. Tú takes te: te enojas.' },
    { c: 'present-reflex', s: 'Los{the|m.pl} estudiantes{students|m.pl} ___ en{in} las{the|f.pl} clases{classes|f.pl} largas{long|f.pl}.', base: 'aburrirse', gloss: 'to get bored', a: ['se aburren'], p: 'ellos', en: 'The students get bored in long classes.', why: 'Ellos takes se, and -ir verbs take -en: se aburren.' },
    { c: 'present-reflex', s: 'Mi{my} hijo{son|m} siempre{always} ___ de{(of)} traer{bringing} la{the|f} lonchera{lunch box|f}.', base: 'olvidarse', gloss: 'to forget', a: ['se olvida'], p: 'él', en: 'My son always forgets to bring his lunch box.', why: 'Olvidarse de is to forget. Él takes se: se olvida.' },
    { c: 'present-reflex', s: 'Ustedes{you all} ___ mucho{a lot}; ¿son{are you} hermanos{siblings|m.pl}?', base: 'parecerse', gloss: 'to look alike', a: ['se parecen'], p: 'ellos', en: 'You look very alike; are you siblings?', why: 'Ustedes takes se, like ellos: se parecen. Parecer adds z only in yo, so this form is regular.' },
    { c: 'present-reflex', s: 'En{in} la{the|f} tienda{shop|f} siempre{always} ___ la{the|f} ropa{clothes|f} antes_de{before} comprarla{buying it}.', base: 'probarse', hint: 'yo', gloss: 'to try on', a: ['me pruebo'], p: 'yo', en: 'In the shop I always try clothes on before buying them.', why: 'Probarse is to try on. It changes o to ue and takes me: me pruebo.' },
    { c: 'present-reflex', s: '¿Tú{you} ___ los{the|m.pl} zapatos{shoes|m.pl} al{when} entrar{coming into} a{(to)} la{the|f} casa{house|f}?', base: 'quitarse', gloss: 'to take off', a: ['te quitas'], p: 'tú', en: 'Do you take your shoes off when you come into the house?', why: 'Quitarse is to take off clothes. Tú takes te: te quitas.' },
    { c: 'present-reflex', s: 'Nosotros{we} ___ con{at} los{the|m.pl} chistes{jokes|m.pl} de{of} mi{my} tío{uncle|m}.', base: 'reírse', gloss: 'to laugh', a: ['nos reímos'], p: 'nosotros', en: 'We laugh at my uncle’s jokes.', why: 'Reírse keeps the accent on the i: nos reímos.' },
    { c: 'present-reflex', s: 'Mi{my} abuelo{grandfather|m} ___ después_de{after} subir{climbing} las{the|f.pl} escaleras{stairs|f.pl}.', base: 'cansarse', gloss: 'to get tired', a: ['se cansa'], p: 'él', en: 'My grandfather gets tired after climbing the stairs.', why: 'Cansarse is to get tired. Él takes se: se cansa.' },
    { c: 'present-reflex', s: 'Siempre{always} ___ en{in} esta{this|f} ciudad{city|f}; las{the|f.pl} calles{streets|f.pl} son{are} un{a|m} laberinto{maze|m}.', base: 'perderse', hint: 'yo', gloss: 'to get lost', a: ['me pierdo'], p: 'yo', en: 'I always get lost in this city; the streets are a maze.', why: 'Perderse is to get lost. It changes e to ie and takes me: me pierdo.' },
    { c: 'present-reflex', s: '¿Ustedes{you all} ___ en{at} la{the|f} playa{beach|f} o{or} en{at} la{the|f} piscina{pool|f}?', base: 'bañarse', gloss: 'to swim, bathe', a: ['se bañan'], p: 'ellos', en: 'Do you all swim at the beach or at the pool?', why: 'Ustedes takes se, like ellos: se bañan.' },
    { c: 'present-reflex', s: 'Los{the|m.pl} invitados{guests|m.pl} ___ de{from} los{the|m.pl} novios{bride and groom|m.pl} a{at} medianoche{midnight|f}.', base: 'despedirse', gloss: 'to say goodbye', a: ['se despiden'], p: 'ellos', en: 'The guests say goodbye to the bride and groom at midnight.', why: 'Despedirse changes e to i and takes se for ellos: se despiden.' },
    { c: 'present-reflex', s: 'Mi{my} mamá{mom|f} ___ con{with} el{the|m} yoga{yoga|m} después_de{after} trabajar{working}.', base: 'relajarse', gloss: 'to relax', a: ['se relaja'], p: 'él', en: 'My mom relaxes with yoga after work.', why: 'Ella takes se: se relaja.' },
    { c: 'present-reflex', s: 'Nosotros{we} ___ con{with} los{the|m.pl} amigos{friends|m.pl} del{from the|m} colegio{school|m} una{one|f} vez{time|f} al{a|m} año{year|m}.', base: 'reunirse', gloss: 'to meet up', a: ['nos reunimos'], p: 'nosotros', en: 'We meet up with our school friends once a year.', why: 'Nosotros takes nos: nos reunimos. Only nosotros has no accent; the others are se reúne, se reúnen.' },
    { c: 'present-reflex', s: 'Tú{you} siempre{always} ___ antes_de{before} salir{going out}; tardas{you take} una{an|f} hora{hour|f}.', base: 'arreglarse', gloss: 'to get ready', a: ['te arreglas'], p: 'tú', en: 'You always get ready before going out; it takes you an hour.', why: 'Arreglarse is to get ready. Tú takes te: te arreglas.' },
  ],
};
