/* Colombian idioms (modismos), practised inside the Present, Past and Future topics.
   Every sentence names its idiom (dictionary form), what it means and what it says literally;
   the answer card shows them, and "Idioms only" on the quiz start screen picks just these sentences.
   Sentences use the format of data-past.js and data-future.js: c is the verb group whose tables show the answer,
   p is the person. Latin American Spanish (ustedes, no vosotros).
   Check with: node validate-idioms.js */

const IDIOM_PAST_SENTENCES = [
  // Indefinido, regular
  { c: 'past-indef-reg', p: 'nosotros', idiom: 'armar parche', means: 'to organise a get-together with friends', lit: 'to build a patch', s: 'El{the|m} sábado{Saturday|m} ___ parche{get-together|m} en{at} mi{my} casa{house|f} y{and} vino{came} todo{the whole|m} el{the|m} barrio{neighbourhood|m}.', base: 'armar', hint: 'nosotros', gloss: 'to build, set up', a: ['armamos'], en: 'On Saturday we had people over at my place and the whole neighbourhood came.', why: 'Armar parche is to get friends together. A finished Saturday takes the indefinido, and nosotros of an -ar verb is armamos, the same as the present.' },
  { c: 'past-indef-reg', p: 'ellos', idiom: 'armar parche', means: 'to organise a get-together with friends', lit: 'to build a patch', s: 'Anoche{last night} los{the|m.pl} vecinos{neighbours|m.pl} ___ un{a|m} parche{party|m} hasta{until} las{the|f.pl} tres{three}.', base: 'armar', gloss: 'to build, set up', a: ['armaron'], en: 'Last night the neighbours had a party until three.', why: 'Armar un parche is to get people together. Anoche calls for the indefinido, and ellos with an -ar verb takes -aron.' },
  { c: 'past-indef-reg', p: 'él', idiom: 'pegarse una rasca', means: 'to get really drunk', lit: 'to stick yourself a scratch', s: 'Anoche{last night} Pedro{Pedro} se{himself} ___ una{a|f} rasca{bender|f} tremenda{huge|f}.', base: 'pegarse', gloss: 'to stick, hit', a: ['pegó'], en: 'Last night Pedro got completely drunk.', why: 'Pegarse una rasca is to get really drunk. A finished event last night takes the indefinido: él pegó, with an accent.' },
  { c: 'past-indef-reg', p: 'él', idiom: 'echar los perros', means: 'to flirt with, hit on', lit: 'to set the dogs on', s: 'Felipe{Felipe} me{me} ___ los{the|m.pl} perros{dogs|m.pl} toda{all|f} la{the|f} noche{night|f} en{at} la{the|f} fiesta{party|f}.', base: 'echar', gloss: 'to throw', a: ['echó'], en: 'Felipe was hitting on me all night at the party.', why: 'Echar los perros is to flirt with someone. The party is over, so the indefinido: echó. The person you flirt with takes me, te, le.' },
  { c: 'past-indef-reg', p: 'él', idiom: 'levantar', means: 'to get a date, pull', lit: 'to lift', s: 'Diego{Diego} ___ en{at} la{the|f} rumba{party|f} del{of the|m} sábado{Saturday|m}.', base: 'levantar', gloss: 'to lift', a: ['levantó'], en: 'Diego pulled at the party on Saturday.', why: 'Levantar is to get a date or hook up. A finished event on Saturday takes the indefinido: levantó.' },
  { c: 'past-indef-reg', p: 'nosotros', idiom: 'cuadrarse', means: 'to become a couple', lit: 'to square yourselves up', s: 'Después_de{after} tres{three} meses{months|m.pl} saliendo{going out}, por_fin{finally} nos{ourselves} ___.', base: 'cuadrarse', hint: 'nosotros', gloss: 'to square up', a: ['cuadramos'], en: 'After three months of going out, we finally made it official.', why: 'Cuadrarse is to become a couple. Nos shows the subject is nosotros, and the indefinido of an -ar verb is -amos.' },
  { c: 'past-indef-reg', p: 'tú', idiom: 'cuadrarse', means: 'to become a couple', lit: 'to square yourselves up', s: '¿Ya{already} te{yourself} ___ con{with} Sebastián{Sebastián} o{or} solo{just} están{you are} saliendo{going out}?', base: 'cuadrarse', gloss: 'to square up', a: ['cuadraste'], en: 'Are you and Sebastián official yet, or just dating?', why: 'Cuadrarse is to become a couple. Tú in the indefinido of an -ar verb ends in -aste.' },
  { c: 'past-indef-reg', p: 'yo', idiom: 'voltear', means: 'to run around doing errands', lit: 'to turn around', s: 'Ayer{yesterday} ___ todo{all|m} el{the|m} día{day|m} haciendo{doing} vueltas{errands|f.pl}.', base: 'voltear', hint: 'yo', gloss: 'to turn around', a: ['volteé'], en: 'Yesterday I spent the whole day running errands.', why: 'Voltear is to run around doing errands. Yo in the indefinido of an -ar verb ends in -é: volteé.' },
  { c: 'past-indef-reg', p: 'yo', idiom: 'sudar la gota gorda', means: 'to work extremely hard', lit: 'to sweat the fat drop', s: 'El_año_pasado{last year} ___ la{the|f} gota{drop|f} gorda{fat|f} para{to} pagar{pay for} la{the|f} universidad{university|f}.', base: 'sudar', hint: 'yo', gloss: 'to sweat', a: ['sudé'], en: 'Last year I sweated blood to pay for university.', why: 'Sudar la gota gorda is to work extremely hard. El año pasado is closed, so the indefinido: yo sudé.' },
  { c: 'past-indef-reg', p: 'él', idiom: 'llevar del bulto', means: 'to get the worst of it', lit: 'to carry from the sack', s: 'En{in} la{the|f} pelea{fight|f}, el{the one|m} que{who} ___ del{from the|m} bulto{sack|m} fue{was} mi{my} primo{cousin|m}.', base: 'llevar', gloss: 'to carry', a: ['llevó'], en: 'In the fight, the one who got the worst of it was my cousin.', why: 'Llevar del bulto is to get the worst of it. A single finished event takes the indefinido: llevó.' },
  { c: 'past-indef-reg', p: 'él', idiom: 'dejar metido', means: 'to stand someone up', lit: 'to leave stuck in', s: 'Quedamos{we agreed} a{at} las{the|f.pl} ocho{eight} y{and} me{me} ___ metido{stuck} una{an|f} hora{hour|f}.', base: 'dejar', hint: 'él', gloss: 'to leave', a: ['dejó'], en: 'We agreed on eight o’clock and he left me waiting for an hour.', why: 'Dejar metido is to stand someone up. Él in the indefinido of an -ar verb ends in -ó: dejó.' },
  { c: 'past-indef-reg', p: 'yo', idiom: 'abrirse', means: 'to leave, take off', lit: 'to open yourself', s: 'La{the|f} fiesta{party|f} estaba{was} aburrida{boring|f}, así_que{so} a{at} las{the|f.pl} diez{ten} me{myself} ___.', base: 'abrirse', hint: 'yo', gloss: 'to open', a: ['abrí'], en: 'The party was boring, so I took off at ten.', why: 'Abrirse is to leave. A single finished moment takes the indefinido, and yo of an -ir verb ends in -í: me abrí.' },

  // Indefinido, irregular
  { c: 'past-indef-irr', p: 'ellos', idiom: 'hacer una vaca', means: 'to pool money for something', lit: 'to make a cow', s: 'Para{for} el{the|m} regalo{gift|m} de{of} Juan{Juan}, los{the|m.pl} compañeros{colleagues|m.pl} ___ una{a|f} vaca{kitty (lit. cow)|f}.', base: 'hacer', gloss: 'to make, do', a: ['hicieron'], en: 'The colleagues chipped in for Juan’s present.', why: 'Hacer una vaca is to pool money. Hacer has the strong stem hic-, so ellos is hicieron.' },
  { c: 'past-indef-irr', p: 'él', idiom: 'ser una chimba', means: 'to be awesome', lit: 'to be a chimba', s: 'El{the|m} concierto{concert|m} de{of} anoche{last night} ___ una{a|f} chimba{blast|f}.', base: 'ser', gloss: 'to be', a: ['fue'], en: 'Last night’s concert was awesome.', why: 'Ser una chimba is to be awesome. The concert is over, so the indefinido of ser: fue. Chimba started out vulgar, so keep it for friends.' },
  { c: 'past-indef-irr', p: 'yo', idiom: 'dar papaya', means: 'to make yourself an easy target', lit: 'to give papaya', s: 'Dejé{I left} la{the|f} bicicleta{bike|f} sin{without} candado{lock|m}; ___ papaya{papaya|f} y{and} me{from me} la{it|f} robaron{they stole}.', base: 'dar', hint: 'yo', gloss: 'to give', a: ['di'], en: 'I left my bike unlocked; I made it easy for them and they stole it.', why: 'Dar papaya is to make yourself an easy target. The indefinido of dar for yo is di, with no accent.' },
  { c: 'past-indef-irr', p: 'él', idiom: 'ponerse las pilas', means: 'to get your act together, get moving', lit: 'to put in your batteries', s: 'Al{at the} final{end|m} del{of the|m} semestre{semester|m}, Andrés{Andrés} se{himself} ___ las{the|f.pl} pilas{batteries|f.pl} y{and} pasó{passed} todo{everything}.', base: 'ponerse', gloss: 'to put on', a: ['puso'], en: 'At the end of the semester Andrés got his act together and passed everything.', why: 'Ponerse las pilas is to get moving. Poner has the strong stem pus-, so él puso.' },
  { c: 'past-indef-irr', p: 'él', idiom: 'hacerse el loco', means: 'to pretend not to notice, play dumb', lit: 'to make yourself the crazy one', s: 'Le{him} pedí{I asked for} la{the|f} plata{money|f} que{that} me{me} debe{he owes} y{and} se{himself} ___ el{the|m} loco{crazy one|m}.', base: 'hacerse', gloss: 'to make, do', a: ['hizo'], en: 'I asked him for the money he owes me and he played dumb.', why: 'Hacerse el loco is to pretend not to notice. The indefinido of hacer for él is hizo, with a z.' },
  { c: 'past-indef-irr', p: 'yo', idiom: 'hacerse el de las gafas', means: 'to pretend you didn’t see', lit: 'to make yourself the one with glasses', s: 'Vi{I saw} a{(to)} mi{my} ex{ex} en{at} la{the|f} fiesta{party|f}, pero{but} me{myself} ___ el{the one} de{with} las{the|f.pl} gafas{glasses|f.pl}.', base: 'hacerse', hint: 'yo', gloss: 'to make, do', a: ['hice'], en: 'I saw my ex at the party, but I pretended I hadn’t seen them.', why: 'Hacerse el de las gafas is to pretend you didn’t see. The indefinido of hacer for yo is hice.' },
  { c: 'past-indef-irr', p: 'ellos', idiom: 'darse garra', means: 'to give it everything', lit: 'to give yourselves claw', s: 'Los{the|m.pl} jugadores{players|m.pl} se{themselves} ___ garra{claw|f} y{and} ganaron{won} el{the|m} partido{match|m}.', base: 'darse', gloss: 'to give', a: ['dieron'], en: 'The players gave it everything and won the match.', why: 'Darse garra is to give it everything. Dar takes -er endings in the indefinido: ellos dieron.' },
  { c: 'past-indef-irr', p: 'ellos', idiom: 'ponerse la camiseta', means: 'to commit fully to a team or company', lit: 'to put on the shirt', s: 'Todos{everyone|m.pl} en{in} la{the|f} empresa{company|f} se{themselves} ___ la{the|f} camiseta{shirt|f} para{for} el{the|m} lanzamiento{launch|m}.', base: 'ponerse', gloss: 'to put on', a: ['pusieron'], en: 'Everyone at the company went all in for the launch.', why: 'Ponerse la camiseta is to commit to the team. Poner has the strong stem pus-: ellos pusieron.' },
  { c: 'past-indef-irr', p: 'yo', idiom: 'hacer el oso', means: 'to embarrass yourself', lit: 'to do the bear', s: 'Anoche{last night} ___ el{the|m} oso{bear|m}: me{myself} caí{I fell} bailando{dancing} en{at} el{the|m} matrimonio{wedding|m}.', base: 'hacer', hint: 'yo', gloss: 'to make, do', a: ['hice'], en: 'Last night I made a fool of myself: I fell over dancing at the wedding.', why: 'Hacer el oso is to embarrass yourself. The indefinido of hacer for yo is hice. ¡Qué oso! on its own means how embarrassing!' },
  { c: 'past-indef-irr', p: 'él', idiom: 'poner los cachos', means: 'to cheat on someone', lit: 'to put the horns on', s: 'Terminaron{they broke up} porque{because} él{he} le{her} ___ los{the|m.pl} cachos{horns|m.pl} con{with} su{her} mejor{best} amiga{friend|f}.', base: 'poner', gloss: 'to put', a: ['puso'], en: 'They broke up because he cheated on her with her best friend.', why: 'Poner los cachos is to cheat on someone. Poner has the strong stem pus-: él puso.' },
  { c: 'past-indef-irr', p: 'él', idiom: 'dar un pico', means: 'to give a quick kiss', lit: 'to give a beak', s: 'Al{on} despedirse{saying goodbye}, ella{she} le{him} ___ un{a|m} pico{peck|m}.', base: 'dar', gloss: 'to give', a: ['dio'], en: 'When they said goodbye, she gave him a quick kiss.', why: 'Dar un pico is to give a quick kiss. The indefinido of dar for ella is dio, with no accent.' },
  { c: 'past-indef-irr', p: 'ellos', idiom: 'dar lora', means: 'to be a nuisance, make noise', lit: 'to give parrot', s: 'Anoche{last night} los{the|m.pl} vecinos{neighbours|m.pl} ___ lora{parrot|f} con{with} la{the|f} música{music|f} hasta{until} las{the|f.pl} cuatro{four}.', base: 'dar', gloss: 'to give', a: ['dieron'], en: 'Last night the neighbours made a racket with their music until four.', why: 'Dar lora is to be a nuisance. The indefinido of dar for ellos is dieron.' },
  { c: 'past-indef-irr', p: 'yo', idiom: 'sacar la piedra', means: 'to make someone angry', lit: 'to take out the stone', s: 'Ayer{yesterday} le{her} ___ la{the|f} piedra{stone|f} a{to} mi{my} mamá{mom|f} por{for} llegar{arriving} tarde{late}.', base: 'sacar', hint: 'yo', gloss: 'to take out', a: ['saqué'], en: 'Yesterday I made my mom angry by getting home late.', why: 'Sacar la piedra is to make someone angry. In the yo form of the indefinido the c changes to qu before é: saqué.' },

  // Imperfecto
  { c: 'past-imperf', p: 'yo', idiom: 'camellar', means: 'to work (hard)', lit: 'to camel', s: 'Cuando{when} vivía{I lived} en{in} Cali{Cali}, ___ en{in} un{a|m} restaurante{restaurant|m}.', base: 'camellar', hint: 'yo', gloss: 'to work (hard)', a: ['camellaba'], en: 'When I lived in Cali, I worked in a restaurant.', why: 'Camellar is to work. An ongoing situation in the past takes the imperfecto: yo camellaba.' },
  { c: 'past-imperf', p: 'nosotros', idiom: 'estar en la olla', means: 'to be in a bad way, broke', lit: 'to be in the pot', s: 'Cuando{when} llegamos{we arrived} a{to} Bogotá{Bogotá}, ___ en{in} la{the|f} olla{pot|f}, pero{but} ahora{now} nos{for us} va{it goes} bien{well}.', base: 'estar', hint: 'nosotros', gloss: 'to be', a: ['estábamos'], en: 'When we arrived in Bogotá we were broke, but now we’re doing well.', why: 'Estar en la olla is to be in a bad way. It describes the background in the past, so the imperfecto: estábamos, with an accent.' },
  { c: 'past-imperf', p: 'él', idiom: 'mamar gallo', means: 'to tease, joke around', lit: 'to suck rooster', s: 'De_niño{as a child}, mi{my} tío{uncle|m} siempre{always} nos{us} ___ gallo{rooster|m} en{at} las{the|f.pl} reuniones{gatherings|f.pl} familiares{family|f.pl}.', base: 'mamar', gloss: 'to suck', a: ['mamaba'], en: 'When I was a kid, my uncle always teased us at family gatherings.', why: 'Mamar gallo is to tease. Siempre in the past marks a habit, so the imperfecto: mamaba.' },
  { c: 'past-imperf', p: 'ellos', idiom: 'irse de rumba', means: 'to go out partying', lit: 'to go off on a rumba', s: 'Antes{before}, mis{my} amigos{friends|m.pl} se{themselves} ___ de{on a} rumba{night out|f} todos{every|m.pl} los{the|m.pl} viernes{Fridays|m.pl}.', base: 'irse', gloss: 'to go', a: ['iban'], en: 'My friends used to go out partying every Friday.', why: 'Irse de rumba is to go out partying. Antes and todos los viernes mark a past habit, and ir is one of the three irregular imperfectos: iban.' },
  { c: 'past-imperf', p: 'él', idiom: 'echar carreta', means: 'to talk nonsense, talk big', lit: 'to throw cart', s: 'Ese{that|m} político{politician|m} siempre{always} ___ mucha{a lot of|f} carreta{cart|f}, pero{but} nunca{never} hacía{did} nada{anything}.', base: 'echar', gloss: 'to throw', a: ['echaba'], en: 'That politician always talked a lot of nonsense, but he never did anything.', why: 'Echar carreta is to talk nonsense. It describes what he used to do, so the imperfecto: echaba.' },
  { c: 'past-imperf', p: 'él', idiom: 'estar tragado', means: 'to be head over heels', lit: 'to be swallowed', s: 'En{at} el{the|m} colegio{school|m}, Mateo{Mateo} ___ tragadísimo{totally smitten} de{with} su{his} vecina{neighbour|f}.', base: 'estar', gloss: 'to be', a: ['estaba'], en: 'At school, Mateo was completely head over heels for his neighbour.', why: 'Estar tragado is to be head over heels. A lasting state in the past takes the imperfecto: estaba. Tragado agrees with the person: tragada for a woman.' },
  { c: 'past-imperf', p: 'él', idiom: 'ser un avión', means: 'to be sharp and sly', lit: 'to be a plane', s: 'De_niño{as a child}, tu{your} hermano{brother|m} ya{already} ___ un{a|m} avión{plane|m}: siempre{always} conseguía{he got} lo_que{what} quería{he wanted}.', base: 'ser', gloss: 'to be', a: ['era'], en: 'Even as a kid your brother was really sharp: he always got what he wanted.', why: 'Ser un avión is to be sharp and sly. Describing someone in the past takes the imperfecto, and ser is irregular: era.' },
  { c: 'past-imperf', p: 'él', idiom: 'ser un berraco', means: 'to be tough, brave, or brilliant at something', lit: 'to be a boar', s: 'Mi{my} abuela{grandmother|f} ___ una{a|f} berraca{tough woman|f}: crió{she raised} a{(to)} ocho{eight} hijos{children|m.pl} sola{alone|f}.', base: 'ser', gloss: 'to be', a: ['era'], en: 'My grandmother was a tough woman: she raised eight children on her own.', why: 'Ser un berraco is to be tough and brave; for a woman it is una berraca. Describing what someone was like takes the imperfecto: era.' },
  { c: 'past-imperf', p: 'yo', idiom: 'estar pilas', means: 'to be alert, on your toes', lit: 'to be batteries', s: 'Mientras{while} caminaba{I walked} por{through} el{the|m} centro{city centre|m}, ___ pilas{alert (lit. batteries)} con{with} el{the|m} bolso{bag|m}.', base: 'estar', hint: 'yo', gloss: 'to be', a: ['estaba'], en: 'While I was walking through the city centre, I kept an eye on my bag.', why: 'Estar pilas is to be alert. Mientras sets up an ongoing background, so the imperfecto: estaba.' },

  // Perfecto
  { c: 'past-perf', p: 'yo', idiom: 'hacer el oso', means: 'to embarrass yourself', lit: 'to do the bear', s: 'Últimamente{lately} ___ el{the|m} oso{bear|m} varias{several|f.pl} veces{times|f.pl} en{at} el{the|m} trabajo{work|m}.', base: 'hacer', hint: 'yo', gloss: 'to make, do', a: ['he hecho'], en: 'Lately I have embarrassed myself several times at work.', why: 'Hacer el oso is to embarrass yourself. Últimamente reaches up to now, so the perfecto, and hacer has the irregular participle hecho.' },
  { c: 'past-perf', p: 'ellos', idiom: 'poner los cachos', means: 'to cheat on someone', lit: 'to put the horns on', s: '¿Alguna_vez{ever} te{you} ___ los{the|m.pl} cachos{horns|m.pl}?', base: 'poner', hint: 'ellos', gloss: 'to put', a: ['han puesto'], en: 'Have you ever been cheated on?', why: 'Poner los cachos is to cheat on someone. Alguna vez asks about life experience: perfecto. Poner has the irregular participle puesto.' },
  { c: 'past-perf', p: 'tú', idiom: 'dar papaya', means: 'to make yourself an easy target', lit: 'to give papaya', s: '¿Alguna_vez{ever} ___ papaya{papaya|f} en{on} el{the|m} Transmilenio{Bogotá bus system|m}?', base: 'dar', hint: 'tú', gloss: 'to give', a: ['has dado'], en: 'Have you ever made yourself a target on the Transmilenio?', why: 'Dar papaya is to make yourself an easy target. Alguna vez asks about experience: perfecto, has plus the regular participle dado.' },
  { c: 'past-perf', p: 'él', idiom: 'ser un camello', means: 'to be a tough job', lit: 'to be a camel', s: 'Hasta_ahora{so far}, este{this|m} proyecto{project|m} ___ un{a|m} camello{camel|m}.', base: 'ser', gloss: 'to be', a: ['ha sido'], en: 'So far, this project has been a real slog.', why: 'Ser un camello is to be a tough job. Hasta ahora covers a period still open: perfecto, ha sido.' },
  { c: 'past-perf', p: 'yo', idiom: 'estar mamado', means: 'to be exhausted or fed up', lit: 'to be sucked dry', s: 'Últimamente{lately} ___ muy{very} mamada{worn out|f} con{with} el{the|m} trabajo{work|m}.', base: 'estar', hint: 'yo, a woman', gloss: 'to be', a: ['he estado'], en: 'Lately I have been really worn out with work.', why: 'Estar mamado is to be exhausted. Últimamente reaches up to now: he estado. It is slightly crude, fine with friends.' },

  // Indefinido or imperfecto
  { c: 'past-choice', p: 'ellos', idiom: 'estar enguayabado', means: 'to be hungover', lit: 'to be guava-ed', s: 'Cuando{when} llegué{I arrived}, mis{my} primas{cousins|f.pl} todavía{still} ___ enguayabadas{hungover|f.pl}.', base: 'estar', gloss: 'to be', a: ['estaban'], en: 'When I arrived, my cousins were still hungover.', why: 'Estar enguayabado is to be hungover. Their state is the background to my arrival, so the imperfecto: estaban.' },
  { c: 'past-choice', p: 'él', idiom: 'estar prendido', means: 'to be tipsy', lit: 'to be switched on', s: 'Cuando{when} llegamos{we arrived} a{to} la{the|f} fiesta{party|f}, Laura{Laura} ya{already} ___ prendida{tipsy|f}.', base: 'estar', gloss: 'to be', a: ['estaba'], en: 'When we got to the party, Laura was already tipsy.', why: 'Estar prendido is to be tipsy. Her state is the background when we arrived, so the imperfecto: estaba.' },
  { c: 'past-choice', p: 'él', idiom: 'sapear', means: 'to snitch on someone', lit: 'to toad', s: 'Cuando{when} el{the|m} profesor{teacher|m} preguntó{asked} quién{who} rompió{broke} la{the|f} ventana{window|f}, Andrés{Andrés} ___ a{(to)} sus{his} compañeros{classmates|m.pl}.', base: 'sapear', gloss: 'to snitch on', a: ['sapeó'], en: 'When the teacher asked who broke the window, Andrés snitched on his classmates.', why: 'Sapear is to snitch. It is a single event that moves the story on, so the indefinido: sapeó.' },
  { c: 'past-choice', p: 'yo', idiom: 'estar amañado', means: 'to feel at home somewhere', lit: 'to be settled in', s: 'Cuando{when} vivía{I lived} en{in} Medellín{Medellín}, ___ muy{very} amañada{at home|f}.', base: 'estar', hint: 'yo', gloss: 'to be', a: ['estaba'], en: 'When I lived in Medellín, I really felt at home.', why: 'Estar amañado is to feel at home. Cuando vivía describes an ongoing situation, so the imperfecto: estaba.' },
  { c: 'past-choice', p: 'él', idiom: 'estar piedro', means: 'to be angry', lit: 'to be stony', s: 'La{the|f} profesora{teacher|f} ___ piedra{angry|f} porque{because} nadie{nobody} había_hecho{had done} la{the|f} tarea{homework|f}.', base: 'estar', gloss: 'to be', a: ['estaba'], en: 'The teacher was angry because nobody had done the homework.', why: 'Estar piedro is to be angry; for a woman it is piedra. It describes her state, so the imperfecto: estaba.' },

  // Pluscuamperfecto
  { c: 'past-pluscuam', p: 'él', idiom: 'dejar metido', means: 'to stand someone up', lit: 'to leave stuck in', s: 'Laura{Laura} estaba{was} furiosa{furious|f} porque{because} Juan{Juan} ya{already} la{her} ___ metida{stuck|f} dos{two} veces{times|f.pl}.', base: 'dejar', gloss: 'to leave', a: ['había dejado'], en: 'Laura was furious because Juan had already stood her up twice.', why: 'Dejar metido is to stand someone up. That happened before she got furious, so the pluscuamperfecto: había dejado.' },
  { c: 'past-pluscuam', p: 'nosotros', idiom: 'hacer una vaca', means: 'to pool money for something', lit: 'to make a cow', s: 'Cuando{when} llegó{came} el{the|m} cumpleaños{birthday|m}, ya{already} ___ una{a|f} vaca{kitty (lit. cow)|f} para{for} el{the|m} regalo{present|m}.', base: 'hacer', hint: 'nosotros', gloss: 'to make, do', a: ['habíamos hecho'], en: 'By the time the birthday came, we had already pooled money for the present.', why: 'Hacer una vaca is to pool money. It happened before the birthday: habíamos plus the irregular participle hecho.' },
  { c: 'past-pluscuam', p: 'él', idiom: 'ponerse las pilas', means: 'to get your act together, get moving', lit: 'to put in your batteries', s: 'Cuando{when} empezaron{started} los{the|m.pl} exámenes{exams|m.pl}, Andrés{Andrés} ya{already} se{himself} ___ las{the|f.pl} pilas{batteries|f.pl}.', base: 'ponerse', gloss: 'to put on', a: ['había puesto'], en: 'When the exams started, Andrés had already got his act together.', why: 'Ponerse las pilas is to get moving. It happened before the exams: había plus the irregular participle puesto.' },
];

const IDIOM_FUTURE_SENTENCES = [
  // Ir a + infinitive
  { c: 'future-ir-a', p: 'nosotros', idiom: 'armar parche', means: 'to organise a get-together with friends', lit: 'to build a patch', s: 'El{the|m} sábado{Saturday|m} ___ parche{get-together|m} en{at} mi{my} casa{house|f}, ¿vienes{are you coming}?', base: 'armar', hint: 'nosotros', gloss: 'to build, set up', a: ['vamos a armar'], en: 'On Saturday we’re having people over at my place, are you coming?', why: 'Armar parche is to get friends together. A plan already made: vamos a plus the infinitive.' },
  { c: 'future-ir-a', p: 'ellos', idiom: 'irse de rumba', means: 'to go out partying', lit: 'to go off on a rumba', s: 'Esta{this|f} noche{night|f} mis{my} amigos{friends|m.pl} se{themselves} ___ de{on a} rumba{night out|f} al{to the|m} centro{city centre|m}.', base: 'irse', gloss: 'to go', a: ['van a ir'], en: 'Tonight my friends are going out partying in the city centre.', why: 'Irse de rumba is to go out partying. A plan for tonight: van a ir, with se in front.' },
  { c: 'future-ir-a', p: 'tú', idiom: 'hacer el oso', means: 'to embarrass yourself', lit: 'to do the bear', s: 'No{don’t} bailes{dance} salsa{salsa|f} en{at} la{the|f} boda{wedding|f}, que{because} ___ el{the|m} oso{bear|m}.', base: 'hacer', hint: 'tú', gloss: 'to make, do', a: ['vas a hacer'], en: 'Don’t dance salsa at the wedding, you’re going to embarrass yourself.', why: 'Hacer el oso is to embarrass yourself. A warning about what is about to happen: vas a hacer.' },
  { c: 'future-ir-a', p: 'tú', idiom: 'sacar la piedra', means: 'to make someone angry', lit: 'to take out the stone', s: 'Deja{stop} de{(of)} molestar{bothering}, que{because} me{me} ___ la{the|f} piedra{stone|f}.', base: 'sacar', hint: 'tú', gloss: 'to take out', a: ['vas a sacar'], en: 'Stop bothering me, you’re going to make me angry.', why: 'Sacar la piedra is to make someone angry. A warning about what is coming: vas a sacar.' },
  { c: 'future-ir-a', p: 'yo', idiom: 'dejar metido', means: 'to stand someone up', lit: 'to leave stuck in', s: 'Si{if} no{not} llegas{you arrive} a{at} las{the|f.pl} ocho{eight}, te{you} ___ metido{stuck}.', base: 'dejar', hint: 'yo', gloss: 'to leave', a: ['voy a dejar'], en: 'If you’re not here by eight, I’m leaving without you.', why: 'Dejar metido is to leave someone waiting or stand them up. A threat about the near future: voy a dejar.' },
  { c: 'future-ir-a', p: 'tú', idiom: 'levantar', means: 'to get a date, pull', lit: 'to lift', s: 'Con{with} esa{that|f} pinta{outfit|f}, seguro{surely} que{that} ___ esta{this|f} noche{night|f}.', base: 'levantar', hint: 'tú', gloss: 'to lift', a: ['vas a levantar'], en: 'Dressed like that, you’re sure to pull tonight.', why: 'Levantar is to get a date. A confident prediction for tonight: vas a levantar.' },

  // Futuro, regular
  { c: 'future-reg', p: 'él', idiom: 'ser un camello', means: 'to be a tough job', lit: 'to be a camel', s: 'Terminar{finishing} este{this|m} proyecto{project|m} a{on} tiempo{time|m} ___ un{a|m} camello{camel|m}.', base: 'ser', gloss: 'to be', a: ['será'], en: 'Finishing this project on time will be tough.', why: 'Ser un camello is to be a tough job. Ser is regular in the futuro: será.' },
  { c: 'future-reg', p: 'nosotros', idiom: 'camellar', means: 'to work (hard)', lit: 'to camel', s: 'El_próximo_año{next year} ___ duro{hard} para{to} comprar{buy} el{the|m} apartamento{apartment|m}.', base: 'camellar', hint: 'nosotros', gloss: 'to work (hard)', a: ['camellaremos'], en: 'Next year we will work hard to buy the apartment.', why: 'Camellar is to work. Nosotros adds -emos to the whole infinitive: camellaremos.' },
  { c: 'future-reg', p: 'yo', idiom: 'estar pilas', means: 'to be alert, on your toes', lit: 'to be batteries', s: 'Tranquila{don’t worry|f}, mamá{mom|f}: en{on} el{the|m} bus{bus|m} ___ pilas{alert (lit. batteries)} con{with} el{the|m} celular{phone|m}.', base: 'estar', hint: 'yo', gloss: 'to be', a: ['estaré'], en: 'Don’t worry, Mom: I’ll keep an eye on my phone on the bus.', why: 'Estar pilas is to be alert. A promise: futuro, and estar is regular: estaré.' },
  { c: 'future-reg', p: 'yo', idiom: 'dar papaya', means: 'to make yourself an easy target', lit: 'to give papaya', s: 'Te{you} prometo{I promise} que{that} no{not} ___ papaya{papaya|f} en{in} el{the|m} centro{city centre|m}.', base: 'dar', hint: 'yo', gloss: 'to give', a: ['daré'], en: 'I promise you I won’t make myself a target in the city centre.', why: 'Dar papaya is to make yourself an easy target. A promise: futuro, daré.' },
  { c: 'future-reg', p: 'yo', idiom: 'echar los perros', means: 'to flirt with, hit on', lit: 'to set the dogs on', s: 'Algún_día{some day} le{her} ___ los{the|m.pl} perros{dogs|m.pl} a{to} Camila{Camila}.', base: 'echar', hint: 'yo', gloss: 'to throw', a: ['echaré'], en: 'Some day I’ll ask Camila out.', why: 'Echar los perros is to flirt with someone. Algún día points to an open future: echaré.' },
  { c: 'future-reg', p: 'tú', idiom: 'estar enguayabado', means: 'to be hungover', lit: 'to be guava-ed', s: 'Si{if} sigues{you keep} tomando{drinking} aguardiente{aguardiente|m}, mañana{tomorrow} ___ enguayabado{hungover|m}.', base: 'estar', hint: 'tú', gloss: 'to be', a: ['estarás'], en: 'If you keep drinking aguardiente, you’ll be hungover tomorrow.', why: 'Estar enguayabado is to be hungover. A consequence in the future: estarás.' },

  // Futuro, irregular
  { c: 'future-irr', p: 'nosotros', idiom: 'hacer una vaca', means: 'to pool money for something', lit: 'to make a cow', s: 'Si{if} falta{is short} plata{money|f}, ___ una{a|f} vaca{kitty (lit. cow)|f}.', base: 'hacer', hint: 'nosotros', gloss: 'to make, do', a: ['haremos'], en: 'If we’re short of money, we’ll chip in.', why: 'Hacer una vaca is to pool money. Hacer shrinks to har- in the futuro: haremos.' },
  { c: 'future-irr', p: 'yo', idiom: 'ponerse las pilas', means: 'to get your act together, get moving', lit: 'to put in your batteries', s: 'Te{you} prometo{I promise} que{that} el{the|m} próximo{next|m} semestre{semester|m} me{myself} ___ las{the|f.pl} pilas{batteries|f.pl}.', base: 'ponerse', hint: 'yo', gloss: 'to put on', a: ['pondré'], en: 'I promise you I’ll get my act together next semester.', why: 'Ponerse las pilas is to get moving. Poner turns its e into d in the futuro: pondré.' },
  { c: 'future-irr', p: 'él', idiom: 'poner los cachos', means: 'to cheat on someone', lit: 'to put the horns on', s: 'Tranquila{don’t worry|f}, Andrés{Andrés} nunca{never} te{you} ___ los{the|m.pl} cachos{horns|m.pl}.', base: 'poner', gloss: 'to put', a: ['pondrá'], en: 'Don’t worry, Andrés will never cheat on you.', why: 'Poner los cachos is to cheat on someone. Poner has the future stem pondr-: pondrá.' },
  { c: 'future-irr', p: 'él', idiom: 'hacerse el loco', means: 'to pretend not to notice, play dumb', lit: 'to make yourself the crazy one', s: 'Cuando{when} llegue{arrives} la{the|f} cuenta{bill|f}, Marta{Marta} se{herself} ___ la{the|f} loca{crazy one|f}, como{as} siempre{always}.', base: 'hacerse', gloss: 'to make, do', a: ['hará'], en: 'When the bill comes, Marta will play dumb, as usual.', why: 'Hacerse el loco is to play dumb; for a woman it is hacerse la loca. Hacer has the future stem har-: hará.' },
  { c: 'future-irr', p: 'ellos', idiom: 'ponerse la camiseta', means: 'to commit fully to a team or company', lit: 'to put on the shirt', s: 'Si{if} los{them|m.pl} tratamos{we treat} bien{well}, los{the|m.pl} empleados{employees|m.pl} nuevos{new|m.pl} se{themselves} ___ la{the|f} camiseta{shirt|f}.', base: 'ponerse', gloss: 'to put on', a: ['pondrán'], en: 'If we treat them well, the new employees will really commit to the company.', why: 'Ponerse la camiseta is to commit to the team. Poner has the future stem pondr-: pondrán.' },

  // Futuro de probabilidad
  { c: 'future-prob', at: ['about a person', 'Spanish'], p: 'él', idiom: 'estar enguayabado', means: 'to be hungover', lit: 'to be guava-ed', s: 'Juan{Juan} no{not} contesta{answers} el{the|m} teléfono{phone|m}. ___ enguayabado{hungover|m} después_de{after} la{the|f} fiesta{party|f}.', base: 'estar', hint: 'guess', gloss: 'to be', a: ['Estará', 'estará'], en: 'Juan isn’t answering his phone. He must be hungover after the party.', why: 'Estar enguayabado is to be hungover. A guess about the present takes the futuro: estará.' },
  { c: 'future-prob', at: ['about a person', 'Spanish'], p: 'él', idiom: 'estar tragado', means: 'to be head over heels', lit: 'to be swallowed', s: 'Mateo{Mateo} no{not} para{stops} de{(of)} hablar{talking} de{about} su{his} vecina{neighbour|f}: ___ tragado{smitten|m}.', base: 'estar', hint: 'guess', gloss: 'to be', a: ['estará'], en: 'Mateo won’t stop talking about his neighbour: he must be head over heels.', why: 'Estar tragado is to be head over heels. A guess about the present takes the futuro: estará.' },
  { c: 'future-prob', at: ['about a person', 'Spanish'], p: 'él', idiom: 'estar en la olla', means: 'to be in a bad way, broke', lit: 'to be in the pot', s: 'Hace{it has been} tres{three} meses{months|m.pl} que{that} no{not} paga{he pays} el{the|m} arriendo{rent|m}; ___ en{in} la{the|f} olla{pot|f}.', base: 'estar', hint: 'guess', gloss: 'to be', a: ['estará'], en: 'He hasn’t paid the rent in three months; he must be broke.', why: 'Estar en la olla is to be broke. A guess about the present takes the futuro: estará.' },
  { c: 'future-prob', p: 'él', idiom: 'dar papaya', means: 'to make yourself an easy target', lit: 'to give papaya', s: 'Le{from him} robaron{they stole} el{the|m} celular{phone|m} a{(to)} Juan{Juan}. ___ papaya{papaya|f} en{on} el{the|m} bus{bus|m}.', base: 'dar', hint: 'guess, perf.', gloss: 'to give', a: ['Habrá dado', 'habrá dado'], en: 'Juan’s phone was stolen. He must have flashed it around on the bus.', why: 'Dar papaya is to make yourself an easy target. A guess about the recent past takes the futuro perfecto: habrá dado.' },

  // Ir a or futuro
  { c: 'future-choice', p: 'nosotros', idiom: 'sudar la gota gorda', means: 'to work extremely hard', lit: 'to sweat the fat drop', s: 'Con{with} este{this|m} calor{heat|m}, en{in} la{the|f} mudanza{move|f} ___ la{the|f} gota{drop|f} gorda{fat|f}.', base: 'sudar', hint: 'nosotros', gloss: 'to sweat', a: ['vamos a sudar', 'sudaremos'], en: 'In this heat, we’re going to sweat buckets during the move.', why: 'Sudar la gota gorda is to work extremely hard. The heat is evidence in front of you, so ir a is most natural: vamos a sudar. Sudaremos is also correct.' },
  { c: 'future-choice', p: 'yo', idiom: 'mamar gallo', means: 'to tease, joke around', lit: 'to suck rooster', s: 'Perdón{sorry}, te{you} lo{it} prometo{I promise}: no{not} te{you} ___ gallo{rooster|m} nunca{ever} más{more}.', base: 'mamar', hint: 'yo', gloss: 'to suck', a: ['mamaré', 'voy a mamar'], en: 'Sorry, I promise: I’ll never tease you again.', why: 'Mamar gallo is to tease. A promise suits the futuro simple: mamaré. Voy a mamar is also heard.' },
];

const IDIOM_PRESENT_SENTENCES = [
  // Regulares
  { c: 'present-reg', p: 'él', idiom: 'camellar', means: 'to work (hard)', lit: 'to camel', s: 'Mi{my} papá{dad|m} ___ de{from} lunes{Monday|m} a{to} sábado{Saturday|m} en{in} una{a|f} fábrica{factory|f}.', base: 'camellar', gloss: 'to work (hard)', a: ['camella'], en: 'My dad works Monday to Saturday in a factory.', why: 'Camellar is to work. It is a routine, so the presente, and él of an -ar verb ends in -a.' },
  { c: 'present-reg', p: 'él', idiom: 'echar carreta', means: 'to talk nonsense, talk big', lit: 'to throw cart', s: 'Ese{that|m} político{politician|m} ___ mucha{a lot of|f} carreta{cart|f}, pero{but} no{not} hace{does} nada{anything}.', base: 'echar', gloss: 'to throw', a: ['echa'], en: 'That politician talks a lot of nonsense, but he doesn’t do anything.', why: 'Echar carreta is to talk nonsense. It describes what he usually does, so the presente: echa.' },
  { c: 'present-reg', p: 'él', idiom: 'mamar gallo', means: 'to tease, joke around', lit: 'to suck rooster', s: 'Mi{my} tío{uncle|m} siempre{always} nos{us} ___ gallo{rooster|m} en{at} las{the|f.pl} reuniones{gatherings|f.pl} familiares{family|f.pl}.', base: 'mamar', gloss: 'to suck', a: ['mama'], en: 'My uncle always teases us at family gatherings.', why: 'Mamar gallo is to tease. A habit takes the presente, and él of an -ar verb ends in -a. It is informal but not rude.' },
  { c: 'present-reg', p: 'él', idiom: 'sacar la piedra', means: 'to make someone angry', lit: 'to take out the stone', s: 'Me{me} ___ la{the|f} piedra{stone|f} que{that} la{the|f} gente{people|f} se{itself} cuele{cuts in} en{in} la{the|f} fila{line|f}.', base: 'sacar', gloss: 'to take out', a: ['saca'], en: 'It makes me angry when people cut in line.', why: 'Sacar la piedra works like gustar: the thing that annoys is the subject. The que clause counts as singular: saca.' },
  { c: 'present-reg', p: 'tú', idiom: 'sapear', means: 'to snitch on someone', lit: 'to toad', s: 'Si{if} ___ a{(to)} tus{your} compañeros{classmates|m.pl}, nadie{nobody} va{is going} a{to} confiar{trust} en{in} ti{you}.', base: 'sapear', hint: 'tú', gloss: 'to snitch on', a: ['sapeas'], en: 'If you snitch on your classmates, nobody will trust you.', why: 'Sapear is to snitch. After si the presente is used, and tú of an -ar verb ends in -as.' },
  { c: 'present-reg', p: 'tú', idiom: 'echar los perros', means: 'to flirt with, hit on', lit: 'to set the dogs on', s: '¿Por_qué{why} no{not} le{her} ___ los{the|m.pl} perros{dogs|m.pl} a{to} Camila{Camila}? Se{it} nota{shows} que{that} te{you} gusta{you like her}.', base: 'echar', hint: 'tú', gloss: 'to throw', a: ['echas'], en: 'Why don’t you ask Camila out? It’s obvious you like her.', why: 'Echar los perros is to flirt with someone. A suggestion with por qué no uses the presente: tú echas.' },
  { c: 'present-reg', p: 'nosotros', idiom: 'hacer una vaca', means: 'to pool money for something', lit: 'to make a cow', s: 'Si{if} ___ una{a|f} vaca{kitty (lit. cow)|f}, nos{us} alcanza{is enough} para{for} el{the|m} asado{barbecue|m}.', base: 'hacer', hint: 'nosotros', gloss: 'to make, do', a: ['hacemos'], en: 'If we pool our money, we’ll have enough for the barbecue.', why: 'Hacer una vaca is to pool money. After si the presente is used. Hacer is irregular only in yo (hago), so nosotros is regular: hacemos.' },
  { c: 'present-reg', p: 'él', idiom: 'levantar', means: 'to get a date, pull', lit: 'to lift', s: 'Diego{Diego} ___ en{at} todas{every|f.pl} las{the|f.pl} rumbas{parties|f.pl}; no{not} sé{I know} cómo{how} lo{it} hace{he does}.', base: 'levantar', gloss: 'to lift', a: ['levanta'], en: 'Diego pulls at every party; I don’t know how he does it.', why: 'Levantar is to get a date. What he always does takes the presente, and él of an -ar verb ends in -a: levanta.' },

  // Yo irregular
  { c: 'present-yo', p: 'yo', idiom: 'dar papaya', means: 'to make yourself an easy target', lit: 'to give papaya', s: 'En{on} el{the|m} bus{bus|m} nunca{never} ___ papaya{papaya|f}: siempre{always} guardo{I put away} el{the|m} celular{phone|m}.', base: 'dar', hint: 'yo', gloss: 'to give', a: ['doy'], en: 'On the bus I never make myself a target: I always put my phone away.', why: 'Dar papaya is to make yourself an easy target. Dar has the short yo form doy.' },
  { c: 'present-yo', p: 'yo', idiom: 'ponerse las pilas', means: 'to get your act together, get moving', lit: 'to put in your batteries', s: 'Si{if} no{not} me{myself} ___ las{the|f.pl} pilas{batteries|f.pl}, voy{I am going} a{to} perder{fail} el{the|m} semestre{semester|m}.', base: 'ponerse', hint: 'yo', gloss: 'to put on', a: ['pongo'], en: 'If I don’t get my act together, I’m going to fail the semester.', why: 'Ponerse las pilas is to get moving. After si the presente is used, and poner adds a g in the yo form: me pongo.' },

  // Ser, estar, ir
  { c: 'present-irr', p: 'él', idiom: 'ser un avión', means: 'to be sharp and sly', lit: 'to be a plane', s: 'Tu{your} hermano{brother|m} ___ un{a|m} avión{plane|m}: siempre{always} consigue{gets} lo_que{what} quiere{he wants}.', base: 'ser', gloss: 'to be', a: ['es'], en: 'Your brother is really sharp: he always gets what he wants.', why: 'Ser un avión is to be sharp and sly. It describes who he is, so ser: es.' },
  { c: 'present-irr', p: 'tú', idiom: 'ser un berraco', means: 'to be tough, brave, or brilliant at something', lit: 'to be a boar', s: 'Tú{you} ___ un{a|m} berraco{star|m} para{at} las{the|f.pl} matemáticas{maths|f.pl}.', base: 'ser', gloss: 'to be', a: ['eres'], en: 'You’re brilliant at maths.', why: 'Ser un berraco para is to be great at something. A trait takes ser, and tú of ser is eres. Estar berraco is different: it means to be furious.' },
  { c: 'present-irr', p: 'yo', idiom: 'estar enguayabado', means: 'to be hungover', lit: 'to be guava-ed', s: 'Hoy{today} no{not} puedo{I can} trabajar{work}: ___ enguayabado{hungover|m} después_de{after} la{the|f} fiesta{party|f}.', base: 'estar', hint: 'yo', gloss: 'to be', a: ['estoy'], en: 'I can’t work today: I’m hungover after the party.', why: 'Estar enguayabado is to be hungover. It is a temporary state, so estar: estoy.' },
  { c: 'present-irr', p: 'ellos', idiom: 'estar amañado', means: 'to feel at home somewhere', lit: 'to be settled in', s: '¿Ustedes{you all} ___ amañados{settled in|m.pl} en{in} Bogotá{Bogotá} o{or} extrañan{do you miss} la{the|f} costa{coast|f}?', base: 'estar', gloss: 'to be', a: ['están'], en: 'Do you all feel at home in Bogotá, or do you miss the coast?', why: 'Estar amañado is to feel at home. A feeling takes estar, and ustedes takes the ellos form: están.' },
  { c: 'present-irr', p: 'yo', idiom: 'estar en la olla', means: 'to be in a bad way, broke', lit: 'to be in the pot', s: 'Desde{since} que{that} perdí{I lost} el{the|m} trabajo{job|m}, ___ en{in} la{the|f} olla{pot|f}.', base: 'estar', hint: 'yo', gloss: 'to be', a: ['estoy'], en: 'Since I lost my job, I’ve been broke.', why: 'Estar en la olla is to be in a bad way. The situation is still going on, so the presente: estoy.' },
  { c: 'present-irr', p: 'él', idiom: 'ser una chimba', means: 'to be awesome', lit: 'to be a chimba', s: 'Este{this|m} parche{group of friends|m} ___ una{a|f} chimba{blast|f}.', base: 'ser', gloss: 'to be', a: ['es'], en: 'This group of friends is awesome.', why: 'Ser una chimba is to be awesome. It describes what something is like, so ser: es. Chimba started out vulgar, so keep it for friends.' },

  // Reflexivos
  { c: 'present-reflex', p: 'yo', idiom: 'abrirse', means: 'to leave, take off', lit: 'to open yourself', s: 'Ya{already} es{it is} tarde{late}, parceros{mates|m.pl}; yo{I} me{myself} ___.', base: 'abrirse', gloss: 'to open', a: ['abro'], en: 'It’s late, guys; I’m off.', why: 'Abrirse is to leave. Yo takes me, and yo of an -ir verb ends in -o: me abro.' },
  { c: 'present-reflex', p: 'ellos', idiom: 'irse de rumba', means: 'to go out partying', lit: 'to go off on a rumba', s: 'Los{on} viernes{Friday|m.pl} mis{my} amigos{friends|m.pl} siempre{always} se{themselves} ___ de{on a} rumba{night out|f}.', base: 'irse', gloss: 'to go', a: ['van'], en: 'On Fridays my friends always go out partying.', why: 'Irse de rumba is to go out partying. Siempre signals a habit, so the presente: ellos se van.' },
];
