/* Past tenses (tiempos del pasado): reference tables and quiz sentences.
   Latin American Spanish: the plural “you” is ustedes, which takes the ellos form.
   In tables, [square brackets] mark the part of the form to highlight.
   In sentences, word{gloss} gives the hover translation and ___ is the gap. */

const PAST_TENSE = {
  id: 'past', pl: 'Pasado', en: 'Past tenses',
  intro: 'Spanish has several past tenses. The indefinido tells what happened, the imperfecto paints the background and habits, and the perfecto covers experience and things still open. The ending tells you the person, so the pronoun is usually left out. In Latin America “you” in the plural is ustedes, which takes the ellos form.',

  groups: [
    {
      id: 'past-indef-reg', pl: 'Indefinido', short: 'Indef.', en: 'Preterite, regular', q: 'hablar → hablé, comer → comí',
      summary: 'The pretérito indefinido reports a finished action at a definite time: ayer, la semana pasada, en 2010, and in Latin America also hoy and esta mañana. Regular -ar verbs take -é, -aste, -ó, -amos, -aron; -er and -ir verbs share one set: -í, -iste, -ió, -imos, -ieron.',
      tables: [
        { title: 'hablar, comer, vivir: the two sets of endings',
          cols: [{ label: '-ar', tint: 'all' }, { label: '-er', tint: 'all' }, { label: '-ir', tint: 'all' }],
          rows: [
            { who: 'yo', cells: ['habl[é]', 'com[í]', 'viv[í]'] },
            { who: 'tú', cells: ['habl[aste]', 'com[iste]', 'viv[iste]'] },
            { who: 'él / ella / usted', cells: ['habl[ó]', 'com[ió]', 'viv[ió]'] },
            { who: 'nosotros', cells: ['habl[amos]', 'com[imos]', 'viv[imos]'] },
            { who: 'ellos / ellas / ustedes', cells: ['habl[aron]', 'com[ieron]', 'viv[ieron]'] },
          ] },
        { title: 'Other regular verbs',
          cols: [{ label: 'yo', tint: 'all' }, { label: 'él', tint: 'all' }, { label: 'ellos', tint: 'all' }],
          rows: [
            { who: 'trabajar, to work', cells: ['trabaj[é]', 'trabaj[ó]', 'trabaj[aron]'] },
            { who: 'comprar, to buy', cells: ['compr[é]', 'compr[ó]', 'compr[aron]'] },
            { who: 'beber, to drink', cells: ['beb[í]', 'beb[ió]', 'beb[ieron]'] },
            { who: 'volver, to come back', cells: ['volv[í]', 'volv[ió]', 'volv[ieron]'] },
            { who: 'salir, to go out', cells: ['sal[í]', 'sal[ió]', 'sal[ieron]'] },
            { who: 'escribir, to write', cells: ['escrib[í]', 'escrib[ió]', 'escrib[ieron]'] },
            { who: 'levantarse, to get up', cells: ['me levant[é]', 'se levant[ó]', 'se levant[aron]'] },
          ] },
        { title: 'Signal words that call for the indefinido',
          cols: [{ label: 'Example', tint: 'all' }, { label: 'English', tint: 'all' }],
          rows: [
            { who: 'ayer', cells: ['Ayer comí tacos.', 'Yesterday I ate tacos.'] },
            { who: 'anoche', cells: ['Anoche salimos tarde.', 'Last night we went out late.'] },
            { who: 'hoy, esta mañana', cells: ['Hoy trabajé mucho.', 'Today I worked a lot.'] },
            { who: 'la semana pasada', cells: ['La semana pasada trabajé mucho.', 'Last week I worked a lot.'] },
            { who: 'el año pasado', cells: ['El año pasado viajaron a Cuba.', 'Last year they travelled to Cuba.'] },
            { who: 'en 2010', cells: ['En 2010 compramos la casa.', 'In 2010 we bought the house.'] },
            { who: 'hace dos días', cells: ['Hace dos días llegó Ana.', 'Ana arrived two days ago.'] },
            { who: 'de repente', cells: ['De repente sonó el teléfono.', 'Suddenly the phone rang.'] },
          ] },
      ],
      rules: [
        { t: 'A finished action at a definite point in the past', ex: 'Ayer hablé con mi madre.', en: 'Yesterday I spoke with my mother.' },
        { t: 'The yo and él forms of -ar verbs carry a written accent: hablé, habló', ex: 'Mi padre trabajó diez horas.', en: 'My father worked ten hours.' },
        { t: '-er and -ir verbs share the same endings', ex: 'Comimos y salimos.', en: 'We ate and we left.' },
        { t: 'A series of events in order goes in the indefinido', ex: 'Me levanté, desayuné y salí.', en: 'I got up, had breakfast and left.' },
        { t: 'A closed period, however long, is one finished event', ex: 'Vivió en Lima diez años.', en: 'She lived in Lima for ten years.' },
        { t: 'In Latin America a finished event from today also takes the indefinido', ex: 'Hoy desayuné muy temprano.', en: 'Today I had breakfast very early.' },
      ],
      watch: [
        'The accent is the difference between habló (he spoke) and hablo (I speak). Do not drop it.',
        '-er and -ir endings are -í, -iste, -ió, never -é or -ó: comió, not “comó”.',
        'Nosotros forms of -ar and -ir verbs look exactly like the present: hablamos, vivimos. The time expression tells you which tense it is. Only -er verbs differ: comemos, comimos.',
        'Ustedes takes the ellos form, -aron and -ieron: ¿Ustedes hablaron con el jefe? ¿Ustedes salieron anoche?',
      ],
    },
    {
      id: 'past-indef-irr', pl: 'Irregulares', short: 'Irreg.', en: 'Preterite, irregular', q: 'ir → fui, tener → tuve',
      summary: 'A dozen very common verbs build the indefinido on a new stem with unstressed endings and no accents: tuve, hice, pude. Ser and ir share one set of forms, and a few spelling and vowel changes touch only some persons.',
      tables: [
        { title: 'ser and ir, dar, ver',
          cols: [{ label: 'ser and ir', tint: 'all' }, { label: 'dar', tint: 'all' }, { label: 'ver', tint: 'all' }],
          rows: [
            { who: 'yo', cells: ['fu[i]', 'd[i]', 'v[i]'] },
            { who: 'tú', cells: ['fu[iste]', 'd[iste]', 'v[iste]'] },
            { who: 'él / ella / usted', cells: ['fu[e]', 'd[io]', 'v[io]'] },
            { who: 'nosotros', cells: ['fu[imos]', 'd[imos]', 'v[imos]'] },
            { who: 'ellos / ellas / ustedes', cells: ['fu[eron]', 'd[ieron]', 'v[ieron]'] },
          ] },
        { title: 'Strong preterites: new stem, endings -e, -iste, -o, -imos, -ieron',
          cols: [{ label: 'tener', tint: 'all' }, { label: 'hacer', tint: 'all' }, { label: 'decir', tint: 'all' }],
          rows: [
            { who: 'yo', cells: ['[tuv]e', '[hic]e', '[dij]e'] },
            { who: 'tú', cells: ['[tuv]iste', '[hic]iste', '[dij]iste'] },
            { who: 'él / ella / usted', cells: ['[tuv]o', '[hiz]o', '[dij]o'] },
            { who: 'nosotros', cells: ['[tuv]imos', '[hic]imos', '[dij]imos'] },
            { who: 'ellos / ellas / ustedes', cells: ['[tuv]ieron', '[hic]ieron', '[dij]eron'] },
          ] },
        { title: 'The other strong stems',
          cols: [{ label: 'yo', tint: 'all' }, { label: 'él', tint: 'all' }, { label: 'ellos', tint: 'all' }],
          rows: [
            { who: 'estar, to be', cells: ['[estuv]e', '[estuv]o', '[estuv]ieron'] },
            { who: 'poder, can', cells: ['[pud]e', '[pud]o', '[pud]ieron'] },
            { who: 'poner, to put', cells: ['[pus]e', '[pus]o', '[pus]ieron'] },
            { who: 'saber, to know', cells: ['[sup]e', '[sup]o', '[sup]ieron'] },
            { who: 'querer, to want', cells: ['[quis]e', '[quis]o', '[quis]ieron'] },
            { who: 'venir, to come', cells: ['[vin]e', '[vin]o', '[vin]ieron'] },
            { who: 'traer, to bring', cells: ['[traj]e', '[traj]o', '[traj]eron'] },
            { who: 'andar, to walk', cells: ['[anduv]e', '[anduv]o', '[anduv]ieron'] },
            { who: 'haber (hay)', cells: ['—', '[hub]o', '—'] },
          ] },
        { title: 'Spelling change in the yo form only: -car, -gar, -zar',
          cols: [{ label: 'yo', tint: 'all' }, { label: 'tú', tint: 'all' }, { label: 'él', tint: 'all' }],
          rows: [
            { who: 'buscar, to look for', cells: ['bus[qué]', 'buscaste', 'buscó'] },
            { who: 'sacar, to take out', cells: ['sa[qué]', 'sacaste', 'sacó'] },
            { who: 'llegar, to arrive', cells: ['lle[gué]', 'llegaste', 'llegó'] },
            { who: 'jugar, to play', cells: ['ju[gué]', 'jugaste', 'jugó'] },
            { who: 'empezar, to begin', cells: ['empe[cé]', 'empezaste', 'empezó'] },
          ] },
        { title: 'Vowel change in the él and ellos forms only',
          cols: [{ label: 'yo', tint: 'all' }, { label: 'él', tint: 'all' }, { label: 'ellos', tint: 'all' }],
          rows: [
            { who: 'pedir, to ask for', cells: ['pedí', 'p[i]dió', 'p[i]dieron'] },
            { who: 'preferir, to prefer', cells: ['preferí', 'pref[i]rió', 'pref[i]rieron'] },
            { who: 'dormir, to sleep', cells: ['dormí', 'd[u]rmió', 'd[u]rmieron'] },
            { who: 'morir, to die', cells: ['morí', 'm[u]rió', 'm[u]rieron'] },
            { who: 'leer, to read', cells: ['leí', 'le[y]ó', 'le[y]eron'] },
            { who: 'oír, to hear', cells: ['oí', 'o[y]ó', 'o[y]eron'] },
          ] },
      ],
      rules: [
        { t: 'Ser and ir have the same forms; the context tells them apart', ex: 'Fui al cine. La película fue buena.', en: 'I went to the cinema. The film was good.' },
        { t: 'Strong preterites use a new stem and endings without any accent', ex: 'Tuve que trabajar el domingo.', en: 'I had to work on Sunday.' },
        { t: 'Hacer spells its él form with z to keep the sound: hizo', ex: 'Ana hizo la cena.', en: 'Ana made dinner.' },
        { t: 'Stems ending in j drop the i in the ellos form: dijeron, trajeron', ex: 'Mis padres me dijeron la verdad.', en: 'My parents told me the truth.' },
        { t: 'Verbs in -car, -gar and -zar change spelling in the yo form only', ex: 'Busqué las llaves y llegué tarde.', en: 'I looked for the keys and arrived late.' },
        { t: '-ir verbs with a stem change in the present change e to i or o to u in the él and ellos forms', ex: 'Pidió agua y durmió toda la tarde.', en: 'He asked for water and slept all afternoon.' },
      ],
      watch: [
        'No accents on the strong preterites: tuve, tuvo, hizo, pudo. Writing “tuvó” is a classic slip.',
        'Fue is both “he was” and “he went”. Fui and fue never take an accent, and neither do vi, vio, di, dio.',
        'Hay in the past is hubo (there was, there were), one form for singular and plural.',
        'Andar and estar are strong too: anduve, estuve, never “andé” or “esté”.',
        'Some verbs shift meaning in the indefinido: tuvo (got, received), pudo (managed to), supo (found out), quiso (tried to), no quiso (refused), conoció (met).',
        'Ustedes uses the ellos form: ustedes fueron, ustedes hicieron, ustedes dijeron.',
      ],
    },
    {
      id: 'past-imperf', pl: 'Imperfecto', short: 'Imperf.', en: 'Imperfect', q: 'hablar → hablaba, ser → era',
      summary: 'The imperfecto describes how things were: habits, background, age, time, weather and actions in progress with no end in view. -ar verbs take -aba, -er and -ir verbs take -ía. Only ser, ir and ver are irregular.',
      tables: [
        { title: 'hablar, comer, vivir',
          cols: [{ label: '-ar', tint: 'all' }, { label: '-er', tint: 'all' }, { label: '-ir', tint: 'all' }],
          rows: [
            { who: 'yo', cells: ['habl[aba]', 'com[ía]', 'viv[ía]'] },
            { who: 'tú', cells: ['habl[abas]', 'com[ías]', 'viv[ías]'] },
            { who: 'él / ella / usted', cells: ['habl[aba]', 'com[ía]', 'viv[ía]'] },
            { who: 'nosotros', cells: ['habl[ábamos]', 'com[íamos]', 'viv[íamos]'] },
            { who: 'ellos / ellas / ustedes', cells: ['habl[aban]', 'com[ían]', 'viv[ían]'] },
          ] },
        { title: 'The only three irregular verbs',
          cols: [{ label: 'ser', tint: 'all' }, { label: 'ir', tint: 'all' }, { label: 'ver', tint: 'all' }],
          rows: [
            { who: 'yo', cells: ['[era]', '[iba]', 've[ía]'] },
            { who: 'tú', cells: ['[eras]', '[ibas]', 've[ías]'] },
            { who: 'él / ella / usted', cells: ['[era]', '[iba]', 've[ía]'] },
            { who: 'nosotros', cells: ['[éramos]', '[íbamos]', 've[íamos]'] },
            { who: 'ellos / ellas / ustedes', cells: ['[eran]', '[iban]', 've[ían]'] },
          ] },
        { title: 'Signal words that call for the imperfecto',
          cols: [{ label: 'Example', tint: 'all' }, { label: 'English', tint: 'all' }],
          rows: [
            { who: 'siempre', cells: ['Siempre comíamos a las dos.', 'We always ate at two.'] },
            { who: 'todos los días', cells: ['Todos los días iba a la escuela caminando.', 'Every day I walked to school.'] },
            { who: 'antes', cells: ['Antes vivía en el centro.', 'I used to live in the centre.'] },
            { who: 'mientras', cells: ['Mientras cocinaba, escuchaba música.', 'While I cooked, I listened to music.'] },
            { who: 'de niño', cells: ['De niño era muy tímido.', 'As a child I was very shy.'] },
            { who: 'cuando (background)', cells: ['Cuando tenía diez años, vivíamos en Quito.', 'When I was ten, we lived in Quito.'] },
          ] },
      ],
      rules: [
        { t: 'Habits and repeated actions in the past: “used to”, “would”', ex: 'Los domingos comíamos en casa de mi abuela.', en: 'On Sundays we used to eat at my grandmother’s.' },
        { t: 'Descriptions of people, places, weather, age and time', ex: 'Era tarde y hacía frío.', en: 'It was late and it was cold.' },
        { t: 'An action in progress when something else happened', ex: 'Dormía cuando sonó el teléfono.', en: 'I was sleeping when the phone rang.' },
        { t: 'Yo and él share the same form; the context or a pronoun tells them apart', ex: 'Yo tenía razón y él no tenía ni idea.', en: 'I was right and he had no idea.' },
        { t: 'The nosotros form of -ar verbs carries the accent', ex: 'Cuando éramos niños, jugábamos en la calle.', en: 'When we were children, we played in the street.' },
      ],
      watch: [
        'Every -er and -ir form has an accent on the í: comía, vivías, teníamos.',
        'Only the nosotros form of -ar verbs has an accent: hablábamos. The others (hablaba, hablaban) have none.',
        'Estar, tener, hacer and poder are regular here: estaba, tenía, hacía, podía. Their irregularity belongs to the indefinido.',
        'Hay in the imperfecto is había, one form for singular and plural: había muchas personas.',
        'Ustedes takes the ellos form: ustedes vivían, ustedes eran.',
      ],
    },
    {
      id: 'past-perf', pl: 'Perfecto', short: 'Perf.', en: 'Present perfect', q: 'he hablado, has comido',
      summary: 'The pretérito perfecto is he, has, ha, hemos, han plus the participle in -ado or -ido. In Latin America it is used for life experience and for things still open or not yet done: alguna vez, nunca, ya, todavía no, últimamente, hasta ahora. A finished event, even one from today, goes in the indefinido.',
      tables: [
        { title: 'haber + participle',
          cols: [{ label: 'haber', tint: 'all' }, { label: '-ar: hablar', tint: 'all' }, { label: '-er, -ir: comer, vivir', tint: 'all' }],
          rows: [
            { who: 'yo', cells: ['[he]', 'habl[ado]', 'com[ido], viv[ido]'] },
            { who: 'tú', cells: ['[has]', 'habl[ado]', 'com[ido], viv[ido]'] },
            { who: 'él / ella / usted', cells: ['[ha]', 'habl[ado]', 'com[ido], viv[ido]'] },
            { who: 'nosotros', cells: ['[hemos]', 'habl[ado]', 'com[ido], viv[ido]'] },
            { who: 'ellos / ellas / ustedes', cells: ['[han]', 'habl[ado]', 'com[ido], viv[ido]'] },
          ] },
        { title: 'Irregular participles',
          cols: [{ label: 'Participle', tint: 'all' }, { label: 'English', tint: 'all' }],
          rows: [
            { who: 'hacer', cells: ['[hecho]', 'done, made'] },
            { who: 'decir', cells: ['[dicho]', 'said'] },
            { who: 'ver', cells: ['[visto]', 'seen'] },
            { who: 'escribir', cells: ['[escrito]', 'written'] },
            { who: 'poner', cells: ['[puesto]', 'put'] },
            { who: 'abrir', cells: ['[abierto]', 'opened'] },
            { who: 'volver', cells: ['[vuelto]', 'returned'] },
            { who: 'romper', cells: ['[roto]', 'broken'] },
            { who: 'morir', cells: ['[muerto]', 'died'] },
            { who: 'descubrir', cells: ['[descubierto]', 'discovered'] },
            { who: 'leer', cells: ['le[í]do', 'read (accent on the í)'] },
          ] },
        { title: 'Signal words that call for the perfecto',
          cols: [{ label: 'Example', tint: 'all' }, { label: 'English', tint: 'all' }],
          rows: [
            { who: 'alguna vez', cells: ['¿Has estado alguna vez en México?', 'Have you ever been to Mexico?'] },
            { who: 'nunca', cells: ['Nunca he visto la nieve.', 'I have never seen snow.'] },
            { who: 'varias veces', cells: ['He estado varias veces en Bogotá.', 'I have been to Bogotá several times.'] },
            { who: 'ya', cells: ['Ya he leído ese libro.', 'I have already read that book.'] },
            { who: 'todavía no', cells: ['Todavía no ha llegado.', 'He has not arrived yet.'] },
            { who: 'últimamente', cells: ['Últimamente hemos trabajado mucho.', 'Lately we have worked a lot.'] },
            { who: 'hasta ahora', cells: ['Hasta ahora no hemos tenido problemas.', 'So far we have had no problems.'] },
            { who: 'siempre (up to now)', cells: ['Siempre he vivido aquí.', 'I have always lived here.'] },
          ] },
      ],
      rules: [
        { t: 'Life experience up to now, with alguna vez, nunca, varias veces', ex: '¿Has estado alguna vez en México?', en: 'Have you ever been to Mexico?' },
        { t: 'Something done by now, or not yet done, with ya and todavía no', ex: 'Todavía no he terminado.', en: 'I have not finished yet.' },
        { t: 'Something going on lately that still continues: últimamente, hasta ahora, siempre', ex: 'Últimamente he dormido mal.', en: 'Lately I have been sleeping badly.' },
        { t: 'Nothing goes between haber and the participle; pronouns come before haber', ex: 'Ya lo he hecho.', en: 'I have already done it.' },
        { t: 'The participle never changes; only haber shows the person', ex: 'Mis hermanas han llegado.', en: 'My sisters have arrived.' },
      ],
      watch: [
        'The participle of -er and -ir verbs is -ido with no accent: comido, vivido. But leer, traer, oír and caer take one: leído, traído, oído, caído.',
        'Ha is the verb; a is the preposition. Compare ha comido (has eaten) with va a comer (is going to eat).',
        'In Latin America a finished event takes the indefinido even if it happened today: hoy trabajé mucho, esta mañana desayuné tarde. Keep the perfecto for experience and for what is still open: nunca he ido, todavía no he desayunado.',
        'Reflexive pronouns go before haber: me he levantado, never “he me levantado”.',
        'Ustedes takes han: ¿Ustedes han estado en Lima?',
      ],
    },
    {
      id: 'past-choice', pl: 'Indef. o imperf.', short: '¿Cuál?', en: 'Preterite or imperfect', q: 'comía cuando llegó',
      summary: 'The imperfecto sets the scene and says what was going on; the indefinido tells what happened and moves the story forward. In Latin America this includes finished events from today: hoy me levanté tarde. Signal words help: ayer, hoy, de repente, en 2010 point to the indefinido; siempre, mientras, todos los días point to the imperfecto.',
      tables: [
        { title: 'Two jobs',
          cols: [{ label: 'Indefinido', tint: 'all' }, { label: 'Imperfecto', tint: 'all' }],
          rows: [
            { who: 'Signal words', cells: ['ayer, anoche, hoy, esta mañana, el año pasado, en 2010, de repente, hace dos días, durante tres años', 'siempre, todos los días, antes, mientras, normalmente, cuando era niño'] },
            { who: 'Used for', cells: ['a finished event, a series of events, a closed period', 'background, description, habit, age, time, weather, action in progress'] },
            { who: 'Example', cells: ['Ayer llovió mucho.', 'Llovía cuando salí.'] },
            { who: 'English', cells: ['Yesterday it rained a lot.', 'It was raining when I went out.'] },
          ] },
        { title: 'Verbs that change meaning',
          cols: [{ label: 'Imperfecto', tint: 'all' }, { label: 'Indefinido', tint: 'all' }],
          rows: [
            { who: 'saber', cells: ['sabía: knew', 'supo: found out'] },
            { who: 'conocer', cells: ['conocía: knew (a person, a place)', 'conoció: met, got to know'] },
            { who: 'querer', cells: ['quería: wanted', 'quiso: tried to; no quiso: refused'] },
            { who: 'poder', cells: ['podía: was able to', 'pudo: managed to'] },
            { who: 'tener', cells: ['tenía: had', 'tuvo: got, received'] },
          ] },
      ],
      rules: [
        { t: 'Background in the imperfecto, event in the indefinido', ex: 'Dormía cuando sonó el teléfono.', en: 'I was sleeping when the phone rang.' },
        { t: 'Two actions going on at the same time: both in the imperfecto', ex: 'Mientras yo cocinaba, ella leía.', en: 'While I cooked, she read.' },
        { t: 'Two events one after the other: both in the indefinido', ex: 'Entró, se sentó y pidió un café.', en: 'He came in, sat down and ordered a coffee.' },
        { t: 'A closed period with a stated length takes the indefinido, even if it lasted years', ex: 'Viví en Bogotá cinco años.', en: 'I lived in Bogotá for five years.' },
        { t: 'Age, time and weather as background: imperfecto', ex: 'Tenía veinte años cuando me casé.', en: 'I was twenty when I got married.' },
        { t: 'A finished event from today: indefinido, the Latin American preference', ex: 'Hoy no dormí bien.', en: 'Today I did not sleep well.' },
      ],
      watch: [
        '“Used to” or “would” in English is the imperfecto: íbamos a la playa. A single “went” is the indefinido: fuimos a la playa.',
        'Cuando goes with either: cuando era niño (background) or cuando llegó (event).',
        'Judging a finished event as a whole takes the indefinido: La fiesta fue genial. Describing the scene takes the imperfecto: La fiesta era en un jardín.',
        'Hoy, esta mañana and esta semana take the indefinido for finished events in Latin America: hoy no desayuné. The perfecto is for experience and things still open: nunca he desayunado tan tarde, todavía no he desayunado.',
      ],
    },
    {
      id: 'past-pluscuam', pl: 'Pluscuamperfecto', short: 'Plusc.', en: 'Past perfect', q: 'había hablado',
      summary: 'The pluscuamperfecto is the imperfecto of haber (había, habías, había, habíamos, habían) plus the participle. It puts one past action before another past action: cuando llegué, ya se habían ido.',
      tables: [
        { title: 'haber in the imperfecto + participle',
          cols: [{ label: 'haber', tint: 'all' }, { label: 'participle', tint: 'all' }],
          rows: [
            { who: 'yo', cells: ['[había]', 'hablado, comido, vivido'] },
            { who: 'tú', cells: ['[habías]', 'hablado, comido, vivido'] },
            { who: 'él / ella / usted', cells: ['[había]', 'hablado, comido, vivido'] },
            { who: 'nosotros', cells: ['[habíamos]', 'hablado, comido, vivido'] },
            { who: 'ellos / ellas / ustedes', cells: ['[habían]', 'hablado, comido, vivido'] },
          ] },
        { title: 'Ordering two past events',
          cols: [{ label: 'Earlier action', tint: 'all' }, { label: 'Later action', tint: 'all' }],
          rows: [
            { who: 'Example', cells: ['Ya había cenado', 'cuando llegaste.'] },
            { who: 'English', cells: ['I had already had dinner', 'when you arrived.'] },
            { who: 'Example', cells: ['Nunca había visto el mar', 'hasta aquel verano.'] },
            { who: 'English', cells: ['I had never seen the sea', 'until that summer.'] },
          ] },
      ],
      rules: [
        { t: 'One past action that happened before another', ex: 'Cuando llegué, la película ya había empezado.', en: 'When I arrived, the film had already started.' },
        { t: 'Experience up to a point in the past, with nunca, ya, todavía no', ex: 'Nunca había comido sushi antes de ese día.', en: 'I had never eaten sushi before that day.' },
        { t: 'Reported speech about something earlier', ex: 'Me dijo que había perdido el tren.', en: 'He told me he had missed the train.' },
        { t: 'The same irregular participles as the perfecto', ex: 'No habían hecho la tarea.', en: 'They had not done their homework.' },
      ],
      watch: [
        'All forms of había carry an accent on the í: había, habíamos, habían.',
        'Pronouns go before había: se había ido, lo había visto.',
        'Use it only when there is a later past point to compare with. On its own, “I had dinner” is cené, not había cenado.',
        'Ustedes takes habían: ¿Ustedes ya habían comido?',
      ],
    },
  ],

  sentences: [
    // Indefinido regular
    { c: 'past-indef-reg', s: 'Ayer{yesterday} ___ con{with} mi{my|f} hermana{sister|f}.', base: 'hablar', hint: 'yo', gloss: 'to speak', a: ['hablé'], p: 'yo', en: 'Yesterday I spoke with my sister.', why: 'Ayer points to a finished moment, so the indefinido. Yo with an -ar verb takes -é, with an accent.' },
    { c: 'past-indef-reg', s: 'Mi{my|m} padre{father|m} ___ en{in} una{a|f} fábrica{factory|f} durante{for} veinte{twenty} años{year|m.pl}.', base: 'trabajar', gloss: 'to work', a: ['trabajó'], p: 'él', en: 'My father worked in a factory for twenty years.', why: 'A closed period (durante veinte años) counts as one finished event: indefinido. Él with an -ar verb takes -ó.' },
    { c: 'past-indef-reg', s: '¿Qué{what} ___ anoche{last night} en{at} el{the|m} restaurante{restaurant|m}?', base: 'comer', hint: 'tú', gloss: 'to eat', a: ['comiste'], p: 'tú', en: 'What did you eat last night at the restaurant?', why: 'Anoche is a signal word for the indefinido. Tú with an -er verb takes -iste.' },
    { c: 'past-indef-reg', s: 'Mis{my|m.pl} abuelos{grandparents|m.pl} ___ en{in} Bogotá{Bogotá} muchos{many|m.pl} años{year|m.pl}.', base: 'vivir', gloss: 'to live', a: ['vivieron'], p: 'ellos', en: 'My grandparents lived in Bogotá for many years.', why: 'A completed stretch of their lives, so indefinido. Ellos with an -ir verb takes -ieron.' },
    { c: 'past-indef-reg', s: 'La_semana_pasada{last week|f} ___ una{a|f} carta{letter|f} a{to} mi{my|f} abuela{grandmother|f}.', base: 'escribir', hint: 'nosotros', gloss: 'to write', a: ['escribimos'], p: 'nosotros', en: 'Last week we wrote a letter to our grandmother.', why: 'La semana pasada is a definite time. Nosotros with an -ir verb takes -imos, the same as the present, so the time expression does the work.' },
    { c: 'past-indef-reg', s: '¿A_qué_hora{at what time} ___ ustedes{you (plural)} de{from} casa{home|f}?', base: 'salir', gloss: 'to leave', a: ['salieron'], p: 'ellos', en: 'What time did you leave home?', why: 'Ustedes takes the ellos form. With an -er or -ir verb that is -ieron: salieron.' },
    { c: 'past-indef-reg', s: 'Ana{Ana} ___ un{a|m} café{coffee|m} y{and} un{a|m} sándwich{sandwich|m}.', base: 'tomar', gloss: 'to have (food, drink)', a: ['tomó'], p: 'él', en: 'Ana had a coffee and a sandwich.', why: 'One finished action, so indefinido. Ella with an -ar verb takes -ó, with an accent.' },
    { c: 'past-indef-reg', s: 'El_año_pasado{last year|m} ___ inglés{English|m} en{at} una{a|f} academia{language school|f}.', base: 'aprender', hint: 'yo', gloss: 'to learn', a: ['aprendí'], p: 'yo', en: 'Last year I learned English at a language school.', why: 'El año pasado is a closed period. Yo with an -er verb takes -í.' },
    { c: 'past-indef-reg', s: 'Los{the|m.pl} niños{children|m.pl} ___ toda{all|f} la{the|f} tarde{afternoon|f} en{in} el{the|m} parque{park|m}.', base: 'jugar', gloss: 'to play', a: ['jugaron'], p: 'ellos', en: 'The children played all afternoon in the park.', why: 'Toda la tarde is a closed period, so indefinido. Ellos takes -aron. Only the yo form of jugar changes spelling (jugué).' },
    { c: 'past-indef-reg', s: 'Anoche{last night} ___ dos{two} vasos{glass|m.pl} de{of} agua{water|f} antes_de{before} dormir{sleeping}.', base: 'beber', hint: 'yo', gloss: 'to drink', a: ['bebí'], p: 'yo', en: 'Last night I drank two glasses of water before sleeping.', why: 'Anoche calls for the indefinido. Yo with an -er verb takes -í.' },
    { c: 'past-indef-reg', s: '¿Cuándo{when} ___ de{from} Buenos_Aires{Buenos Aires}, Carlos{Carlos}?', base: 'volver', hint: 'tú', gloss: 'to come back', a: ['volviste'], p: 'tú', en: 'When did you come back from Buenos Aires, Carlos?', why: 'Tú with an -er verb takes -iste. Volver changes its stem in the present (vuelvo) but not in the indefinido.' },
    { c: 'past-indef-reg', s: 'Mi{my|f} madre{mother|f} ___ la{the|f} puerta{door|f} y{and} entró{came in}.', base: 'abrir', gloss: 'to open', a: ['abrió'], p: 'él', en: 'My mother opened the door and came in.', why: 'Two events in a row, both in the indefinido. Ella with an -ir verb takes -ió.' },
    { c: 'past-indef-reg', s: 'El{the|m} sábado{Saturday|m} ___ los{the|m.pl} boletos{ticket|m.pl} por{on} internet{the internet|m}.', base: 'comprar', hint: 'nosotros', gloss: 'to buy', a: ['compramos'], p: 'nosotros', en: 'On Saturday we bought the tickets online.', why: 'Nosotros with an -ar verb takes -amos. It looks like the present, but el sábado (last Saturday) sets it in the past.' },
    { c: 'past-indef-reg', s: '¿Ustedes{you (plural)} ___ mucho{a lot} en{at} la{the|f} fiesta{party|f}?', base: 'bailar', gloss: 'to dance', a: ['bailaron'], p: 'ellos', en: 'Did you dance a lot at the party?', why: 'Ustedes takes the ellos form. With an -ar verb that is -aron: bailaron.' },
    { c: 'past-indef-reg', s: 'Mis{my|m.pl} amigos{friend|m.pl} ___ a{at} las{the|f.pl} diez{ten} de{at} la{the|f} noche{night|f}.', base: 'llegar', gloss: 'to arrive', a: ['llegaron'], p: 'ellos', en: 'My friends arrived at ten at night.', why: 'Ellos with an -ar verb takes -aron. The -gar spelling change only affects the yo form (llegué).' },
    { c: 'past-indef-reg', s: 'Hace{ago} dos{two} años{year|m.pl} ___ a{to} Ciudad_de_México{Mexico City}.', base: 'mudarse', hint: 'yo', gloss: 'to move house', a: ['me mudé'], p: 'yo', en: 'Two years ago I moved to Mexico City.', why: 'Hace dos años is a definite time. Reflexive verbs keep their pronoun: me mudé.' },
    { c: 'past-indef-reg', s: 'Hoy{today} ___ muy{very} temprano{early} en{at} la{the|f} oficina{office|f}.', base: 'terminar', hint: 'yo', gloss: 'to finish', a: ['terminé'], p: 'yo', en: 'Today I finished very early at the office.', why: 'The event is over, so in Latin America hoy takes the indefinido: terminé. Yo with an -ar verb takes -é.' },
    { c: 'past-indef-reg', s: 'El{on the|m} domingo{Sunday|m} mi{my|m} hermano{brother|m} ___ el{the|m} carro{car|m}.', base: 'lavar', gloss: 'to wash', a: ['lavó'], p: 'él', en: 'On Sunday my brother washed the car.', why: 'A finished action on a definite day: indefinido. Él with an -ar verb takes -ó, with an accent.' },
    { c: 'past-indef-reg', s: '¿Tú{you} ___ el{the|m} correo{email|m} que{that} te{you} mandé{I sent} ayer{yesterday}?', base: 'recibir', gloss: 'to receive, get', a: ['recibiste'], p: 'tú', en: 'Did you get the email I sent you yesterday?', why: 'Tú with an -ir verb takes -iste, the same as -er verbs: recibiste.' },
    { c: 'past-indef-reg', s: 'Hace{ago} tres{three} años{year|m.pl} mis{my|m.pl} padres{parents|m.pl} ___ la{the|f} casa{house|f} del{in the|m} pueblo{village|m}.', base: 'vender', gloss: 'to sell', a: ['vendieron'], p: 'ellos', en: 'Three years ago my parents sold the house in the village.', why: 'Hace tres años points to a finished moment: indefinido. Ellos with an -er verb takes -ieron.' },
    { c: 'past-indef-reg', s: 'Anoche{last night} ___ tarde{late} porque{because} había{there was} un{a|m} trancón{traffic jam|m}.', base: 'llegar', hint: 'nosotros', gloss: 'to arrive', a: ['llegamos'], p: 'nosotros', en: 'Last night we got there late because there was a traffic jam.', why: 'Anoche calls for the indefinido. Nosotros with an -ar verb takes -amos, the same as the present, so anoche shows the tense.' },
    { c: 'past-indef-reg', s: 'Esta_mañana{this morning|f} ___ dos{two} horas{hour|f.pl} para{for} el{the|m} examen{exam|m}.', base: 'estudiar', hint: 'yo', gloss: 'to study', a: ['estudié'], p: 'yo', en: 'This morning I studied for two hours for the exam.', why: 'Esta mañana is over, so the indefinido even though it is today. Yo with an -ar verb takes -é.' },

    // Indefinido irregular
    { c: 'past-indef-irr', s: 'Ayer{yesterday} ___ al{to the|m} médico{doctor|m}.', base: 'ir', hint: 'yo', gloss: 'to go', a: ['fui'], p: 'yo', en: 'Yesterday I went to the doctor.', why: 'Ir has the same forms as ser in the indefinido. Yo is fui, with no accent.' },
    { c: 'past-indef-irr', s: 'La{the|f} fiesta{party|f} ___ muy{very} divertida{fun|f}.', base: 'ser', gloss: 'to be', a: ['fue'], p: 'él', en: 'The party was great fun.', why: 'A finished event judged as a whole: indefinido. Ser in the él form is fue.' },
    { c: 'past-indef-irr', s: 'El{on|m} domingo{Sunday|m} no{not} ___ tiempo{time|m} para{for} nada{anything}.', base: 'tener', hint: 'yo', gloss: 'to have', a: ['tuve'], p: 'yo', en: 'On Sunday I had no time for anything.', why: 'Tener builds its preterite on tuv-: tuve, with no accent.' },
    { c: 'past-indef-irr', s: '¿Qué{what} ___ el_fin_de_semana{at the weekend|m}?', base: 'hacer', hint: 'tú', gloss: 'to do', a: ['hiciste'], p: 'tú', en: 'What did you do at the weekend?', why: 'Hacer uses the stem hic-. Tú takes -iste: hiciste.' },
    { c: 'past-indef-irr', s: 'Mi{my|f} hermana{sister|f} ___ un{a|m} pastel{cake|m} para{for} mi{my|m} cumpleaños{birthday|m}.', base: 'hacer', gloss: 'to make', a: ['hizo'], p: 'él', en: 'My sister made a cake for my birthday.', why: 'The él form of hacer is spelt with z to keep the sound: hizo. No accent.' },
    { c: 'past-indef-irr', s: 'Mis{my|m.pl} padres{parents|m.pl} ___ en{in} Roma{Rome} la_semana_pasada{last week|f}.', base: 'estar', gloss: 'to be', a: ['estuvieron'], p: 'ellos', en: 'My parents were in Rome last week.', why: 'Estar is a strong preterite: estuv- plus -ieron.' },
    { c: 'past-indef-irr', s: 'No{not} ___ venir{to come} a{to} la{the|f} reunión{meeting|f}, lo_siento{I am sorry}.', base: 'poder', hint: 'yo', gloss: 'can, to be able to', a: ['pude'], p: 'yo', en: 'I couldn’t come to the meeting, I’m sorry.', why: 'Poder uses the stem pud-: pude. In the indefinido no pude means I could not manage to.' },
    { c: 'past-indef-irr', s: '¿Dónde{where} ___ las{the|f.pl} llaves{key|f.pl}, Marta{Marta}?', base: 'poner', hint: 'tú', gloss: 'to put', a: ['pusiste'], p: 'tú', en: 'Where did you put the keys, Marta?', why: 'Poner uses the stem pus-: pusiste.' },
    { c: 'past-indef-irr', s: 'Juan{Juan} ___ a{to} casa{home|f} muy{very} tarde{late}.', base: 'venir', gloss: 'to come', a: ['vino'], p: 'él', en: 'Juan came home very late.', why: 'Venir has the stem vin-: vino, with no accent. It looks like the word for wine, but the context makes it clear.' },
    { c: 'past-indef-irr', s: 'Los{the|m.pl} niños{children|m.pl} no{not} ___ la{the|f} verdad{truth|f}.', base: 'decir', gloss: 'to tell', a: ['dijeron'], p: 'ellos', en: 'The children didn’t tell the truth.', why: 'Decir uses dij-, and after j the ending is -eron, not -ieron: dijeron.' },
    { c: 'past-indef-irr', s: 'Ana{Ana} me{me} ___ un{a|m} regalo{present|m} precioso{lovely|m}.', base: 'dar', gloss: 'to give', a: ['dio'], p: 'él', en: 'Ana gave me a lovely present.', why: 'Dar takes the -er/-ir endings on the stem d-: dio, with no accent because it is one syllable.' },
    { c: 'past-indef-irr', s: '¿Ustedes{you (plural)} ___ la{the|f} película{film|f} anoche{last night}?', base: 'ver', gloss: 'to watch', a: ['vieron'], p: 'ellos', en: 'Did you watch the film last night?', why: 'Ver is v- plus the -er endings. Ustedes takes the ellos form: vieron, with no accent.' },
    { c: 'past-indef-irr', s: 'Ayer{yesterday} ___ a{at} la{the|f} oficina{office|f} a{at} las{the|f.pl} ocho{eight}.', base: 'llegar', hint: 'yo', gloss: 'to arrive', a: ['llegué'], p: 'yo', en: 'Yesterday I arrived at the office at eight.', why: 'Llegar keeps its hard g sound by writing gu before é: llegué. Only the yo form changes.' },
    { c: 'past-indef-irr', s: '___ a{to} estudiar{study} español{Spanish|m} hace{ago} un{a|m} año{year|m}.', base: 'empezar', hint: 'yo', gloss: 'to begin', a: ['Empecé'], p: 'yo', en: 'I began to study Spanish a year ago.', why: 'Before é the z becomes c: empecé. The other persons are regular (empezaste, empezó).' },
    { c: 'past-indef-irr', s: 'El{the|m} mesero{waiter|m} nos{us} ___ la{the|f} cuenta{bill|f}.', base: 'traer', gloss: 'to bring', a: ['trajo'], p: 'él', en: 'The waiter brought us the bill.', why: 'Traer uses traj-: trajo. Like decir, its ellos form drops the i: trajeron.' },
    { c: 'past-indef-irr', s: 'Mi{my|m} abuelo{grandfather|m} ___ toda{all|f} la{the|f} tarde{afternoon|f}.', base: 'dormir', gloss: 'to sleep', a: ['durmió'], p: 'él', en: 'My grandfather slept all afternoon.', why: 'Dormir changes o to u in the él and ellos forms only: durmió.' },
    { c: 'past-indef-irr', s: 'Ellos{they|m.pl} ___ ceviche{ceviche|m} en{at} el{the|m} restaurante{restaurant|m}.', base: 'pedir', gloss: 'to order', a: ['pidieron'], p: 'ellos', en: 'They ordered ceviche at the restaurant.', why: 'Pedir changes e to i in the él and ellos forms: pidieron.' },
    { c: 'past-indef-irr', s: '¿Cuándo{when} ___ ustedes{you (plural)} que{that} Luis{Luis} se_casaba{was getting married}?', base: 'saber', gloss: 'to know', a: ['supieron'], p: 'ellos', en: 'When did you find out that Luis was getting married?', why: 'Saber uses sup-. In the indefinido it usually means found out. Ustedes takes the ellos form: supieron.' },
    { c: 'past-indef-irr', s: 'Ayer{yesterday} ___ un{a|m} accidente{accident|m} en{on} la{the|f} autopista{motorway|f}.', base: 'haber', hint: 'hay', gloss: 'there is (hay)', a: ['hubo'], p: 'él', en: 'Yesterday there was an accident on the motorway.', why: 'Hay becomes hubo in the indefinido, one form that never changes.' },
    { c: 'past-indef-irr', s: 'Pablo{Pablo} ___ el{the|m} periódico{newspaper|m} en{on} el{the|m} tren{train|m}.', base: 'leer', gloss: 'to read', a: ['leyó'], p: 'él', en: 'Pablo read the newspaper on the train.', why: 'Between two vowels the i of -ió becomes y: leyó, leyeron.' },
    { c: 'past-indef-irr', s: 'El_año_pasado{last year|m} ___ a{to} Cartagena{Cartagena} de{on} vacaciones{holiday|f.pl}.', base: 'ir', hint: 'nosotros', gloss: 'to go', a: ['fuimos'], p: 'nosotros', en: 'Last year we went to Cartagena on holiday.', why: 'Ir and ser share the same indefinido: nosotros fuimos.' },
    { c: 'past-indef-irr', s: 'Mis{my|m.pl} amigos{friends|m.pl} no{not} ___ venir{come} a{to} mi{my|f} fiesta{party|f}.', base: 'querer', gloss: 'to want', a: ['quisieron'], p: 'ellos', en: 'My friends refused to come to my party.', why: 'Querer has the strong stem quis-, and ellos takes -ieron: quisieron. In the negative it means they refused.' },
    { c: 'past-indef-irr', s: '¿Qué{what} te{you} ___ el{the|m} médico{doctor|m}?', base: 'decir', gloss: 'to say, tell', a: ['dijo'], p: 'él', en: 'What did the doctor tell you?', why: 'Decir has the strong stem dij-: dijo, with no accent.' },
    { c: 'past-indef-irr', s: 'Ayer{yesterday} ___ en{at} casa{home|f} todo{all|m} el{the|m} día{day|m}.', base: 'estar', hint: 'yo', gloss: 'to be', a: ['estuve'], p: 'yo', en: 'Yesterday I was at home all day.', why: 'Estar has the strong stem estuv-: estuve, with no accent.' },
    { c: 'past-indef-irr', s: 'Anoche{last night} no{not} ___ bien{well} por{because of} el{the|m} ruido{noise|m}.', base: 'dormir', hint: 'yo', gloss: 'to sleep', a: ['dormí'], p: 'yo', en: 'Last night I didn’t sleep well because of the noise.', why: 'Dormir changes o to u only in the él and ellos forms (durmió, durmieron); yo is regular: dormí.' },

    // Imperfecto
    { c: 'past-imperf', s: 'Cuando{when} era{I was} niño{child|m}, ___ en{in} un{a|m} pueblo{village|m} pequeño{small|m}.', base: 'vivir', hint: 'yo', gloss: 'to live', a: ['vivía'], p: 'yo', en: 'When I was a child, I lived in a small village.', why: 'Cuando era niño sets a background in the past, so the imperfecto. Yo with an -ir verb takes -ía.' },
    { c: 'past-imperf', s: 'Mi{my|f} abuela{grandmother|f} siempre{always} ___ pan{bread|m} los{on|m.pl} domingos{Sunday|m.pl}.', base: 'hacer', gloss: 'to make', a: ['hacía'], p: 'él', en: 'My grandmother always made bread on Sundays.', why: 'Siempre marks a habit. Hacer is regular in the imperfecto: hacía.' },
    { c: 'past-imperf', s: 'Antes{before} ___ fútbol{football|m} todos_los_sábados{every Saturday|m.pl}.', base: 'jugar', hint: 'nosotros', gloss: 'to play', a: ['jugábamos'], p: 'nosotros', en: 'We used to play football every Saturday.', why: 'Antes signals a past habit: imperfecto. The nosotros form of -ar verbs is the only one with an accent: jugábamos.' },
    { c: 'past-imperf', s: '___ las{the|f.pl} diez{ten} y{and} no{not} había{there was} nadie{nobody} en{in} la{the|f} calle{street|f}.', base: 'ser', hint: 'clock time', gloss: 'to be', a: ['Eran'], p: 'ellos', en: 'It was ten o’clock and there was nobody in the street.', why: 'Clock time in the past always goes in the imperfecto, and the hours are plural: eran las diez.' },
    { c: 'past-imperf', s: 'Mientras{while} yo{I} cocinaba{was cooking}, mi{my|m} esposo{husband|m} ___ la{the|f} mesa{table|f}.', base: 'poner', gloss: 'to set (the table)', a: ['ponía'], p: 'él', en: 'While I was cooking, my husband was setting the table.', why: 'Mientras links two actions going on at the same time: imperfecto. Poner is regular here: ponía.' },
    { c: 'past-imperf', s: 'De_niños{as children|m.pl} ___ a{to} la{the|f} escuela{school|f} caminando{on foot}.', base: 'ir', hint: 'nosotros', gloss: 'to go', a: ['íbamos'], p: 'nosotros', en: 'As children we walked to school.', why: 'Ir is one of the three irregular verbs: íbamos, with an accent on the í.' },
    { c: 'past-imperf', s: 'Mis{my|m.pl} padres{parents|m.pl} ___ muy{very} jóvenes{young|m.pl} en{in} esa{that|f} foto{photo|f}.', base: 'ser', gloss: 'to be', a: ['eran'], p: 'ellos', en: 'My parents were very young in that photo.', why: 'A description of how people looked: imperfecto. Ser is irregular: eran.' },
    { c: 'past-imperf', s: 'Todos_los_veranos{every summer|m.pl} ___ a{(personal a)} mis{my|m.pl} primos{cousin|m.pl} en{at} la{the|f} playa{beach|f}.', base: 'ver', hint: 'yo', gloss: 'to see', a: ['veía'], p: 'yo', en: 'Every summer I saw my cousins at the beach.', why: 'Todos los veranos marks a repeated action. Ver keeps its e in the imperfecto: veía.' },
    { c: 'past-imperf', s: '¿Dónde{where} ___ tú{you} cuando{when} eras{you were} niño{child|m}?', base: 'vivir', gloss: 'to live', a: ['vivías'], p: 'tú', en: 'Where did you live when you were a child?', why: 'Cuando eras niño is a background time, so the imperfecto: vivías.' },
    { c: 'past-imperf', s: 'Hacía{it was} frío{cold|m} y{and} ___ mucho{a lot}.', base: 'llover', hint: 'it', gloss: 'to rain', a: ['llovía'], p: 'él', en: 'It was cold and it was raining a lot.', why: 'Weather as background: imperfecto. Llover is regular: llovía.' },
    { c: 'past-imperf', s: 'Cuando{when} ___ tiempo{time|m}, leíamos{we read} juntos{together|m.pl}.', base: 'tener', hint: 'nosotros', gloss: 'to have', a: ['teníamos'], p: 'nosotros', en: 'When we had time, we read together.', why: 'A habit: whenever we had time. Tener is regular in the imperfecto: teníamos.' },
    { c: 'past-imperf', s: 'Los{on|m.pl} sábados{Saturday|m.pl} ustedes{you (plural)} siempre{always} ___ hasta{until} muy{very} tarde{late}.', base: 'dormir', gloss: 'to sleep', a: ['dormían'], p: 'ellos', en: 'On Saturdays you always slept until very late.', why: 'Ustedes takes the ellos form, -ían: dormían. There is no stem change in the imperfecto.' },
    { c: 'past-imperf', s: 'En{in} aquella{that|f} época{time|f} no{not} ___ celulares{cell phone|m.pl}.', base: 'haber', hint: 'hay', gloss: 'there is (hay)', a: ['había'], p: 'él', en: 'In those days there were no cell phones.', why: 'Hay in the imperfecto is había, and it stays singular even with a plural noun.' },
    { c: 'past-imperf', s: 'Mi{my|m} hermano{brother|m} ___ mucha{a lot of|f} hambre{hunger|f} después_del{after the|m} partido{match|m}.', base: 'tener', gloss: 'to have', a: ['tenía'], p: 'él', en: 'My brother was very hungry after the match.', why: 'A state, not an event, so the imperfecto: tenía.' },
    { c: 'past-imperf', s: 'Cada{every} mañana{morning|f} ___ un{a|m} café{coffee|m} en{at} la{the|f} cafetería{café|f} de{on} la{the|f} esquina{corner|f}.', base: 'tomar', hint: 'yo', gloss: 'to have (food, drink)', a: ['tomaba'], p: 'yo', en: 'Every morning I had a coffee at the café on the corner.', why: 'Cada mañana marks a routine: imperfecto. Yo with an -ar verb takes -aba, which is also the él form.' },
    { c: 'past-imperf', s: 'Los{the|m.pl} niños{children|m.pl} ___ en{in} el{the|m} jardín{garden|m} mientras{while} llovía{it rained}.', base: 'jugar', gloss: 'to play', a: ['jugaban'], p: 'ellos', en: 'The children were playing in the garden while it rained.', why: 'Two actions going on at the same time: imperfecto. Ellos takes -aban.' },
    { c: 'past-imperf', s: '¿Ustedes{you (plural)} ya{already} ___ a{(personal a)} María{María} antes_de{before} la{the|f} boda{wedding|f}?', base: 'conocer', gloss: 'to know (a person)', a: ['conocían'], p: 'ellos', en: 'Did you already know María before the wedding?', why: 'Knowing someone is a state, so the imperfecto. Ustedes takes the ellos form: conocían.' },
    { c: 'past-imperf', s: 'Cuando{when} era{I was} pequeña{little|f}, mi{my|f} mamá{mom|f} me{me} ___ cuentos{stories|m.pl} todas{every|f.pl} las{the|f.pl} noches{night|f.pl}.', base: 'leer', gloss: 'to read', a: ['leía'], p: 'él', en: 'When I was little, my mom read me stories every night.', why: 'Todas las noches marks a habit in the past: imperfecto. Leer is regular: leía.' },
    { c: 'past-imperf', s: 'Antes{before} ___ en{in} un{a|m} banco{bank|m}, pero{but} ahora{now} soy{I am} profesor{teacher|m}.', base: 'trabajar', hint: 'yo', gloss: 'to work', a: ['trabajaba'], p: 'yo', en: 'I used to work in a bank, but now I’m a teacher.', why: 'Antes describes how things used to be: imperfecto. Yo with an -ar verb takes -aba.' },
    { c: 'past-imperf', s: 'De{as} niños{children|m.pl}, mi{my|m} hermano{brother|m} y{and} yo{I} ___ mucha{a lot of|f} televisión{television|f}.', base: 'ver', gloss: 'to watch', a: ['veíamos'], p: 'nosotros', en: 'As children, my brother and I watched a lot of television.', why: 'Ver is one of the three irregular verbs in the imperfecto: it keeps the e, veíamos.' },
    { c: 'past-imperf', s: '¿Ustedes{you all} ___ cerca{near} del{to the|m} colegio{school|m}?', base: 'vivir', gloss: 'to live', a: ['vivían'], p: 'ellos', en: 'Did you all use to live near the school?', why: 'Ustedes takes the ellos form, and -ir verbs take -ían: vivían.' },
    { c: 'past-imperf', s: 'La{the|f} casa{house|f} de{of} mis{my|m.pl} abuelos{grandparents|m.pl} ___ un{a|m} jardín{garden|m} enorme{huge} con{with} árboles{trees|m.pl} de{of} mango{mango|m}.', base: 'tener', gloss: 'to have', a: ['tenía'], p: 'él', en: 'My grandparents’ house had a huge garden with mango trees.', why: 'Describing what something was like in the past: imperfecto, tenía.' },
    { c: 'past-imperf', s: 'Tú{you} siempre{always} ___ tarde{late} a{to} clase{class|f}.', base: 'llegar', gloss: 'to arrive', a: ['llegabas'], p: 'tú', en: 'You always used to arrive late to class.', why: 'Siempre marks a past habit: imperfecto. Tú with an -ar verb takes -abas.' },

    // Perfecto
    { c: 'past-perf', s: 'Nunca{never} ___ en{in} una{a|f} oficina{office|f} tan{so} grande{big|f}.', base: 'trabajar', hint: 'yo', gloss: 'to work', a: ['he trabajado'], p: 'yo', en: 'I have never worked in such a big office.', why: 'Nunca, in your life up to now: perfecto. He plus the -ado participle.' },
    { c: 'past-perf', s: '¿Alguna_vez{ever} ___ en{in} Japón{Japan}?', base: 'estar', hint: 'tú', gloss: 'to be', a: ['has estado'], p: 'tú', en: 'Have you ever been to Japan?', why: 'Alguna vez asks about life experience up to now: perfecto. Tú is has plus estado.' },
    { c: 'past-perf', s: 'Mi{my|f} madre{mother|f} todavía{still} no{not} ___ del{from the|m} mercado{market|m}.', base: 'volver', gloss: 'to come back', a: ['ha vuelto'], p: 'él', en: 'My mother hasn’t come back from the market yet.', why: 'Todavía no means not yet, something still open: perfecto. Volver has the irregular participle vuelto.' },
    { c: 'past-perf', s: 'Hasta_ahora{so far} ___ mucho{a lot of|m} español{Spanish|m}.', base: 'aprender', hint: 'nosotros', gloss: 'to learn', a: ['hemos aprendido'], p: 'nosotros', en: 'So far we have learned a lot of Spanish.', why: 'Hasta ahora reaches up to now, with more to come: perfecto. Hemos plus the -ido participle.' },
    { c: 'past-perf', s: '¿Ustedes{you (plural)} ___ alguna_vez{ever} un{a|m} viaje{trip|m} en{by} barco{ship|m}?', base: 'hacer', gloss: 'to do, to make', a: ['han hecho'], p: 'ellos', en: 'Have you ever taken a trip by ship?', why: 'Alguna vez asks about life experience: perfecto. Ustedes takes the ellos form, han, and hacer has the irregular participle hecho.' },
    { c: 'past-perf', s: 'Mis{my|f.pl} hijas{daughter|f.pl} ya{already} ___ la{the|f} tarea{homework|f}.', base: 'terminar', gloss: 'to finish', a: ['han terminado'], p: 'ellos', en: 'My daughters have already finished their homework.', why: 'Ya (already) for something done by now: perfecto. Han plus terminado.' },
    { c: 'past-perf', s: 'Nunca{never} ___ una{a|f} carta{letter|f} de{of} amor{love|m}.', base: 'escribir', hint: 'yo', gloss: 'to write', a: ['he escrito'], p: 'yo', en: 'I have never written a love letter.', why: 'Nunca, in your life up to now: perfecto. Escribir has the irregular participle escrito.' },
    { c: 'past-perf', s: '¿Alguna_vez{ever} te{yourself} ___ un{a|m} hueso{bone|m}?', base: 'romperse', hint: 'tú', gloss: 'to break (a bone)', a: ['has roto'], p: 'tú', en: 'Have you ever broken a bone?', why: 'Life experience: perfecto. Romper has the irregular participle roto, and the pronoun te stays in front of haber.' },
    { c: 'past-perf', s: '¿Ya{already} ___ la{the|f} película{film|f} nueva{new|f}?', base: 'ver', hint: 'tú', gloss: 'to see', a: ['has visto'], p: 'tú', en: 'Have you already seen the new film?', why: 'Ya asks whether something has been done by now: perfecto. Ver has the participle visto.' },
    { c: 'past-perf', s: 'Siempre{always} ___ en{in} esta{this|f} ciudad{city|f}.', base: 'vivir', hint: 'yo', gloss: 'to live', a: ['he vivido'], p: 'yo', en: 'I have always lived in this city.', why: 'Siempre, from birth until now and still true: perfecto. Vivir has a regular participle: vivido.' },
    { c: 'past-perf', s: 'Últimamente{lately} mis{my|m.pl} vecinos{neighbour|m.pl} ___ mucho{a lot of|m} ruido{noise|m}.', base: 'hacer', gloss: 'to make', a: ['han hecho'], p: 'ellos', en: 'Lately my neighbours have made a lot of noise.', why: 'Últimamente reaches up to now: perfecto. Han plus hecho.' },
    { c: 'past-perf', s: 'Los{the|m.pl} niños{children|m.pl} todavía{still} no{not} ___ y{and} ya{already} es{it is} mediodía{midday|m}.', base: 'levantarse', gloss: 'to get up', a: ['se han levantado'], p: 'ellos', en: 'The children haven’t got up yet and it is already midday.', why: 'Todavía no means not yet: perfecto. The reflexive pronoun goes before haber: se han levantado.' },
    { c: 'past-perf', s: 'La{the|f} tienda{shop|f} todavía{still} no{not} ___.', base: 'abrir', gloss: 'to open', a: ['ha abierto'], p: 'él', en: 'The shop hasn’t opened yet.', why: 'Todavía no, something still pending: perfecto. Abrir has the irregular participle abierto.' },
    { c: 'past-perf', s: 'Ustedes{you (plural)} todavía{still} no{not} le{to her} ___ lo_que{what} pasó{happened}.', base: 'decir', gloss: 'to tell', a: ['han dicho'], p: 'ellos', en: 'You still haven’t told her what happened.', why: 'Todavía no: perfecto. Ustedes takes han, decir has the participle dicho, and le stays in front of haber.' },
    { c: 'past-perf', s: 'Mi{my|m} hermano{brother|m} nunca{never} ___ un{a|m} pie{foot|m} en{in} un{a|m} gimnasio{gym|m}.', base: 'poner', gloss: 'to put', a: ['ha puesto'], p: 'él', en: 'My brother has never set foot in a gym.', why: 'Nunca, in his whole life so far: perfecto. Poner has the participle puesto.' },
    { c: 'past-perf', s: 'Ustedes{you (plural)} nunca{never} ___ ceviche{ceviche|m}, ¿verdad{right}?', base: 'comer', gloss: 'to eat', a: ['han comido'], p: 'ellos', en: 'You have never eaten ceviche, right?', why: 'Life experience: perfecto. Ustedes takes the ellos form, han, plus the regular participle comido.' },
    { c: 'past-perf', s: 'Ellos{they|m.pl} ya{already} ___ el{the|m} libro{book|m}.', base: 'leer', gloss: 'to read', a: ['han leído'], p: 'ellos', en: 'They have already read the book.', why: 'Leer takes an accent on its participle because the í sits between vowels: leído.' },
    { c: 'past-perf', s: 'Este{this|m} año{year|m} ___ tres{three} veces{times|f.pl} a{to} Medellín{Medellín}.', base: 'ir', hint: 'nosotros', gloss: 'to go', a: ['hemos ido'], p: 'nosotros', en: 'This year we have been to Medellín three times.', why: 'Este año is still going on and the trips count up to now: perfecto. Ir has the participle ido.' },
    { c: 'past-perf', s: '¿Ya{already} ___ la{the|f} puerta{door|f} con{with} llave{key|f}?', base: 'cerrar', hint: 'tú', gloss: 'to close, lock', a: ['has cerrado'], p: 'tú', en: 'Have you locked the door yet?', why: 'Ya asks whether something has happened up to now: perfecto. Tú is has plus cerrado.' },
    { c: 'past-perf', s: 'Mis{my|m.pl} padres{parents|m.pl} nunca{never} ___ en{by} avión{plane|m}.', base: 'viajar', gloss: 'to travel', a: ['han viajado'], p: 'ellos', en: 'My parents have never travelled by plane.', why: 'Nunca, in their lives up to now: perfecto. Ellos is han plus viajado.' },
    { c: 'past-perf', s: 'Todavía{still} no{not} ___ los{the|m.pl} regalos{presents|m.pl}.', base: 'abrir', hint: 'nosotros', gloss: 'to open', a: ['hemos abierto'], p: 'nosotros', en: 'We haven’t opened the presents yet.', why: 'Todavía no: perfecto. Abrir has the irregular participle abierto.' },
    { c: 'past-perf', s: 'Últimamente{lately} mi{my|f} hija{daughter|f} ___ muy{very} bien{well}.', base: 'dormir', gloss: 'to sleep', a: ['ha dormido'], p: 'él', en: 'Lately my daughter has been sleeping very well.', why: 'Últimamente covers a stretch of time up to now: perfecto. Ella is ha plus dormido.' },

    // Indefinido o imperfecto
    { c: 'past-choice', s: 'Ayer{yesterday} ___ mucho{a lot} en{in} Bogotá{Bogotá}.', base: 'llover', hint: 'it', gloss: 'to rain', a: ['llovió'], p: 'él', en: 'Yesterday it rained a lot in Bogotá.', why: 'Ayer names a finished day: indefinido. Llovió, not llovía.' },
    { c: 'past-choice', s: 'Cuando{when} era{I was} niño{child|m}, ___ mucho{a lot} en{in} Bogotá{Bogotá}.', base: 'llover', hint: 'it', gloss: 'to rain', a: ['llovía'], p: 'él', en: 'When I was a child, it rained a lot in Bogotá.', why: 'Cuando era niño describes how things used to be: imperfecto.' },
    { c: 'past-choice', s: '___ la{the|f} televisión{television|f} cuando{when} alguien{someone} llamó{knocked} a{at} la{the|f} puerta{door|f}.', base: 'ver', hint: 'yo', gloss: 'to watch', a: ['Veía'], p: 'yo', en: 'I was watching television when someone knocked at the door.', why: 'An action in progress interrupted by an event: the ongoing action goes in the imperfecto, the knock in the indefinido.' },
    { c: 'past-choice', s: 'De_repente{suddenly} ___ un{a|m} ruido{noise|m} muy{very} fuerte{loud|m}.', base: 'oír', hint: 'nosotros', gloss: 'to hear', a: ['oímos'], p: 'nosotros', en: 'Suddenly we heard a very loud noise.', why: 'De repente introduces a sudden event: indefinido. Oír in the nosotros form is oímos.' },
    { c: 'past-choice', s: 'Antes{before} mi{my|m} padre{father|m} ___ en{at} el{the|m} banco{bank|m}, ahora{now} está{he is} jubilado{retired|m}.', base: 'trabajar', gloss: 'to work', a: ['trabajaba'], p: 'él', en: 'My father used to work at the bank, now he is retired.', why: 'Antes contrasts a past habit with now: imperfecto.' },
    { c: 'past-choice', s: 'En{in} 2010{2010} mi{my|f} familia{family|f} ___ a{to} Alemania{Germany}.', base: 'mudarse', gloss: 'to move house', a: ['se mudó'], p: 'él', en: 'In 2010 my family moved to Germany.', why: 'En 2010 gives a definite date: indefinido. Reflexive verbs keep the pronoun: se mudó.' },
    { c: 'past-choice', s: 'Todos_los_días{every day|m.pl} ___ a{at} la{the|f} misma{same|f} hora{time|f}.', base: 'levantarse', hint: 'yo', gloss: 'to get up', a: ['me levantaba'], p: 'yo', en: 'Every day I got up at the same time.', why: 'Todos los días marks a routine: imperfecto.' },
    { c: 'past-choice', s: '___ veinte{twenty} años{year|m.pl} cuando{when} conocí{I met} a{(personal a)} tu{your|m} padre{father|m}.', base: 'tener', hint: 'yo', gloss: 'to have', a: ['Tenía'], p: 'yo', en: 'I was twenty when I met your father.', why: 'Age is background information: imperfecto. The meeting itself is an event, hence conocí.' },
    { c: 'past-choice', s: 'Mientras{while} tú{you} dormías{were sleeping}, yo{I} ___ toda{all|f} la{the|f} casa{house|f}.', base: 'limpiar', gloss: 'to clean', a: ['limpiaba', 'limpié'], p: 'yo', en: 'While you were sleeping, I was cleaning the whole house.', why: 'Mientras usually pairs two ongoing actions, so limpiaba. Limpié is also correct if you present the cleaning as one finished job.' },
    { c: 'past-choice', s: 'Anoche{last night} ustedes{you (plural)} ___ a{to} casa{home|f} muy{very} tarde{late}.', base: 'llegar', gloss: 'to arrive', a: ['llegaron'], p: 'ellos', en: 'Last night you got home very late.', why: 'Anoche is a finished point in time: indefinido. Ustedes takes the ellos form: llegaron.' },
    { c: 'past-choice', s: 'La{the|f} casa{house|f} de{of} mis{my|m.pl} abuelos{grandparents|m.pl} ___ muy{very} grande{big|f} y{and} tenía{had} un{a|m} jardín{garden|m}.', base: 'ser', gloss: 'to be', a: ['era'], p: 'él', en: 'My grandparents’ house was very big and had a garden.', why: 'A description of a place, with no event: imperfecto. Tenía in the same sentence confirms it.' },
    { c: 'past-choice', s: 'El_año_pasado{last year|m} ___ en{in} Argentina{Argentina} tres{three} meses{month|m.pl}.', base: 'estar', hint: 'nosotros', gloss: 'to be', a: ['estuvimos'], p: 'nosotros', en: 'Last year we were in Argentina for three months.', why: 'A closed period with a stated length (tres meses): indefinido, even though it lasted a while.' },
    { c: 'past-choice', s: 'Siempre{always} ___ la{the|f} misma{same|f} canción{song|f} en{in} el{the|m} carro{car|m}.', base: 'cantar', hint: 'ellos', gloss: 'to sing', a: ['cantaban'], p: 'ellos', en: 'They always sang the same song in the car.', why: 'Siempre marks a habit: imperfecto.' },
    { c: 'past-choice', s: 'Ayer{yesterday} ___ a{(personal a)} una{a|f} chica{girl|f} muy{very} simpática{nice|f} en{at} la{the|f} fiesta{party|f}.', base: 'conocer', hint: 'yo', gloss: 'to know, to meet', a: ['conocí'], p: 'yo', en: 'Yesterday I met a very nice girl at the party.', why: 'Conocer in the indefinido means to meet for the first time: conocí. Conocía would mean I already knew her.' },
    { c: 'past-choice', s: 'No{not} ___ que{that} estabas{you were} enfermo{ill|m}, lo_siento{I am sorry}.', base: 'saber', hint: 'yo', gloss: 'to know', a: ['sabía'], p: 'yo', en: 'I didn’t know you were ill, I’m sorry.', why: 'Knowing is a state, so the imperfecto: no sabía. No supe would mean I never found out.' },
    { c: 'past-choice', s: 'Cuando{when} ___ a{to} casa{home|f}, mi{my|f} hermana{sister|f} estaba{was} llorando{crying}.', base: 'llegar', hint: 'yo', gloss: 'to arrive', a: ['llegué'], p: 'yo', en: 'When I got home, my sister was crying.', why: 'The arrival is the event that interrupts the background (estaba llorando): indefinido. Remember the spelling llegué.' },
    { c: 'past-choice', s: 'Mi{my|f} abuela{grandmother|f} ___ de{from} un{a|m} pueblo{village|m} de{in} Oaxaca{Oaxaca}.', base: 'ser', gloss: 'to be', a: ['era'], p: 'él', en: 'My grandmother was from a village in Oaxaca.', why: 'Where someone is from is a permanent description: imperfecto.' },
    { c: 'past-choice', s: 'El{the|m} viaje{trip|m} ___ estupendo{wonderful|m}, gracias{thanks}.', base: 'ser', gloss: 'to be', a: ['fue'], p: 'él', en: 'The trip was wonderful, thanks.', why: 'The trip is over and judged as a whole: indefinido, fue.' },
    { c: 'past-choice', s: 'Hoy{today} ___ muy{very} temprano{early} para{to} ir{go} al{to the|m} aeropuerto{airport|m}.', base: 'levantarse', hint: 'yo', gloss: 'to get up', a: ['me levanté'], p: 'yo', en: 'Today I got up very early to go to the airport.', why: 'A finished event, even from today, takes the indefinido in Latin America: me levanté. The perfecto is kept for experience and things still open.' },
    { c: 'past-choice', s: 'Esta{this|f} mañana{morning|f} no{not} ___ tiempo{time|m} de{to} desayunar{have breakfast}.', base: 'tener', hint: 'yo', gloss: 'to have', a: ['tuve'], p: 'yo', en: 'This morning I didn’t have time for breakfast.', why: 'Esta mañana is over, so Latin American Spanish uses the indefinido: tuve, on the strong stem tuv-.' },
    { c: 'past-choice', s: 'Cuando{when} ___ niña{girl|f}, vivía{I lived} en{in} Cali{Cali}.', base: 'ser', hint: 'yo', gloss: 'to be', a: ['era'], p: 'yo', en: 'When I was a girl, I lived in Cali.', why: 'Describing a stage of life: imperfecto, era.' },
    { c: 'past-choice', s: 'Mientras{while} mi{my|m} papá{dad|m} cocinaba{was cooking}, el{the|m} teléfono{phone|m} ___.', base: 'sonar', gloss: 'to ring', a: ['sonó'], p: 'él', en: 'While my dad was cooking, the phone rang.', why: 'The ring interrupts the cooking: a single event, so the indefinido, sonó.' },
    { c: 'past-choice', s: 'Ayer{yesterday} ___ tres{three} horas{hour|f.pl} en{at} el{the|m} gimnasio{gym|m}.', base: 'estar', hint: 'yo', gloss: 'to be', a: ['estuve'], p: 'yo', en: 'Yesterday I was at the gym for three hours.', why: 'A closed period on a finished day: indefinido, estuve.' },
    { c: 'past-choice', s: 'Antes{in the past} mis{my|m.pl} abuelos{grandparents|m.pl} ___ a{to} misa{mass|f} todos{every|m.pl} los{the|m.pl} domingos{Sunday|m.pl}.', base: 'ir', gloss: 'to go', a: ['iban'], p: 'ellos', en: 'My grandparents used to go to mass every Sunday.', why: 'Antes and todos los domingos mark a past habit: imperfecto, iban.' },
    { c: 'past-choice', s: 'Hacía{it was} sol{sunny|m} y{and} los{the|m.pl} niños{children|m.pl} ___ en{in} la{the|f} piscina{pool|f}.', base: 'nadar', gloss: 'to swim', a: ['nadaban'], p: 'ellos', en: 'It was sunny and the children were swimming in the pool.', why: 'Background description of a scene: imperfecto, nadaban.' },
    { c: 'past-choice', s: 'La_semana_pasada{last week|f} ___ un{a|m} accidente{accident|m} con{with} la{the|f} bicicleta{bicycle|f}.', base: 'tener', hint: 'yo', gloss: 'to have', a: ['tuve'], p: 'yo', en: 'Last week I had an accident on my bike.', why: 'A single event in a finished week: indefinido, tuve.' },

    // Pluscuamperfecto
    { c: 'past-pluscuam', s: 'Cuando{when} llegamos{we arrived} al{at the|m} cine{cinema|m}, la{the|f} película{film|f} ya{already} ___.', base: 'empezar', gloss: 'to start', a: ['había empezado'], p: 'él', en: 'When we arrived at the cinema, the film had already started.', why: 'The film started before we arrived, so the earlier action goes in the pluscuamperfecto.' },
    { c: 'past-pluscuam', s: 'Nunca{never} ___ el{the|m} mar{sea|m} hasta{until} aquel{that|m} verano{summer|m}.', base: 'ver', hint: 'yo', gloss: 'to see', a: ['había visto'], p: 'yo', en: 'I had never seen the sea until that summer.', why: 'Experience up to a point in the past: pluscuamperfecto. Ver has the participle visto.' },
    { c: 'past-pluscuam', s: 'Marta{Marta} me{me} dijo{told} que{that} ___ el{the|m} tren{train|m}.', base: 'perder', gloss: 'to miss', a: ['había perdido'], p: 'él', en: 'Marta told me she had missed the train.', why: 'Reported speech about something that happened before she spoke: había plus perdido.' },
    { c: 'past-pluscuam', s: 'Cuando{when} volvimos{we came back}, los{the|m.pl} niños{children|m.pl} ya{already} ___.', base: 'acostarse', gloss: 'to go to bed', a: ['se habían acostado'], p: 'ellos', en: 'When we came back, the children had already gone to bed.', why: 'They went to bed before we came back: pluscuamperfecto. The reflexive pronoun goes first: se habían acostado.' },
    { c: 'past-pluscuam', s: 'No{not} pude{I could} entrar{go in} porque{because} ___ las{the|f.pl} llaves{key|f.pl} en{at} casa{home|f}.', base: 'dejar', hint: 'yo', gloss: 'to leave', a: ['había dejado'], p: 'yo', en: 'I couldn’t get in because I had left the keys at home.', why: 'Leaving the keys happened before the failed attempt to get in: había dejado.' },
    { c: 'past-pluscuam', s: '¿Ustedes{you (plural)} ya{already} ___ en{in} España{Spain} antes_de{before} ese{that|m} viaje{trip|m}?', base: 'estar', gloss: 'to be', a: ['habían estado'], p: 'ellos', en: 'Had you already been to Spain before that trip?', why: 'Antes de ese viaje marks an earlier past. Ustedes takes the ellos form: habían plus estado.' },
    { c: 'past-pluscuam', s: 'Llegué{I arrived} tarde{late} y{and} mis{my|m.pl} amigos{friend|m.pl} ya{already} ___.', base: 'irse', gloss: 'to leave', a: ['se habían ido'], p: 'ellos', en: 'I arrived late and my friends had already left.', why: 'They left before I arrived: se habían ido. Ir has a regular participle: ido.' },
    { c: 'past-pluscuam', s: 'Ana{Ana} estaba{was} contenta{happy|f} porque{because} ___ el{the|m} examen{exam|m}.', base: 'aprobar', gloss: 'to pass', a: ['había aprobado'], p: 'él', en: 'Ana was happy because she had passed the exam.', why: 'Passing the exam came before her being happy: había aprobado.' },
    { c: 'past-pluscuam', s: 'Cuando{when} tú{you} llamaste{called}, todavía{still} no{not} ___.', base: 'cenar', hint: 'nosotros', gloss: 'to have dinner', a: ['habíamos cenado'], p: 'nosotros', en: 'When you called, we hadn’t had dinner yet.', why: 'Todavía no plus a past point: pluscuamperfecto. Habíamos carries an accent on the í.' },
    { c: 'past-pluscuam', s: 'El{the|m} mesero{waiter|m} nos{us} trajo{brought} un{a|m} plato{dish|m} que{that} no{not} ___.', base: 'pedir', hint: 'nosotros', gloss: 'to order', a: ['habíamos pedido'], p: 'nosotros', en: 'The waiter brought us a dish we hadn’t ordered.', why: 'The ordering, or not, came before the bringing: habíamos pedido.' },
    { c: 'past-pluscuam', s: 'Nunca{never} ___ tanto{so much|m} frío{cold|m} como{as} aquel{that|m} invierno{winter|m}.', base: 'hacer', hint: 'it', gloss: 'to be (weather)', a: ['había hecho'], p: 'él', en: 'It had never been as cold as that winter.', why: 'Weather before a past point: había hecho. Hacer has the participle hecho.' },
    { c: 'past-pluscuam', s: '¿Tú{you} ya{already} ___ ese{that|m} libro{book|m} antes_de{before} la{the|f} clase{class|f}?', base: 'leer', gloss: 'to read', a: ['habías leído'], p: 'tú', en: 'Had you already read that book before the class?', why: 'Reading before the class: habías leído. The participle leído has an accent.' },
    { c: 'past-pluscuam', s: 'Cuando{when} llegó{arrived} la{the|f} policía{police|f}, los{the|m.pl} ladrones{thief|m.pl} ya{already} ___.', base: 'escapar', gloss: 'to escape', a: ['habían escapado'], p: 'ellos', en: 'When the police arrived, the thieves had already escaped.', why: 'Escaping came before the police arriving: habían escapado.' },
    { c: 'past-pluscuam', s: 'Hasta{until} ese{that|m} día{day|m} ella{she|f} no{not} me{me} ___ nada{anything} de{about} la{the|f} boda{wedding|f}.', base: 'decir', gloss: 'to tell', a: ['había dicho'], p: 'él', en: 'Until that day she hadn’t told me anything about the wedding.', why: 'Hasta ese día sets the past point: había dicho, with the irregular participle dicho.' },
    { c: 'past-pluscuam', s: 'Cuando{when} llegué{I arrived} a{at} la{the|f} estación{station|f}, el{the|m} bus{bus|m} ya{already} ___.', base: 'salir', gloss: 'to leave', a: ['había salido'], p: 'él', en: 'When I got to the station, the bus had already left.', why: 'The bus left before I arrived, so the earlier action takes the pluscuamperfecto: había salido.' },
    { c: 'past-pluscuam', s: 'Nunca{never} ___ antes_de{before} ese{that|m} viaje{trip|m} a{to} Miami{Miami}.', base: 'volar', hint: 'yo', gloss: 'to fly', a: ['había volado'], p: 'yo', en: 'I had never flown before that trip to Miami.', why: 'Experience up to a point in the past: pluscuamperfecto, había volado.' },
    { c: 'past-pluscuam', s: 'Mis{my|m.pl} padres{parents|m.pl} ya{already} ___ la{the|f} cena{dinner|f} cuando{when} llegamos{we arrived}.', base: 'preparar', gloss: 'to make, prepare', a: ['habían preparado'], p: 'ellos', en: 'My parents had already made dinner when we arrived.', why: 'Making dinner came before we arrived. Ellos is habían plus the participle: habían preparado.' },
    { c: 'past-pluscuam', s: 'Me{me} dijiste{you told} que{that} ___ la{the|f} película{film|f}, pero{but} no{not} sabías{you knew} el{the|m} final{ending|m}.', base: 'ver', hint: 'tú', gloss: 'to see', a: ['habías visto'], p: 'tú', en: 'You told me you had seen the film, but you didn’t know the ending.', why: 'Reported speech about something earlier: tú is habías plus visto, the irregular participle of ver.' },
    { c: 'past-pluscuam', s: 'Cuando{when} entré{I went in}, vi{I saw} que{that} alguien{someone} ___ la{the|f} ventana{window|f}.', base: 'romper', gloss: 'to break', a: ['había roto'], p: 'él', en: 'When I went in, I saw that someone had broken the window.', why: 'The window was broken before I went in. Romper has the irregular participle roto: había roto.' },
    { c: 'past-pluscuam', s: 'Antes_de{before} mudarnos{moving} a{to} Bogotá{Bogotá}, nunca{never} ___ en{in} una{a|f} ciudad{city|f} tan{so} grande{big|f}.', base: 'vivir', hint: 'nosotros', gloss: 'to live', a: ['habíamos vivido'], p: 'nosotros', en: 'Before we moved to Bogotá, we had never lived in such a big city.', why: 'Experience up to a point in the past: nosotros is habíamos plus vivido.' },
    { c: 'past-pluscuam', s: 'El{the|m} profesor{teacher|m} nos{us} preguntó{asked} si{whether} ya{already} ___ la{the|f} tarea{homework|f}.', base: 'hacer', hint: 'nosotros', gloss: 'to do', a: ['habíamos hecho'], p: 'nosotros', en: 'The teacher asked us whether we had already done the homework.', why: 'A reported question about an earlier action: habíamos plus hecho, the irregular participle of hacer.' },
  ],
};
