/* Future (futuro): reference tables and quiz sentences.
   Latin American Spanish: the plural “you” is ustedes, which takes the ellos form.
   In tables, [square brackets] mark the part of the form to highlight.
   In sentences, word{gloss} gives the hover translation and ___ is the gap. */

const FUTURE_TENSE = {
  id: 'future', pl: 'Futuro', en: 'Future',
  intro: 'Spanish has two everyday futures. Ir a + infinitivo (voy a comer) is the spoken favourite for plans and things about to happen. The futuro simple (comeré) adds -é, -ás, -á to the whole infinitive and is used for predictions, promises and guesses about the present. In Latin America “you” in the plural is ustedes, which takes the ellos form.',

  groups: [
    {
      id: 'future-ir-a', pl: 'Ir a + verbo', short: 'Ir a', ini: 'A', en: 'Going to', q: 'voy a comer',
      summary: 'The present of ir, then a, then the infinitive: voy a comer. This is the most common way to talk about plans and things about to happen, especially in speech.',
      tables: [
        { title: 'ir in the present + a + infinitive',
          cols: [{ label: 'ir', tint: 'all' }, { label: 'a + infinitive', tint: 'all' }],
          rows: [
            { who: 'yo', cells: ['[voy]', 'a comer'] },
            { who: 'tú', cells: ['[vas]', 'a comer'] },
            { who: 'él / ella / usted', cells: ['[va]', 'a comer'] },
            { who: 'nosotros', cells: ['[vamos]', 'a comer'] },
            { who: 'ellos / ellas / ustedes', cells: ['[van]', 'a comer'] },
          ] },
        { title: 'Where the pronoun goes',
          cols: [{ label: 'Before ir', tint: 'all' }, { label: 'Attached to the infinitive', tint: 'all' }],
          rows: [
            { who: 'levantarse', cells: ['[me] voy a levantar', 'voy a levantar[me]'] },
            { who: 'comprarlo', cells: ['[lo] voy a comprar', 'voy a comprar[lo]'] },
            { who: 'llamarte', cells: ['[te] voy a llamar', 'voy a llamar[te]'] },
          ] },
        { title: 'Signal words for the near future',
          cols: [{ label: 'Example', tint: 'all' }, { label: 'English', tint: 'all' }],
          rows: [
            { who: 'mañana', cells: ['Mañana voy a trabajar desde casa.', 'Tomorrow I am going to work from home.'] },
            { who: 'esta tarde', cells: ['Esta tarde vamos a ir al cine.', 'This afternoon we are going to the cinema.'] },
            { who: 'este fin de semana', cells: ['Este fin de semana va a llover.', 'This weekend it is going to rain.'] },
            { who: 'la próxima semana', cells: ['La próxima semana van a venir mis padres.', 'Next week my parents are coming.'] },
            { who: 'dentro de una hora', cells: ['Dentro de una hora va a salir el tren.', 'The train is leaving in an hour.'] },
            { who: 'luego, pronto', cells: ['Luego te voy a llamar.', 'I will call you later.'] },
          ] },
      ],
      rules: [
        { t: 'Plans and intentions', ex: 'Este verano vamos a viajar a Perú.', en: 'This summer we are going to travel to Peru.' },
        { t: 'Something about to happen, with evidence now', ex: 'Mira el cielo, va a llover.', en: 'Look at the sky, it is going to rain.' },
        { t: 'Reflexive and object pronouns go before ir or attach to the infinitive', ex: 'Me voy a bañar. Voy a bañarme.', en: 'I am going to have a shower.' },
        { t: 'The plain present also works for fixed plans, as in English', ex: 'Mañana tengo una reunión.', en: 'Tomorrow I have a meeting.' },
      ],
      watch: [
        'Do not drop the a: “voy comer” is wrong. Voy a comer.',
        'Vamos a + infinitive can also mean “let’s”: ¡Vamos a bailar!',
        'Va and vamos have no accent, and va has no h. Compare ha comido (has eaten) with va a comer (is going to eat).',
        'Ustedes takes van: ¿Ustedes van a venir?',
      ],
    },
    {
      id: 'future-reg', pl: 'Futuro regular', short: 'Regular', ini: 'R', en: 'Simple future, regular', q: 'hablar → hablaré',
      summary: 'The futuro simple adds one set of endings to the whole infinitive, for all three conjugations: -é, -ás, -á, -emos, -án. It is used for predictions, promises and the more distant or less certain future.',
      tables: [
        { title: 'hablar, comer, vivir: one set of endings',
          cols: [{ label: '-ar', tint: 'all' }, { label: '-er', tint: 'all' }, { label: '-ir', tint: 'all' }],
          rows: [
            { who: 'yo', cells: ['hablar[é]', 'comer[é]', 'vivir[é]'] },
            { who: 'tú', cells: ['hablar[ás]', 'comer[ás]', 'vivir[ás]'] },
            { who: 'él / ella / usted', cells: ['hablar[á]', 'comer[á]', 'vivir[á]'] },
            { who: 'nosotros', cells: ['hablar[emos]', 'comer[emos]', 'vivir[emos]'] },
            { who: 'ellos / ellas / ustedes', cells: ['hablar[án]', 'comer[án]', 'vivir[án]'] },
          ] },
        { title: 'Regular even though the present is not',
          cols: [{ label: 'present', tint: 'all' }, { label: 'futuro', tint: 'all' }],
          rows: [
            { who: 'ser', cells: ['soy', 'ser[é]'] },
            { who: 'ir', cells: ['voy', 'ir[é]'] },
            { who: 'estar', cells: ['estoy', 'estar[é]'] },
            { who: 'volver', cells: ['vuelvo', 'volver[é]'] },
            { who: 'empezar', cells: ['empiezo', 'empezar[é]'] },
            { who: 'dormir', cells: ['duermo', 'dormir[é]'] },
          ] },
        { title: 'Signal words',
          cols: [{ label: 'Example', tint: 'all' }, { label: 'English', tint: 'all' }],
          rows: [
            { who: 'el próximo año', cells: ['El próximo año viviré en Lima.', 'Next year I will live in Lima.'] },
            { who: 'dentro de diez años', cells: ['Dentro de diez años seremos ricos.', 'In ten years we will be rich.'] },
            { who: 'algún día', cells: ['Algún día visitaré Japón.', 'One day I will visit Japan.'] },
            { who: 'en el futuro', cells: ['En el futuro trabajaremos menos.', 'In the future we will work less.'] },
            { who: 'seguro que', cells: ['Seguro que llegará tarde.', 'He will be late for sure.'] },
          ] },
      ],
      rules: [
        { t: 'Predictions and expectations', ex: 'Mañana lloverá en el norte.', en: 'Tomorrow it will rain in the north.' },
        { t: 'Promises', ex: 'Te llamaré esta noche.', en: 'I will call you tonight.' },
        { t: 'The endings go on the whole infinitive, including the -ar, -er or -ir', ex: 'Viviremos cerca del mar.', en: 'We will live near the sea.' },
        { t: 'Every form except nosotros has an accent', ex: 'Comerás, comerá, comerán.', en: 'You will eat, he will eat, they will eat.' },
      ],
      watch: [
        'Do not cut the infinitive: comeré, not “comé”; viviré, not “vivé”.',
        'Nosotros is the only form without an accent: hablaremos.',
        'Ser and ir are regular here: seré, iré. Their irregularity belongs to the past tenses.',
        'After cuando with a future meaning Spanish uses the subjunctive: cuando llegue, te llamaré, never “cuando llegaré”.',
        'Ustedes takes the ellos form, -án: ustedes hablarán, ustedes comerán.',
      ],
    },
    {
      id: 'future-irr', pl: 'Futuro irregular', short: 'Irreg.', ini: 'I', en: 'Simple future, irregular', q: 'tener → tendré, hacer → haré',
      summary: 'Twelve common verbs shorten their infinitive before the same endings: tendr-, podr-, har-, dir-. The endings never change, only the stem does.',
      tables: [
        { title: 'tener, hacer, decir: short stem, same endings',
          cols: [{ label: 'tener', tint: 'all' }, { label: 'hacer', tint: 'all' }, { label: 'decir', tint: 'all' }],
          rows: [
            { who: 'yo', cells: ['[tendr]é', '[har]é', '[dir]é'] },
            { who: 'tú', cells: ['[tendr]ás', '[har]ás', '[dir]ás'] },
            { who: 'él / ella / usted', cells: ['[tendr]á', '[har]á', '[dir]á'] },
            { who: 'nosotros', cells: ['[tendr]emos', '[har]emos', '[dir]emos'] },
            { who: 'ellos / ellas / ustedes', cells: ['[tendr]án', '[har]án', '[dir]án'] },
          ] },
        { title: 'The twelve stems in three patterns',
          cols: [{ label: 'stem', tint: 'all' }, { label: 'yo', tint: 'all' }, { label: 'ellos', tint: 'all' }],
          rows: [
            { who: 'drop the e: poder', cells: ['podr-', '[podr]é', '[podr]án'] },
            { who: 'saber', cells: ['sabr-', '[sabr]é', '[sabr]án'] },
            { who: 'querer', cells: ['querr-', '[querr]é', '[querr]án'] },
            { who: 'haber', cells: ['habr-', '[habr]é', '[habr]án'] },
            { who: 'caber', cells: ['cabr-', '[cabr]é', '[cabr]án'] },
            { who: 'vowel becomes d: tener', cells: ['tendr-', '[tendr]é', '[tendr]án'] },
            { who: 'poner', cells: ['pondr-', '[pondr]é', '[pondr]án'] },
            { who: 'salir', cells: ['saldr-', '[saldr]é', '[saldr]án'] },
            { who: 'venir', cells: ['vendr-', '[vendr]é', '[vendr]án'] },
            { who: 'valer', cells: ['valdr-', '[valdr]é', '[valdr]án'] },
            { who: 'shortened: hacer', cells: ['har-', '[har]é', '[har]án'] },
            { who: 'decir', cells: ['dir-', '[dir]é', '[dir]án'] },
          ] },
      ],
      rules: [
        { t: 'Poder, saber, querer, haber and caber drop the e of the infinitive', ex: 'No podré ir mañana.', en: 'I will not be able to go tomorrow.' },
        { t: 'Tener, poner, salir, venir and valer replace the vowel with d', ex: 'Tendremos tiempo el domingo.', en: 'We will have time on Sunday.' },
        { t: 'Hacer and decir shrink to har- and dir-', ex: 'Te diré la verdad.', en: 'I will tell you the truth.' },
        { t: 'Compounds follow the base verb: mantener, suponer, deshacer', ex: 'Supongo que mantendrá su promesa.', en: 'I suppose he will keep his promise.' },
        { t: 'Hay in the future is habrá, one form for singular and plural', ex: 'Mañana habrá una fiesta.', en: 'Tomorrow there will be a party.' },
      ],
      watch: [
        'Querer doubles the r: querré, querrá. Do not write “quereré”.',
        'The endings stay the same: tendré, tendrás, tendrá. Only the stem is short.',
        'Ser and ir look like candidates but are regular in the future: seré, iré.',
        'Habrá never changes: habrá un problema, habrá problemas.',
        'Ustedes takes the ellos form: ustedes tendrán, ustedes harán.',
      ],
    },
    {
      id: 'future-prob', pl: 'Probabilidad', short: 'Probab.', ini: 'P', en: 'Guessing and future perfect', q: 'Serán las tres. Habrá salido.',
      summary: 'The futuro also expresses a guess about the present: ¿Dónde estará Juan? means I wonder where Juan is. The futuro perfecto (habré + participle) says what will have happened by a point in the future, or guesses about the recent past: habrá salido ya.',
      tables: [
        { title: 'The future as a guess',
          cols: [{ label: 'Spanish', tint: 'all' }, { label: 'English', tint: 'all' }],
          rows: [
            { who: 'about the time', cells: ['[Serán] las tres.', 'It must be about three.'] },
            { who: 'about a person', cells: ['[Tendrá] unos cuarenta años.', 'He must be about forty.'] },
            { who: 'a question', cells: ['¿Dónde [estarán] mis llaves?', 'Where can my keys be?'] },
            { who: 'about the recent past', cells: ['[Habrá perdido] el autobús.', 'She must have missed the bus.'] },
          ] },
        { title: 'futuro perfecto: habré + participle',
          cols: [{ label: 'haber', tint: 'all' }, { label: 'participle', tint: 'all' }],
          rows: [
            { who: 'yo', cells: ['[habré]', 'terminado, comido, salido'] },
            { who: 'tú', cells: ['[habrás]', 'terminado, comido, salido'] },
            { who: 'él / ella / usted', cells: ['[habrá]', 'terminado, comido, salido'] },
            { who: 'nosotros', cells: ['[habremos]', 'terminado, comido, salido'] },
            { who: 'ellos / ellas / ustedes', cells: ['[habrán]', 'terminado, comido, salido'] },
          ] },
        IRREGULAR_PARTICIPLES,   // from data-past.js, which loads first
      ],
      rules: [
        { t: 'A guess or estimate about now: the futuro simple', ex: 'Serán las diez.', en: 'It must be about ten.' },
        { t: 'A guess about what has already happened: the futuro perfecto', ex: 'No contesta. Se habrá dormido.', en: 'She is not answering. She must have fallen asleep.' },
        { t: 'Something that will be finished by a point in the future, often with para or antes de', ex: 'Para el viernes habremos terminado el trabajo.', en: 'By Friday we will have finished the work.' },
        { t: 'Questions in the futuro mean “I wonder”', ex: '¿Quién será a estas horas?', en: 'Who can that be at this hour?' },
      ],
      watch: [
        'Context decides: tendrá veinte años is a guess about now, not a prediction, when you are looking at someone.',
        'The participle never changes, and the irregular ones are the same as in the perfecto: habrá hecho, habrá dicho.',
        'English adds “must” or “probably”; Spanish adds nothing, the tense does the job.',
      ],
    },
    {
      id: 'future-choice', pl: 'Ir a o futuro', short: '¿Cuál?', ini: '?', en: 'Going to or will', q: 'voy a comer / comeré',
      summary: 'Both forms talk about the future, and often either works. Ir a is the natural choice for plans, decisions already made and things about to happen; the futuro simple suits predictions, promises, the distant future and formal or written Spanish.',
      tables: [
        { title: 'Which one?',
          cols: [{ label: 'ir a + infinitive', tint: 'all' }, { label: 'futuro simple', tint: 'all' }],
          rows: [
            { who: 'Typical use', cells: ['plan, intention, decision already made, something about to happen', 'prediction, promise, guess about now, distant future'] },
            { who: 'Example', cells: ['Esta tarde voy a estudiar.', 'Algún día seré médico.'] },
            { who: 'English', cells: ['This afternoon I am going to study.', 'One day I will be a doctor.'] },
            { who: 'Register', cells: ['spoken, informal', 'written, formal, also spoken'] },
          ] },
        { title: 'Often both are fine',
          cols: [{ label: 'ir a', tint: 'all' }, { label: 'futuro', tint: 'all' }],
          rows: [
            { who: 'prediction', cells: ['Mañana va a llover.', 'Mañana lloverá.'] },
            { who: 'plan', cells: ['Nos vamos a mudar.', 'Nos mudaremos.'] },
            { who: 'promise', cells: ['Te lo voy a devolver.', 'Te lo devolveré.'] },
            { who: 'guess about now', cells: ['—', 'Serán las cinco.'] },
            { who: 'evidence in front of you', cells: ['¡Se va a caer!', '—'] },
          ] },
      ],
      rules: [
        { t: 'A plan or decision already made: ir a', ex: 'Este año voy a aprender a manejar.', en: 'This year I am going to learn to drive.' },
        { t: 'Evidence you can see now: ir a', ex: 'Cuidado, el vaso se va a caer.', en: 'Careful, the glass is going to fall.' },
        { t: 'A promise: futuro simple, or ir a in relaxed speech', ex: 'No te preocupes, yo lo haré.', en: 'Don’t worry, I will do it.' },
        { t: 'The distant or uncertain future and formal predictions: futuro simple', ex: 'En 2050 la gente vivirá cien años.', en: 'In 2050 people will live to a hundred.' },
        { t: 'A guess about the present: only the futuro simple', ex: 'Serán las cinco.', en: 'It must be about five.' },
      ],
      watch: [
        'In speech ir a wins for anything already planned. The futuro simple can sound formal, or like a prophecy.',
        'Van a ser las cinco is not a guess: it means the clock is about to strike five.',
        'Voy a ir is fine; iré is a shorter option with the same meaning.',
      ],
    },
  ],

  sentences: [
    // Ir a + infinitivo
    { c: 'future-ir-a', s: 'Mañana{tomorrow} ___ a{(personal a)} mis{my|m.pl} abuelos{grandparents|m.pl}.', base: 'visitar', hint: 'yo', gloss: 'to visit', a: ['voy a visitar'], p: 'yo', en: 'Tomorrow I am going to visit my grandparents.', why: 'A plan for tomorrow: voy a plus the infinitive.' },
    { c: 'future-ir-a', s: 'Esta{this|f} noche{night|f} ___ en{at} un{a|m} restaurante{restaurant|m} italiano{Italian|m}.', base: 'cenar', hint: 'nosotros', gloss: 'to have dinner', a: ['vamos a cenar'], p: 'nosotros', en: 'Tonight we are going to have dinner at an Italian restaurant.', why: 'A plan for tonight: vamos a cenar. Vamos has no accent.' },
    { c: 'future-ir-a', s: '¿Qué{what} ___ este{this|m} fin_de_semana{weekend|m}?', base: 'hacer', hint: 'tú', gloss: 'to do', a: ['vas a hacer'], p: 'tú', en: 'What are you going to do this weekend?', why: 'Asking about plans: vas a hacer.' },
    { c: 'future-ir-a', s: 'Mira{look} esas{those|f.pl} nubes{cloud|f.pl}, ___.', base: 'llover', hint: 'it', gloss: 'to rain', a: ['va a llover'], p: 'él', en: 'Look at those clouds, it is going to rain.', why: 'Evidence now for something about to happen: va a llover.' },
    { c: 'future-ir-a', s: 'Mis{my|m.pl} padres{parents|m.pl} ___ una{a|f} casa{house|f} en{in} el{the|m} pueblo{village|m}.', base: 'comprar', gloss: 'to buy', a: ['van a comprar'], p: 'ellos', en: 'My parents are going to buy a house in the village.', why: 'A plan already made: van a comprar.' },
    { c: 'future-ir-a', s: '¿Ustedes{you (plural)} ___ a{to} la{the|f} fiesta{party|f} de{of} Ana{Ana}?', base: 'ir', gloss: 'to go', a: ['van a ir'], p: 'ellos', en: 'Are you going to go to Ana’s party?', why: 'Ir a ir is fine and common: van a ir. Ustedes takes the ellos form, van.' },
    { c: 'future-ir-a', s: 'La_próxima_semana{next week|f} mi{my|f} hermana{sister|f} ___ a{to} trabajar{work} en{in} Londres{London}.', base: 'empezar', gloss: 'to start', a: ['va a empezar'], p: 'él', en: 'Next week my sister is going to start working in London.', why: 'A fixed plan in the near future: va a empezar. The second a belongs to empezar a + infinitive.' },
    { c: 'future-ir-a', s: '___ temprano{early} porque{because} tengo{I have} un{a|m} examen{exam|m}.', base: 'acostarse', hint: 'yo', gloss: 'to go to bed', a: ['Me voy a acostar', 'Voy a acostarme'], p: 'yo', en: 'I am going to go to bed early because I have an exam.', why: 'The reflexive pronoun goes before voy or attaches to the infinitive: me voy a acostar, voy a acostarme.' },
    { c: 'future-ir-a', s: 'Dentro_de{in} una{an|f} hora{hour|f} ___ el{the|m} tren{train|m}.', base: 'salir', gloss: 'to leave', a: ['va a salir'], p: 'él', en: 'The train is going to leave in an hour.', why: 'Something about to happen at a set time: va a salir.' },
    { c: 'future-ir-a', s: 'Este{this|m} verano{summer|m} ustedes{you (plural)} ___ inglés{English|m} en{in} Canadá{Canada}.', base: 'estudiar', gloss: 'to study', a: ['van a estudiar'], p: 'ellos', en: 'This summer you are going to study English in Canada.', why: 'A plan for the summer. Ustedes takes the ellos form: van a estudiar.' },
    { c: 'future-ir-a', s: 'No{not} ___ más{any more} café{coffee|m}, me{me} pone{makes} nervioso{nervous|m}.', base: 'tomar', hint: 'yo', gloss: 'to have (food, drink)', a: ['voy a tomar'], p: 'yo', en: 'I am not going to have any more coffee, it makes me nervous.', why: 'An intention or decision: no voy a tomar.' },
    { c: 'future-ir-a', s: 'Luego{later} ___ a{(personal a)} Pablo{Pablo} para{to} invitarlo{invite him}.', base: 'llamar', hint: 'nosotros', gloss: 'to call', a: ['vamos a llamar'], p: 'nosotros', en: 'Later we are going to call Pablo to invite him.', why: 'Luego points to the near future: vamos a llamar.' },
    { c: 'future-ir-a', s: '¿A_qué_hora{what time} ___ los{the|m.pl} invitados{guest|m.pl}?', base: 'llegar', gloss: 'to arrive', a: ['van a llegar'], p: 'ellos', en: 'What time are the guests going to arrive?', why: 'Los invitados is ellos: van a llegar.' },
    { c: 'future-ir-a', s: 'Mi{my|m} hermano{brother|m} ___ mañana{tomorrow} muy{very} temprano{early}.', base: 'levantarse', gloss: 'to get up', a: ['se va a levantar', 'va a levantarse'], p: 'él', en: 'My brother is going to get up very early tomorrow.', why: 'Both positions of the pronoun are fine: se va a levantar, va a levantarse.' },
    { c: 'future-ir-a', s: '¡Cuidado{careful}, ___!', base: 'caerse', hint: 'tú', gloss: 'to fall', a: ['te vas a caer', 'vas a caerte'], p: 'tú', en: 'Careful, you are going to fall!', why: 'Something about to happen right now: te vas a caer.' },
    { c: 'future-ir-a', s: 'Esta{this|f} tarde{afternoon|f} ___ al{to the|m} supermercado{supermarket|m}.', base: 'ir', hint: 'yo', gloss: 'to go', a: ['voy a ir'], p: 'yo', en: 'This afternoon I am going to go to the supermarket.', why: 'A plan for this afternoon: voy a plus the infinitive. Voy a ir is perfectly normal Spanish.' },
    { c: 'future-ir-a', s: '¿Tú{you} ___ a{(personal a)} tus{your|m.pl} papás{parents|m.pl} en{at} Navidad{Christmas|f}?', base: 'ver', gloss: 'to see', a: ['vas a ver'], p: 'tú', en: 'Are you going to see your parents at Christmas?', why: 'Asking about plans: tú is vas a plus the infinitive.' },
    { c: 'future-ir-a', s: 'Mis{my|m.pl} amigos{friends|m.pl} ___ una{a|f} fiesta{party|f} sorpresa{surprise|f} para{for} Laura{Laura}.', base: 'organizar', gloss: 'to organise', a: ['van a organizar'], p: 'ellos', en: 'My friends are going to throw a surprise party for Laura.', why: 'A plan already under way: ellos is van a plus the infinitive.' },
    { c: 'future-ir-a', s: 'Con{with} este{this|m} tráfico{traffic|m}, ___ tarde{late} a{to} la{the|f} reunión{meeting|f}.', base: 'llegar', hint: 'nosotros', gloss: 'to arrive', a: ['vamos a llegar'], p: 'nosotros', en: 'With this traffic, we are going to be late for the meeting.', why: 'A prediction from what you can see right now: vamos a llegar.' },
    { c: 'future-ir-a', s: 'El{on the|m} sábado{Saturday|m} mi{my|f} hermana{sister|f} ___ treinta{thirty} años{year|m.pl}.', base: 'cumplir', gloss: 'to turn (an age)', a: ['va a cumplir'], p: 'él', en: 'On Saturday my sister is going to turn thirty.', why: 'Él and ella take va a plus the infinitive: va a cumplir.' },
    { c: 'future-ir-a', s: 'Mañana{tomorrow} ___ el{the|m} carro{car|m} al{to the|m} taller{garage|m}.', base: 'llevar', hint: 'yo', gloss: 'to take', a: ['voy a llevar'], p: 'yo', en: 'Tomorrow I am going to take the car to the garage.', why: 'A plan for tomorrow: voy a llevar.' },
    { c: 'future-ir-a', s: 'Esta{this|f} tarde{afternoon|f} ___ el{the|m} apartamento{apartment|m} antes_de_que{before} lleguen{arrive} mis{my|m.pl} suegros{in-laws|m.pl}.', base: 'limpiar', hint: 'yo', gloss: 'to clean', a: ['voy a limpiar'], p: 'yo', en: 'This afternoon I am going to clean the apartment before my in-laws arrive.', why: 'A plan for this afternoon: voy a limpiar.' },
    { c: 'future-ir-a', s: '¿Tú{you} ___ con{with} nosotros{us} al{to the|m} cine{cinema|m} o{or} te{yourself} quedas{stay} en{at} casa{home|f}?', base: 'venir', gloss: 'to come', a: ['vas a venir'], p: 'tú', en: 'Are you going to come to the cinema with us or are you staying at home?', why: 'Asking about plans: tú is vas a plus the infinitive, vas a venir.' },
    { c: 'future-ir-a', s: 'Mi{my|m} papá{dad|m} ___ el_próximo_año{next year|m}, después_de{after} treinta{thirty} años{year|m.pl} en{at} el{the|m} banco{bank|m}.', base: 'jubilarse', gloss: 'to retire', a: ['se va a jubilar', 'va a jubilarse'], p: 'él', en: 'My dad is going to retire next year, after thirty years at the bank.', why: 'A plan for next year: se va a jubilar, or with the pronoun attached, va a jubilarse.' },
    { c: 'future-ir-a', s: 'Este{this|m} sábado{Saturday|m} ___ el{the|m} cumpleaños{birthday|m} de{of} mi{my|f} abuela{grandmother|f} en{at} una{a|f} finca{country house|f}.', base: 'celebrar', hint: 'nosotros', gloss: 'to celebrate', a: ['vamos a celebrar'], p: 'nosotros', en: 'This Saturday we are going to celebrate my grandmother’s birthday at a country house.', why: 'A plan for Saturday: vamos a celebrar. Vamos has no accent.' },
    { c: 'future-ir-a', s: 'Los{the|m.pl} vecinos{neighbour|m.pl} ___ la{the|f} cocina{kitchen|f} este{this|m} mes{month|m}.', base: 'remodelar', gloss: 'to renovate', a: ['van a remodelar'], p: 'ellos', en: 'The neighbours are going to renovate the kitchen this month.', why: 'Los vecinos is ellos: van a remodelar.' },
    { c: 'future-ir-a', s: '¿Ustedes{you (plural)} ___ en{by} bus{bus|m} o{or} en{by} taxi{taxi|m}?', base: 'regresar', gloss: 'to go back', a: ['van a regresar'], p: 'ellos', en: 'Are you going to go back by bus or by taxi?', why: 'Asking about plans. Ustedes takes the ellos form: van a regresar.' },
    { c: 'future-ir-a', s: 'El{the|m} bebé{baby|m} ya{already} cierra{closes} los{the|m.pl} ojos{eye|m.pl}; ___.', base: 'dormirse', gloss: 'to fall asleep', a: ['se va a dormir', 'va a dormirse'], p: 'él', en: 'The baby is already closing his eyes; he is going to fall asleep.', why: 'Evidence right now for something about to happen: se va a dormir, va a dormirse.' },
    { c: 'future-ir-a', s: 'Ya{already} lo{it|m} decidí{I decided}: no{not} ___ más{any more} plata{money|f} en{on} ropa{clothes|f}.', base: 'gastar', hint: 'yo', gloss: 'to spend', a: ['voy a gastar'], p: 'yo', en: 'I have decided: I am not going to spend any more money on clothes.', why: 'A decision already made: no voy a gastar.' },
    { c: 'future-ir-a', s: 'Si{if} sales{you go out} sin{without} chaqueta{jacket|f}, ___.', base: 'resfriarse', hint: 'tú', gloss: 'to catch a cold', a: ['te vas a resfriar', 'vas a resfriarte'], p: 'tú', en: 'If you go out without a jacket, you are going to catch a cold.', why: 'A warning about what will happen: te vas a resfriar, or vas a resfriarte.' },
    { c: 'future-ir-a', s: '¡Corre{run}, que{or} ___ el{the|m} bus{bus|m}!', base: 'perder', hint: 'nosotros', gloss: 'to miss', a: ['vamos a perder'], p: 'nosotros', en: 'Run, or we are going to miss the bus!', why: 'Something about to happen unless you hurry: vamos a perder.' },
    { c: 'future-ir-a', s: 'Mis{my|m.pl} tíos{aunt and uncle|m.pl} ___ a{to} Medellín{Medellín} en{in} diciembre{December}.', base: 'mudarse', gloss: 'to move (house)', a: ['se van a mudar', 'van a mudarse'], p: 'ellos', en: 'My aunt and uncle are going to move to Medellín in December.', why: 'A plan already made: se van a mudar, or van a mudarse.' },
    { c: 'future-ir-a', s: 'Hace{it is} mucho{very} frío{cold|m} y{and} el{the|m} cielo{sky|m} está{is} gris{grey}; ___.', base: 'nevar', hint: 'it', gloss: 'to snow', a: ['va a nevar'], p: 'él', en: 'It is very cold and the sky is grey; it is going to snow.', why: 'Evidence you can see now: va a nevar.' },
    { c: 'future-ir-a', s: 'Para{for} la{the|f} cena{dinner|f} ___ una{a|f} sopa{soup|f} de{of} pollo{chicken|m}.', base: 'cocinar', hint: 'yo', gloss: 'to cook', a: ['voy a cocinar'], p: 'yo', en: 'For dinner I am going to cook a chicken soup.', why: 'A plan for tonight: voy a cocinar.' },
    { c: 'future-ir-a', s: '¿Cuándo{when} le{her} ___ a{to} tu{your} mamá{mom|f} lo{the business} del{of the|m} accidente{accident|m}?', base: 'contar', hint: 'tú', gloss: 'to tell', a: ['vas a contar'], p: 'tú', en: 'When are you going to tell your mom about the accident?', why: 'Asking about plans: vas a contar. Le stays before vas.' },
    { c: 'future-ir-a', s: 'Mañana{tomorrow} ustedes{you (plural)} ___ el{the|m} proyecto{project|m} delante_de{in front of} todo{the whole|m} el{the|m} equipo{team|m}.', base: 'presentar', gloss: 'to present', a: ['van a presentar'], p: 'ellos', en: 'Tomorrow you are going to present the project in front of the whole team.', why: 'A fixed plan for tomorrow. Ustedes takes the ellos form: van a presentar.' },
    { c: 'future-ir-a', s: 'Mi{my|f} prima{cousin|f} ___ con{with} su{her} novio{boyfriend|m} en{in} junio{June}.', base: 'casarse', gloss: 'to get married', a: ['se va a casar', 'va a casarse'], p: 'él', en: 'My cousin is going to marry her boyfriend in June.', why: 'A plan already made: se va a casar, or va a casarse.' },
    { c: 'future-ir-a', s: 'Esta{this|f} noche{night|f} les{you (plural)} ___ las{the|f.pl} fotos{photo|f.pl} del{of the|m} viaje{trip|m}.', base: 'mostrar', hint: 'nosotros', gloss: 'to show', a: ['vamos a mostrar'], p: 'nosotros', en: 'Tonight we are going to show you the photos from the trip.', why: 'A plan for tonight: vamos a mostrar. The stem change of the present (muestro) does not touch the infinitive.' },
    { c: 'future-ir-a', s: 'Estoy{I am} muy{very} cansada{tired|f}, ___ un{a|m} rato{while|m}.', base: 'descansar', hint: 'yo', gloss: 'to rest', a: ['voy a descansar'], p: 'yo', en: 'I am very tired, I am going to rest for a while.', why: 'A decision for right now: voy a descansar.' },
    { c: 'future-ir-a', s: '¿Tú{you} ___ la{the|f} luz{light|f} o{or} la{it|f} apago{switch off} yo{I}?', base: 'apagar', gloss: 'to switch off', a: ['vas a apagar'], p: 'tú', en: 'Are you going to switch off the light or shall I?', why: 'Asking about what someone intends to do: vas a apagar.' },
    { c: 'future-ir-a', s: 'Los{the|m.pl} niños{children|m.pl} ___ en{in} el{the|m} parque{park|m} toda{all|f} la{the|f} tarde{afternoon|f}.', base: 'jugar', gloss: 'to play', a: ['van a jugar'], p: 'ellos', en: 'The children are going to play in the park all afternoon.', why: 'Los niños is ellos: van a jugar.' },
    { c: 'future-ir-a', s: 'Mi{my|m} jefe{boss|m} me{me} ___ el{the|m} sueldo{salary|m} en{in} enero{January}.', base: 'subir', gloss: 'to raise', a: ['va a subir'], p: 'él', en: 'My boss is going to raise my salary in January.', why: 'Él takes va a plus the infinitive: va a subir.' },
    { c: 'future-ir-a', s: 'Mañana{tomorrow} ___ la{the|f} sala{living room|f} de{in} azul{blue}.', base: 'pintar', hint: 'nosotros', gloss: 'to paint', a: ['vamos a pintar'], p: 'nosotros', en: 'Tomorrow we are going to paint the living room blue.', why: 'A plan for tomorrow: vamos a pintar.' },

    // Futuro regular
    { c: 'future-reg', s: 'Mañana{tomorrow} te{you} ___ por{in} la{the|f} tarde{afternoon|f}.', base: 'llamar', hint: 'yo', gloss: 'to call', a: ['llamaré'], p: 'yo', en: 'Tomorrow I will call you in the afternoon.', why: 'A promise: futuro simple. Yo takes -é on the whole infinitive: llamaré.' },
    { c: 'future-reg', s: 'El_próximo_año{next year|m} mis{my|m.pl} padres{parents|m.pl} ___ a{to} Perú{Peru}.', base: 'viajar', gloss: 'to travel', a: ['viajarán'], p: 'ellos', en: 'Next year my parents will travel to Peru.', why: 'Ellos takes -án: viajarán, with an accent.' },
    { c: 'future-reg', s: '¿Dónde{where} ___ dentro_de{in} diez{ten} años{year|m.pl}?', base: 'vivir', hint: 'tú', gloss: 'to live', a: ['vivirás'], p: 'tú', en: 'Where will you live in ten years?', why: 'The distant future: futuro simple. Tú takes -ás: vivirás.' },
    { c: 'future-reg', s: 'Nosotros{we} ___ la{the|f} cena{dinner|f} esta{this|f} noche{night|f}.', base: 'preparar', gloss: 'to prepare', a: ['prepararemos'], p: 'nosotros', en: 'We will prepare dinner tonight.', why: 'Nosotros is the only form without an accent: prepararemos.' },
    { c: 'future-reg', s: 'Este{this|m} invierno{winter|m} ___ mucho{a lot} en{in} la{the|f} montaña{mountains|f}.', base: 'nevar', hint: 'it', gloss: 'to snow', a: ['nevará'], p: 'él', en: 'This winter it will snow a lot in the mountains.', why: 'A prediction: futuro simple. Nevar is regular here, even though it changes stem in the present (nieva).' },
    { c: 'future-reg', s: 'Algún_día{one day|m} ___ una{a|f} casa{house|f} junto_al{by the|m} mar{sea|m}.', base: 'comprar', hint: 'yo', gloss: 'to buy', a: ['compraré'], p: 'yo', en: 'One day I will buy a house by the sea.', why: 'Algún día is a distant, uncertain future: compraré.' },
    { c: 'future-reg', s: '¿Ustedes{you (plural)} ___ a{to} la{the|f} boda{wedding|f} de{of} Carmen{Carmen}?', base: 'ir', gloss: 'to go', a: ['irán'], p: 'ellos', en: 'Will you go to Carmen’s wedding?', why: 'Ir is regular in the futuro: ir plus -án. Ustedes takes the ellos form: irán.' },
    { c: 'future-reg', s: 'Los{the|m.pl} niños{children|m.pl} ___ mucho{a lot} en{at} el{the|m} campamento{camp|m}.', base: 'aprender', gloss: 'to learn', a: ['aprenderán'], p: 'ellos', en: 'The children will learn a lot at the camp.', why: 'Ellos takes -án on the whole infinitive: aprenderán.' },
    { c: 'future-reg', s: 'Te{you} lo{it|m} ___ mañana{tomorrow}, lo_prometo{I promise}.', base: 'explicar', hint: 'yo', gloss: 'to explain', a: ['explicaré'], p: 'yo', en: 'I will explain it to you tomorrow, I promise.', why: 'A promise: futuro simple, explicaré.' },
    { c: 'future-reg', s: 'Mi{my|f} hija{daughter|f} ___ dieciocho{eighteen} años{year|m.pl} en{in} mayo{May}.', base: 'cumplir', gloss: 'to turn (an age)', a: ['cumplirá'], p: 'él', en: 'My daughter will turn eighteen in May.', why: 'Ella takes -á: cumplirá.' },
    { c: 'future-reg', s: 'Seguro_que{surely} ___ un{a|m} buen{good|m} médico{doctor|m}.', base: 'ser', hint: 'tú', gloss: 'to be', a: ['serás'], p: 'tú', en: 'You will surely be a good doctor.', why: 'Ser is regular in the futuro: serás.' },
    { c: 'future-reg', s: 'El_próximo_año{next year|m} ___ en{in} un{a|m} apartamento{apartment|m} más{more} grande{big|m}.', base: 'vivir', hint: 'nosotros', gloss: 'to live', a: ['viviremos'], p: 'nosotros', en: 'Next year we will live in a bigger apartment.', why: 'Nosotros takes -emos with no accent: viviremos.' },
    { c: 'future-reg', s: '¿Cuándo{when} ___ los{the|m.pl} resultados{result|m.pl} del{of the|m} examen{exam|m}?', base: 'recibir', hint: 'nosotros', gloss: 'to receive', a: ['recibiremos'], p: 'nosotros', en: 'When will we receive the exam results?', why: 'Nosotros: recibiremos, no accent.' },
    { c: 'future-reg', s: 'Estoy{I am} seguro{sure|m} de_que{that} todo{everything|m} ___ bien{well}.', base: 'ir', gloss: 'to go', a: ['irá'], p: 'él', en: 'I am sure everything will go well.', why: 'Ir is regular: irá, with an accent.' },
    { c: 'future-reg', s: 'Ustedes{you (plural)} ___ la{the|f} mesa{table|f} y{and} yo{I} lavaré{will wash} los{the|m.pl} platos{plate|m.pl}.', base: 'levantar', gloss: 'to clear (the table)', a: ['levantarán'], p: 'ellos', en: 'You will clear the table and I will wash the plates.', why: 'Ustedes takes the ellos form, -án: levantarán.' },
    { c: 'future-reg', s: 'El{the|m} concierto{concert|m} ___ a{at} las{the|f.pl} nueve{nine}.', base: 'empezar', gloss: 'to start', a: ['empezará'], p: 'él', en: 'The concert will start at nine.', why: 'Empezar changes its stem in the present, but the futuro is regular: the whole infinitive plus -á, empezará.' },
    { c: 'future-reg', s: 'Nosotros{we} te{you} ___ en{at} el{the|m} aeropuerto{airport|m}.', base: 'esperar', gloss: 'to wait for', a: ['esperaremos'], p: 'nosotros', en: 'We will wait for you at the airport.', why: 'Nosotros takes -emos on the whole infinitive: esperaremos.' },
    { c: 'future-reg', s: '¿Me{me} ___ cuando{when} llegues{you arrive}?', base: 'escribir', hint: 'tú', gloss: 'to write', a: ['escribirás'], p: 'tú', en: 'Will you write to me when you arrive?', why: 'Tú takes -ás on the infinitive: escribirás, with an accent.' },
    { c: 'future-reg', s: 'Algún_día{one day|m} mis{my|m.pl} hijos{children|m.pl} ___ esta{this|f} historia{story|f}.', base: 'entender', gloss: 'to understand', a: ['entenderán'], p: 'ellos', en: 'One day my children will understand this story.', why: 'Ellos takes -án: entenderán. The stem change of the present (entienden) does not appear in the futuro.' },
    { c: 'future-reg', s: 'Esta{this|f} noche{night|f} ___ temprano{early} porque{because} estoy{I am} cansado{tired|m}.', base: 'dormir', hint: 'yo', gloss: 'to sleep', a: ['dormiré'], p: 'yo', en: 'Tonight I will go to bed early because I am tired.', why: 'Dormir is regular in the futuro: the whole infinitive plus -é, dormiré.' },
    { c: 'future-reg', s: 'Mañana{tomorrow} te{you} ___ las{the|f.pl} fotos{photo|f.pl} por{by} correo{email|m}.', base: 'mandar', hint: 'yo', gloss: 'to send', a: ['mandaré'], p: 'yo', en: 'Tomorrow I will send you the photos by email.', why: 'A promise: yo takes -é on the whole infinitive, mandaré.' },
    { c: 'future-reg', s: 'Si{if} practicas{you practise} todos_los_días{every day}, pronto{soon} ___ el{the|m} piano{piano|m} muy{very} bien{well}.', base: 'tocar', hint: 'tú', gloss: 'to play (an instrument)', a: ['tocarás'], p: 'tú', en: 'If you practise every day, you will soon play the piano very well.', why: 'A result in the future: tú takes -ás, tocarás.' },
    { c: 'future-reg', s: 'El{the|m} museo{museum|m} ___ sus{its|f.pl} puertas{door|f.pl} en{in} marzo{March}.', base: 'abrir', gloss: 'to open', a: ['abrirá'], p: 'él', en: 'The museum will open its doors in March.', why: 'An announcement: futuro simple. Él takes -á: abrirá.' },
    { c: 'future-reg', s: 'El{on the|m} sábado{Saturday|m} ___ con{with} los{the|m.pl} niños{children|m.pl} en{in} el{the|m} lago{lake|m}.', base: 'nadar', hint: 'nosotros', gloss: 'to swim', a: ['nadaremos'], p: 'nosotros', en: 'On Saturday we will swim with the children in the lake.', why: 'Nosotros takes -emos with no accent: nadaremos.' },
    { c: 'future-reg', s: 'Mañana{tomorrow} los{the|m.pl} bancos{bank|m.pl} ___ cerrados{closed|m.pl} por{because of} el{the|m} festivo{public holiday|m}.', base: 'estar', gloss: 'to be', a: ['estarán'], p: 'ellos', en: 'Tomorrow the banks will be closed because of the public holiday.', why: 'Estar is regular in the futuro: estar plus -án, estarán.' },
    { c: 'future-reg', s: 'Ustedes{you (plural)} ___ en{at} el{the|m} hotel{hotel|m} y{and} luego{then} visitarán{you will visit} el{the|m} museo{museum|m}.', base: 'almorzar', gloss: 'to have lunch', a: ['almorzarán'], p: 'ellos', en: 'You will have lunch at the hotel and then visit the museum.', why: 'Ustedes takes the ellos form, -án: almorzarán. The stem change of the present (almuerzan) does not appear.' },
    { c: 'future-reg', s: 'Según{according to} el{the|m} pronóstico{forecast|m}, mañana{tomorrow} ___ toda{all|f} la{the|f} tarde{afternoon|f}.', base: 'llover', hint: 'it', gloss: 'to rain', a: ['lloverá'], p: 'él', en: 'According to the forecast, it will rain all afternoon tomorrow.', why: 'A forecast: futuro simple. Llover keeps the whole infinitive: lloverá.' },
    { c: 'future-reg', s: 'Cuando{when} tenga{I have} tiempo{time|m}, ___ esa{that|f} novela{novel|f}.', base: 'leer', hint: 'yo', gloss: 'to read', a: ['leeré'], p: 'yo', en: 'When I have time, I will read that novel.', why: 'Yo takes -é on the whole infinitive, so the two e meet: leeré.' },
    { c: 'future-reg', s: '¿Me{me} ___ cuando{when} sea{I am} vieja{old|f}?', base: 'cuidar', hint: 'tú', gloss: 'to look after', a: ['cuidarás'], p: 'tú', en: 'Will you look after me when I am old?', why: 'Tú takes -ás: cuidarás, with an accent.' },
    { c: 'future-reg', s: 'En{in} la{the|f} reunión{meeting|f} ___ del{about the|m} presupuesto{budget|m} del{for the|m} próximo{next|m} año{year|m}.', base: 'hablar', hint: 'nosotros', gloss: 'to talk', a: ['hablaremos'], p: 'nosotros', en: 'In the meeting we will talk about next year’s budget.', why: 'Nosotros takes -emos: hablaremos, the only form without an accent.' },
    { c: 'future-reg', s: 'Los{the|m.pl} abuelos{grandparents|m.pl} ___ el{the|m} avión{plane|m} a{at} las{the|f.pl} seis{six}.', base: 'tomar', gloss: 'to take', a: ['tomarán'], p: 'ellos', en: 'The grandparents will take the plane at six.', why: 'Ellos takes -án: tomarán.' },
    { c: 'future-reg', s: 'La{the|f} tienda{shop|f} ___ más{more} temprano{early} el{on|m} domingo{Sunday|m}.', base: 'cerrar', gloss: 'to close', a: ['cerrará'], p: 'él', en: 'The shop will close earlier on Sunday.', why: 'Cerrar changes its stem in the present (cierra), but the futuro is regular: cerrará.' },
    { c: 'future-reg', s: 'Nunca{never} ___ lo_que{what} hiciste{you did} por{for} mí{me}.', base: 'olvidar', hint: 'yo', gloss: 'to forget', a: ['olvidaré'], p: 'yo', en: 'I will never forget what you did for me.', why: 'A promise: futuro simple, olvidaré.' },
    { c: 'future-reg', s: 'Con{with} este{this|m} mapa{map|m} no{not} te{yourself} ___.', base: 'perderse', hint: 'tú', gloss: 'to get lost', a: ['perderás'], p: 'tú', en: 'With this map you won’t get lost.', why: 'Tú takes -ás on the whole infinitive: perderás. Te stays in front of the verb.' },
    { c: 'future-reg', s: '¿Ustedes{you (plural)} ___ la{the|f} casa{house|f} o{or} la{it|f} alquilarán{will rent out}?', base: 'vender', gloss: 'to sell', a: ['venderán'], p: 'ellos', en: 'Will you sell the house or rent it out?', why: 'Ustedes takes the ellos form, -án: venderán.' },
    { c: 'future-reg', s: 'El{the|m} médico{doctor|m} lo{him} ___ mañana{tomorrow} a_primera_hora{first thing}.', base: 'atender', gloss: 'to see (a patient)', a: ['atenderá'], p: 'él', en: 'The doctor will see him first thing tomorrow.', why: 'Atender changes its stem in the present (atiende), but not in the futuro: atenderá.' },
    { c: 'future-reg', s: 'Si{if} ganamos{we win} este{this|m} partido{match|m}, ___ a{to} la{the|f} final{final|f}.', base: 'pasar', hint: 'nosotros', gloss: 'to go through', a: ['pasaremos'], p: 'nosotros', en: 'If we win this match, we will go through to the final.', why: 'A result after si plus the present: futuro simple, pasaremos.' },
    { c: 'future-reg', s: 'Mis{my|m.pl} hermanos{brother|m.pl} ___ la{the|f} casa{house|f} de{of} los{the|m.pl} abuelos{grandparents|m.pl} el_próximo_verano{next summer|m}.', base: 'arreglar', gloss: 'to fix up', a: ['arreglarán'], p: 'ellos', en: 'My brothers will fix up the grandparents’ house next summer.', why: 'Ellos takes -án: arreglarán.' },
    { c: 'future-reg', s: 'No{don’t} te{yourself} preocupes{worry}, ___ las{the|f.pl} plantas{plant|f.pl} mientras{while} estás{you are} de{on} viaje{trip|m}.', base: 'regar', hint: 'yo', gloss: 'to water', a: ['regaré'], p: 'yo', en: 'Don’t worry, I will water the plants while you are away.', why: 'A promise: regaré. The stem change of the present (riego) does not appear in the futuro.' },
    { c: 'future-reg', s: 'Mañana{tomorrow} ___ a{(personal a)} mi{my|f} novia{girlfriend|f}; es{she is} muy{very} simpática{nice|f}.', base: 'conocer', hint: 'tú', gloss: 'to meet', a: ['conocerás'], p: 'tú', en: 'Tomorrow you will meet my girlfriend; she is very nice.', why: 'Conocer is regular in the futuro, with no extra z: conocerás.' },
    { c: 'future-reg', s: 'El{the|m} vuelo{flight|m} ___ con{with} una{an|f} hora{hour|f} de{of} retraso{delay|m}.', base: 'aterrizar', gloss: 'to land', a: ['aterrizará'], p: 'él', en: 'The flight will land an hour late.', why: 'Él takes -á on the whole infinitive: aterrizará.' },

    // Futuro irregular
    { c: 'future-irr', s: 'Mañana{tomorrow} no{not} ___ venir{come} a{to} clase{class|f}.', base: 'poder', hint: 'yo', gloss: 'can, to be able to', a: ['podré'], p: 'yo', en: 'Tomorrow I won’t be able to come to class.', why: 'Poder drops the e: podr- plus -é.' },
    { c: 'future-irr', s: 'El{the|m} jefe{boss|m} nos{us} ___ la{the|f} respuesta{answer|f} el{on|m} lunes{Monday|m}.', base: 'decir', gloss: 'to tell', a: ['dirá'], p: 'él', en: 'The boss will tell us the answer on Monday.', why: 'Decir shrinks to dir-: dirá.' },
    { c: 'future-irr', s: '¿A_qué_hora{what time} ___ de{from} casa{home|f}?', base: 'salir', hint: 'tú', gloss: 'to leave', a: ['saldrás'], p: 'tú', en: 'What time will you leave home?', why: 'Salir replaces the i with d: saldr- plus -ás.' },
    { c: 'future-irr', s: 'Ellos{they|m.pl} no{not} ___ tiempo{time|m} para{to} visitarnos{visit us}.', base: 'tener', gloss: 'to have', a: ['tendrán'], p: 'ellos', en: 'They won’t have time to visit us.', why: 'Tener becomes tendr-: tendrán.' },
    { c: 'future-irr', s: '¿Qué{what} ___ ustedes{you (plural)} este{this|m} verano{summer|m}?', base: 'hacer', gloss: 'to do', a: ['harán'], p: 'ellos', en: 'What will you do this summer?', why: 'Hacer shrinks to har-. Ustedes takes the ellos form: harán.' },
    { c: 'future-irr', s: 'Mis{my|m.pl} primos{cousin|m.pl} ___ a{to} la{the|f} boda{wedding|f} desde{from} Chile{Chile}.', base: 'venir', gloss: 'to come', a: ['vendrán'], p: 'ellos', en: 'My cousins will come to the wedding from Chile.', why: 'Venir becomes vendr-: vendrán.' },
    { c: 'future-irr', s: 'Mañana{tomorrow} ___ un{a|m} concierto{concert|m} en{in} la{the|f} plaza{square|f}.', base: 'haber', hint: 'hay', gloss: 'there is (hay)', a: ['habrá'], p: 'él', en: 'Tomorrow there will be a concert in the square.', why: 'Hay in the future is habrá, one form.' },
    { c: 'future-irr', s: 'Te{you} ___ el{the|m} café{coffee|m} en{on} la{the|f} mesa{table|f}.', base: 'poner', hint: 'yo', gloss: 'to put', a: ['pondré'], p: 'yo', en: 'I will put your coffee on the table.', why: 'Poner becomes pondr-: pondré.' },
    { c: 'future-irr', s: 'Pronto{soon} ___ la{the|f} verdad{truth|f}.', base: 'saber', hint: 'nosotros', gloss: 'to know', a: ['sabremos'], p: 'nosotros', en: 'Soon we will know the truth.', why: 'Saber drops the e: sabr- plus -emos, no accent.' },
    { c: 'future-irr', s: 'Seguro_que{surely} él{he|m} no{not} ___ venir{come} con{with} nosotros{us}.', base: 'querer', gloss: 'to want', a: ['querrá'], p: 'él', en: 'He surely won’t want to come with us.', why: 'Querer drops the e and doubles the r: querrá.' },
    { c: 'future-irr', s: 'Hoy{today} ___ mucho{a lot of|m} calor{heat|m}, según{according to} las{the|f.pl} noticias{news|f.pl}.', base: 'hacer', hint: 'it', gloss: 'to be (weather)', a: ['hará'], p: 'él', en: 'It will be very hot today, according to the news.', why: 'A forecast: futuro simple. Hacer shortens to har-: hará.' },
    { c: 'future-irr', s: 'Esta{this|f} casa{house|f} ___ mucho{a lot} dentro_de{in} unos{a few|m.pl} años{year|m.pl}.', base: 'valer', gloss: 'to be worth', a: ['valdrá'], p: 'él', en: 'This house will be worth a lot in a few years.', why: 'Valer becomes valdr-: valdrá.' },
    { c: 'future-irr', s: 'No{not} ___ todos{all|m.pl} en{in} el{the|m} carro{car|m}.', base: 'caber', hint: 'nosotros', gloss: 'to fit', a: ['cabremos'], p: 'nosotros', en: 'We won’t all fit in the car.', why: 'Caber drops the e: cabr- plus -emos.' },
    { c: 'future-irr', s: '¿Cuándo{when} ___ las{the|f.pl} notas{grade|f.pl}?', base: 'poner', hint: 'ellos', gloss: 'to put (up)', a: ['pondrán'], p: 'ellos', en: 'When will they put up the grades?', why: 'Poner becomes pondr-: pondrán.' },
    { c: 'future-irr', s: '¿Ustedes{you (plural)} ___ venir{come} a{to} la{the|f} cena{dinner|f} del{on|m} sábado{Saturday|m}?', base: 'poder', gloss: 'can, to be able to', a: ['podrán'], p: 'ellos', en: 'Will you be able to come to the dinner on Saturday?', why: 'Poder drops the e: podr-. Ustedes takes the ellos form: podrán.' },
    { c: 'future-irr', s: 'Yo{I} ___ lo_que{what} pienso{I think} en{at} la{the|f} reunión{meeting|f}.', base: 'decir', gloss: 'to say', a: ['diré'], p: 'yo', en: 'I will say what I think at the meeting.', why: 'Decir shrinks to dir-: diré.' },
    { c: 'future-irr', s: 'Mi{my|f} hermana{sister|f} ___ de{on} viaje{trip|m} el{on|m} domingo{Sunday|m}.', base: 'salir', gloss: 'to set off', a: ['saldrá'], p: 'él', en: 'My sister will set off on a trip on Sunday.', why: 'Salir becomes saldr-: saldrá.' },
    { c: 'future-irr', s: 'Creo{I think} que{that} el{the|m} paquete{parcel|m} no{not} ___ en{in} el{the|m} buzón{letterbox|m}.', base: 'caber', gloss: 'to fit', a: ['cabrá'], p: 'él', en: 'I think the parcel won’t fit in the letterbox.', why: 'Caber drops the e: cabrá.' },
    { c: 'future-irr', s: 'El_próximo_mes{next month|m} ___ un{a|m} carro{car|m} nuevo{new|m}.', base: 'tener', hint: 'yo', gloss: 'to have', a: ['tendré'], p: 'yo', en: 'Next month I will have a new car.', why: 'Tener swaps its vowel for a d: tendr- plus -é.' },
    { c: 'future-irr', s: '¿Cuándo{when} ___ si{whether} te{you} dieron{they gave} el{the|m} trabajo{job|m}?', base: 'saber', hint: 'tú', gloss: 'to know', a: ['sabrás'], p: 'tú', en: 'When will you know whether you got the job?', why: 'Saber drops the e: sabr- plus -ás.' },
    { c: 'future-irr', s: 'Nosotros{we} ___ la{the|f} mesa{table|f} mientras{while} tú{you} cocinas{cook}.', base: 'poner', gloss: 'to put, set', a: ['pondremos'], p: 'nosotros', en: 'We will set the table while you cook.', why: 'Poner swaps its vowel for a d: pondr- plus -emos.' },
    { c: 'future-irr', s: 'Mis{my|m.pl} padres{parents|m.pl} no{not} ___ salir{go out} esta{this|f} noche{night|f}.', base: 'querer', gloss: 'to want', a: ['querrán'], p: 'ellos', en: 'My parents won’t want to go out tonight.', why: 'Querer drops the e and keeps both r: querrán.' },
    { c: 'future-irr', s: 'Si{if} sigues{you carry on} así{like this}, no{not} ___ nada{anything} bueno{good|m}.', base: 'hacer', hint: 'tú', gloss: 'to do', a: ['harás'], p: 'tú', en: 'If you carry on like this, you won’t achieve anything good.', why: 'Hacer shrinks to har-: harás.' },
    { c: 'future-irr', s: 'Esta{this|f} noche{night|f} ___ arepas{arepa|f.pl} para{for} la{the|f} cena{dinner|f}.', base: 'hacer', hint: 'yo', gloss: 'to make', a: ['haré'], p: 'yo', en: 'Tonight I will make arepas for dinner.', why: 'Hacer shrinks to har-: haré.' },
    { c: 'future-irr', s: 'Si{if} estudias{you study} medicina{medicine|f}, ___ que{(to)} estudiar{study} muchos{many|m.pl} años{year|m.pl}.', base: 'tener', hint: 'tú', gloss: 'to have', a: ['tendrás'], p: 'tú', en: 'If you study medicine, you will have to study for many years.', why: 'Tener que in the futuro: tendr- plus -ás, tendrás que.' },
    { c: 'future-irr', s: 'El{the|m} técnico{technician|m} ___ mañana{tomorrow} a{to} arreglar{fix} la{the|f} lavadora{washing machine|f}.', base: 'venir', gloss: 'to come', a: ['vendrá'], p: 'él', en: 'The technician will come tomorrow to fix the washing machine.', why: 'Venir becomes vendr-: vendrá.' },
    { c: 'future-irr', s: '___ a{at} las{the|f.pl} cinco{five} para{to} evitar{avoid} el{the|m} tráfico{traffic|m}.', base: 'salir', hint: 'nosotros', gloss: 'to leave', a: ['Saldremos'], p: 'nosotros', en: 'We will leave at five to avoid the traffic.', why: 'Salir becomes saldr-: saldremos, no accent.' },
    { c: 'future-irr', s: 'Mis{my|m.pl} amigos{friend|m.pl} no{not} ___ nada{anything}; saben{they know how to} guardar{keep} un{a|m} secreto{secret|m}.', base: 'decir', gloss: 'to say', a: ['dirán'], p: 'ellos', en: 'My friends won’t say anything; they know how to keep a secret.', why: 'Decir shrinks to dir-: dirán.' },
    { c: 'future-irr', s: 'Ustedes{you (plural)} ___ los{the|m.pl} resultados{result|m.pl} la_próxima_semana{next week|f}.', base: 'saber', gloss: 'to know', a: ['sabrán'], p: 'ellos', en: 'You will know the results next week.', why: 'Saber drops the e: sabr-. Ustedes takes the ellos form: sabrán.' },
    { c: 'future-irr', s: 'El_próximo_mes{next month|m} ___ elecciones{election|f.pl} en{in} todo{the whole|m} el{the|m} país{country|m}.', base: 'haber', hint: 'hay', gloss: 'there is (hay)', a: ['habrá'], p: 'él', en: 'Next month there will be elections across the whole country.', why: 'Hay in the future is habrá, singular even with a plural noun: habrá elecciones.' },
    { c: 'future-irr', s: 'Te{you} ___ informado{informed|m} de{of} todo{everything|m}.', base: 'mantener', hint: 'yo', gloss: 'to keep', a: ['mantendré'], p: 'yo', en: 'I will keep you informed of everything.', why: 'Mantener follows tener: mantendré.' },
    { c: 'future-irr', s: '¿Tú{you} ___ la{the|f} música{music|f} para{for} la{the|f} fiesta{party|f}?', base: 'poner', gloss: 'to put on', a: ['pondrás'], p: 'tú', en: 'Will you put on the music for the party?', why: 'Poner becomes pondr-: pondrás.' },
    { c: 'future-irr', s: 'Este{this|m} carro{car|m} usado{used|m} no{not} ___ más{more} de{than} cinco{five} millones{million|m.pl}.', base: 'valer', gloss: 'to be worth', a: ['valdrá'], p: 'él', en: 'This used car won’t be worth more than five million.', why: 'Valer becomes valdr-: valdrá.' },
    { c: 'future-irr', s: 'No{don’t} te{yourself} preocupes{worry}: ___ todo{everything|m} lo{(the)} posible{possible} por{to} ayudarte{help you}.', base: 'hacer', hint: 'nosotros', gloss: 'to do', a: ['haremos'], p: 'nosotros', en: 'Don’t worry: we will do everything we can to help you.', why: 'Hacer shrinks to har-: haremos, no accent.' },
    { c: 'future-irr', s: 'Con{with} este{this|m} sueldo{salary|m}, mis{my|m.pl} papás{parents|m.pl} no{not} ___ pagar{pay} el{the|m} arriendo{rent|m}.', base: 'poder', gloss: 'can, to be able to', a: ['podrán'], p: 'ellos', en: 'With this salary, my parents won’t be able to pay the rent.', why: 'Poder drops the e: podrán.' },
    { c: 'future-irr', s: 'Esta{this|f} mudanza{move|f} ___ un{a|m} gasto{expense|m} enorme{huge}.', base: 'suponer', gloss: 'to mean, involve', a: ['supondrá'], p: 'él', en: 'This move will mean a huge expense.', why: 'Suponer follows poner: supondrá.' },
    { c: 'future-irr', s: 'Si{if} sigues{you follow} estos{these|m.pl} pasos{step|m.pl}, ___ mejores{better} resultados{result|m.pl}.', base: 'obtener', hint: 'tú', gloss: 'to get', a: ['obtendrás'], p: 'tú', en: 'If you follow these steps, you will get better results.', why: 'Obtener follows tener: obtendrás.' },
    { c: 'future-irr', s: 'Después_de{after} esta{this|f} caminata{hike|f}, solo{only} ___ dormir{sleep}.', base: 'querer', hint: 'yo', gloss: 'to want', a: ['querré'], p: 'yo', en: 'After this hike, I will only want to sleep.', why: 'Querer drops the e and doubles the r: querré.' },
    { c: 'future-irr', s: 'Si{if} llegamos{we arrive} temprano{early}, ___ ver{see} el{the|m} desfile{parade|m} desde{from} adelante{the front}.', base: 'poder', hint: 'nosotros', gloss: 'can, to be able to', a: ['podremos'], p: 'nosotros', en: 'If we arrive early, we will be able to see the parade from the front.', why: 'Poder drops the e: podr- plus -emos.' },
    { c: 'future-irr', s: 'Los{the|m.pl} resultados{result|m.pl} ___ en{in} el{the|m} periódico{newspaper|m} mañana{tomorrow}.', base: 'salir', gloss: 'to come out', a: ['saldrán'], p: 'ellos', en: 'The results will come out in the newspaper tomorrow.', why: 'Salir becomes saldr-: saldrán.' },
    { c: 'future-irr', s: 'El{the|m} alcalde{mayor|m} ___ un{a|m} nuevo{new|m} plan{plan|m} de{of} transporte{transport|m}.', base: 'proponer', gloss: 'to propose', a: ['propondrá'], p: 'él', en: 'The mayor will propose a new transport plan.', why: 'Proponer follows poner: propondrá.' },
    { c: 'future-irr', s: 'Con{with} tanta{so much|f} gente{people|f}, no{not} ___ en{in} el{the|m} ascensor{lift|m}.', base: 'caber', hint: 'tú', gloss: 'to fit', a: ['cabrás'], p: 'tú', en: 'With so many people, you won’t fit in the lift.', why: 'Caber drops the e: cabr- plus -ás.' },
    { c: 'future-irr', s: '¿Ustedes{you (plural)} ___ tiempo{time|m} de{to} pasar{drop by} por{at} la{the|f} oficina{office|f} mañana{tomorrow}?', base: 'tener', gloss: 'to have', a: ['tendrán'], p: 'ellos', en: 'Will you have time to drop by the office tomorrow?', why: 'Tener becomes tendr-. Ustedes takes the ellos form: tendrán.' },
    { c: 'future-irr', s: 'Mañana{tomorrow} les{them} ___ a{to} los{the|m.pl} niños{children|m.pl} que{that} nos{ourselves} vamos{we are going} a{to} mudar{move}.', base: 'decir', hint: 'nosotros', gloss: 'to tell', a: ['diremos'], p: 'nosotros', en: 'Tomorrow we will tell the children that we are going to move.', why: 'Decir shrinks to dir-: diremos.' },
    { c: 'future-irr', s: 'Mañana{tomorrow} ___ las{the|f.pl} maletas{suitcase|f.pl}; hoy{today} estoy{I am} muy{very} cansado{tired|m}.', base: 'deshacer', hint: 'yo', gloss: 'to unpack', a: ['desharé'], p: 'yo', en: 'Tomorrow I will unpack the suitcases; today I am very tired.', why: 'Deshacer follows hacer: desharé.' },

    // Probabilidad y futuro perfecto
    { c: 'future-prob', at: ['about the time', 'Spanish'], s: 'No{not} sé{I know} qué{what} hora{time|f} es{it is}. ___ las{the|f.pl} siete{seven}.', base: 'ser', hint: 'guess', gloss: 'to be', a: ['Serán'], p: 'ellos', en: 'I don’t know what time it is. It must be about seven.', why: 'A guess about the present takes the futuro simple: serán las siete.' },
    { c: 'future-prob', at: ['a question', 'Spanish'], s: '¿Dónde{where} ___ mis{my|m.pl} lentes{glasses|m.pl}?', base: 'estar', hint: 'guess', gloss: 'to be', a: ['estarán'], p: 'ellos', en: 'Where can my glasses be?', why: 'Wondering about the present: estarán, I wonder where they are.' },
    { c: 'future-prob', at: ['about a person', 'Spanish'], s: 'Esa{that|f} chica{girl|f} ___ unos{about|m.pl} veinte{twenty} años{year|m.pl}.', base: 'tener', hint: 'guess', gloss: 'to have', a: ['tendrá'], p: 'él', en: 'That girl must be about twenty.', why: 'An estimate of age: tendrá, she must be.' },
    { c: 'future-prob', s: 'Ana{Ana} no{not} contesta{answers}. ___ el{the|m} celular{cell phone|m} en{at} casa{home|f}.', base: 'dejar', hint: 'guess, perf.', gloss: 'to leave', a: ['Habrá dejado'], p: 'él', en: 'Ana isn’t answering. She must have left her phone at home.', why: 'A guess about something that already happened: futuro perfecto, habrá dejado.' },
    { c: 'future-prob', s: 'Para{by} el{the|m} viernes{Friday|m} ___ el{the|m} informe{report|m}.', base: 'terminar', hint: 'yo, perfecto', gloss: 'to finish', a: ['habré terminado'], p: 'yo', en: 'By Friday I will have finished the report.', why: 'Finished by a point in the future: futuro perfecto, habré terminado.' },
    { c: 'future-prob', s: 'Cuando{when} llegues{you arrive}, nosotros{we} ya{already} ___.', base: 'cenar', hint: 'perfecto', gloss: 'to have dinner', a: ['habremos cenado'], p: 'nosotros', en: 'When you arrive, we will already have had dinner.', why: 'Done before a future moment: habremos cenado.' },
    { c: 'future-prob', at: ['a question', 'Spanish'], s: '¿Quién{who} ___ a{at} estas{these|f.pl} horas{hour|f.pl}?', base: 'ser', hint: 'guess', gloss: 'to be', a: ['será'], p: 'él', en: 'Who can that be at this hour?', why: 'Someone is at the door and you wonder who: será.' },
    { c: 'future-prob', at: ['about a person', 'Spanish'], s: 'Los{the|m.pl} niños{children|m.pl} ___ hambre{hunger|f}, no{not} han{have} comido{eaten} nada{anything}.', base: 'tener', hint: 'guess', gloss: 'to have', a: ['tendrán'], p: 'ellos', en: 'The children must be hungry, they haven’t eaten anything.', why: 'A guess about now: tendrán hambre, they must be hungry.' },
    { c: 'future-prob', s: 'El{the|m} tren{train|m} ya{already} ___, son{it is} las{the|f.pl} nueve{nine} y{and} media{half}.', base: 'salir', hint: 'guess, perf.', gloss: 'to leave', a: ['habrá salido'], p: 'él', en: 'The train must have left already, it is half past nine.', why: 'A guess about the recent past: futuro perfecto, habrá salido.' },
    { c: 'future-prob', s: '¿Por_qué{why} no{not} viene{comes} Luis{Luis}? ___ mucho{a lot of|m} tráfico{traffic|m}.', base: 'haber', hint: 'hay, guess', gloss: 'there is (hay)', a: ['Habrá'], p: 'él', en: 'Why isn’t Luis coming? There must be a lot of traffic.', why: 'A guess with hay: habrá mucho tráfico, there is probably a lot of traffic.' },
    { c: 'future-prob', s: 'Dentro_de{in} un{a|m} año{year|m} ___ la{the|f} carrera{degree|f}.', base: 'terminar', hint: 'tú, perfecto', gloss: 'to finish', a: ['habrás terminado'], p: 'tú', en: 'In a year you will have finished your degree.', why: 'Finished by a future point: habrás terminado.' },
    { c: 'future-prob', s: '¿Ustedes{you (plural)} ___ la{the|f} casa{house|f} antes_de{before} septiembre{September}?', base: 'vender', hint: 'perfecto', gloss: 'to sell', a: ['habrán vendido'], p: 'ellos', en: 'Will you have sold the house before September?', why: 'Antes de septiembre sets the deadline. Ustedes takes the ellos form: habrán vendido.' },
    { c: 'future-prob', s: 'Mi{my|m} vecino{neighbour|m} ___ en{in} el{the|m} extranjero{abroad|m}, habla{he speaks} cuatro{four} idiomas{language|m.pl}.', base: 'vivir', hint: 'guess, perf.', gloss: 'to live', a: ['habrá vivido'], p: 'él', en: 'My neighbour must have lived abroad, he speaks four languages.', why: 'A guess about his past from what you see now: habrá vivido.' },
    { c: 'future-prob', at: ['about a person', 'Spanish'], s: 'Marta{Marta} no{not} está{is} en{at} casa{home|f}. ___ en{at} el{the|m} trabajo{work|m}.', base: 'estar', hint: 'guess', gloss: 'to be', a: ['Estará'], p: 'él', en: 'Marta isn’t at home. She must be at work.', why: 'A guess about where she is now: estará.' },
    { c: 'future-prob', s: 'Para{by} el{the|m} año{year|m} 2040{2040} los{the|m.pl} carros{car|m.pl} ___ mucho{a lot}.', base: 'cambiar', hint: 'ellos, perf.', gloss: 'to change', a: ['habrán cambiado'], p: 'ellos', en: 'By the year 2040 cars will have changed a lot.', why: 'Para el año 2040 sets a future point: habrán cambiado.' },
    { c: 'future-prob', s: 'Son{it is} las{the|f.pl} once{eleven}. Los{the|m.pl} niños{children|m.pl} ya{already} ___.', base: 'dormirse', hint: 'guess, perf.', gloss: 'to fall asleep', a: ['se habrán dormido'], p: 'ellos', en: 'It is eleven. The children must have fallen asleep by now.', why: 'A guess about the recent past: se habrán dormido, with the pronoun before habrán.' },
    { c: 'future-prob', at: ['about the time', 'Spanish'], s: 'Ya{already} está{it is} oscuro{dark|m}; ___ las{the|f.pl} ocho{eight}.', base: 'ser', hint: 'guess', gloss: 'to be', a: ['serán'], p: 'ellos', en: 'It is already dark; it must be about eight.', why: 'A guess about the time right now: serán las ocho.' },
    { c: 'future-prob', at: ['about a person', 'Spanish'], s: 'Pedro{Pedro} no{not} vino{came} a{to} clase{class|f}; ___ enfermo{ill|m}.', base: 'estar', hint: 'guess', gloss: 'to be', a: ['estará'], p: 'él', en: 'Pedro didn’t come to class; he must be ill.', why: 'A guess about the present: estará enfermo, he must be ill.' },
    { c: 'future-prob', at: ['a question', 'Spanish'], s: '¿Cuántos{how many|m.pl} años{year|m.pl} ___ el{the|m} profesor{teacher|m} nuevo{new|m}?', base: 'tener', hint: 'guess', gloss: 'to have', a: ['tendrá'], p: 'él', en: 'I wonder how old the new teacher is.', why: 'Wondering about the present: ¿cuántos años tendrá?, I wonder how old he is.' },
    { c: 'future-prob', s: '¿Dónde{where} ___ las{the|f.pl} llaves{keys|f.pl}? Esta_mañana{this morning|f} las{them|f.pl} tenía{I had}.', base: 'poner', hint: 'yo, guess, perf.', gloss: 'to put', a: ['habré puesto'], p: 'yo', en: 'Where can I have put the keys? I had them this morning.', why: 'Wondering about the recent past: futuro perfecto, habré plus puesto, the irregular participle of poner.' },
    { c: 'future-prob', s: 'Para{by} las{the|f.pl} diez{ten} ya{already} ___ todos{all|m.pl} los{the|m.pl} invitados{guests|m.pl}.', base: 'llegar', hint: 'perfecto', gloss: 'to arrive', a: ['habrán llegado'], p: 'ellos', en: 'By ten all the guests will have arrived.', why: 'Something finished by a point in the future: futuro perfecto, habrán plus llegado.' },
    { c: 'future-prob', s: 'Para{by} el{the|m} lunes{Monday|m} ya{already} ___ la{the|f} mudanza{move|f}.', base: 'hacer', hint: 'nosotros, perf.', gloss: 'to do', a: ['habremos hecho'], p: 'nosotros', en: 'By Monday we will already have done the move.', why: 'Finished by a point in the future: nosotros is habremos plus hecho, the irregular participle of hacer.' },
    { c: 'future-prob', at: ['about the time', 'Spanish'], s: 'El{the|m} sol{sun|m} ya{already} está{is} saliendo{coming up}; ___ las{the|f.pl} seis{six}.', base: 'ser', hint: 'guess', gloss: 'to be', a: ['serán'], p: 'ellos', en: 'The sun is already coming up; it must be about six.', why: 'A guess about the time right now: serán las seis.' },
    { c: 'future-prob', at: ['about the time', 'Spanish'], s: 'Todavía{still} no{not} ha{has} sonado{rung} la{the|f} campana{bell|f}, pero{but} ___ casi{almost} la{the|f} una{one}.', base: 'ser', hint: 'guess', gloss: 'to be', a: ['será'], p: 'él', en: 'The bell hasn’t rung yet, but it must be almost one.', why: 'A guess about the time. La una is singular, so será, not serán.' },
    { c: 'future-prob', at: ['a question', 'Spanish'], s: '¿Qué{what} hora{time|f} ___? Dejé{I left} el{the|m} reloj{watch|m} en{at} casa{home|f}.', base: 'ser', hint: 'guess', gloss: 'to be', a: ['será'], p: 'él', en: 'I wonder what time it is. I left my watch at home.', why: 'Wondering about the present: ¿qué hora será?, I wonder what time it is.' },
    { c: 'future-prob', at: ['about a person', 'Spanish'], s: 'Mi{my|m} vecino{neighbour|m} siempre{always} lleva{wears} traje{suit|m}; ___ abogado{lawyer|m}.', base: 'ser', hint: 'guess', gloss: 'to be', a: ['será'], p: 'él', en: 'My neighbour always wears a suit; he must be a lawyer.', why: 'A guess about the present from what you see: será abogado.' },
    { c: 'future-prob', at: ['a question', 'Spanish'], s: '¿Qué{what} ___ en{in} esa{that|f} caja{box|f} tan{so} pesada{heavy|f}?', base: 'haber', hint: 'hay, guess', gloss: 'there is (hay)', a: ['habrá'], p: 'él', en: 'I wonder what is in that heavy box.', why: 'Wondering about the present with hay: ¿qué habrá?' },
    { c: 'future-prob', at: ['a question', 'Spanish'], s: '¿Quién{who} ___ esa{that|f} chica{girl|f}? Nunca{never} la{her} había{had} visto{seen}.', base: 'ser', hint: 'guess', gloss: 'to be', a: ['será'], p: 'él', en: 'I wonder who that girl is. I had never seen her before.', why: 'A question in the futuro means I wonder: ¿quién será?' },
    { c: 'future-prob', at: ['about a person', 'Spanish'], s: 'Tus{your|m.pl} papás{parents|m.pl} ___ muy{very} orgullosos{proud|m.pl} de{of} ti{you}.', base: 'estar', hint: 'guess', gloss: 'to be', a: ['estarán'], p: 'ellos', en: 'Your parents must be very proud of you.', why: 'A guess about how they feel now: estarán orgullosos.' },
    { c: 'future-prob', at: ['about a person', 'Spanish'], s: 'Carlos{Carlos} tiene{has} tres{three} carros{car|m.pl} y{and} una{a|f} finca{country house|f}; ___ mucha{a lot of|f} plata{money|f}.', base: 'ganar', hint: 'guess', gloss: 'to earn', a: ['ganará'], p: 'él', en: 'Carlos has three cars and a country house; he must earn a lot of money.', why: 'A guess about the present: ganará, he must earn.' },
    { c: 'future-prob', at: ['a question', 'Spanish'], s: '¿Por_qué{why} ___ tan{so} callados{quiet|m.pl} los{the|m.pl} niños{children|m.pl}?', base: 'estar', hint: 'guess', gloss: 'to be', a: ['estarán'], p: 'ellos', en: 'I wonder why the children are so quiet.', why: 'Wondering about the present: ¿por qué estarán tan callados?' },
    { c: 'future-prob', s: 'La{the|f} calle{street|f} está{is} mojada{wet|f}; ___ anoche{last night}.', base: 'llover', hint: 'guess, perf.', gloss: 'to rain', a: ['habrá llovido'], p: 'él', en: 'The street is wet; it must have rained last night.', why: 'A guess about the past from what you see now: futuro perfecto, habrá llovido.' },
    { c: 'future-prob', s: 'Para{by} junio{June} ya{already} ___ cien{a hundred} libros{book|m.pl} este{this|m} año{year|m}.', base: 'leer', hint: 'yo, perfecto', gloss: 'to read', a: ['habré leído'], p: 'yo', en: 'By June I will already have read a hundred books this year.', why: 'Finished by a point in the future: habré leído. The participle leído has an accent.' },
    { c: 'future-prob', s: '¿No{not} ___ tú{you} las{the|f.pl} llaves{key|f.pl} en{at} la{the|f} oficina{office|f}?', base: 'olvidar', hint: 'guess, perf.', gloss: 'to forget', a: ['habrás olvidado'], p: 'tú', en: 'You haven’t left the keys at the office, have you?', why: 'A worried guess about the recent past: futuro perfecto, habrás olvidado.' },
    { c: 'future-prob', s: 'Cuando{when} vuelvas{you come back} de{from} tu{your} viaje{trip|m}, ya{already} ___ de{(of)} casa{house|f}.', base: 'mudarse', hint: 'nosotros, perf.', gloss: 'to move (house)', a: ['nos habremos mudado'], p: 'nosotros', en: 'When you come back from your trip, we will already have moved house.', why: 'Done before a future moment: nos habremos mudado, with the pronoun before habremos.' },
    { c: 'future-prob', s: 'Hay{there are} muchos{many|m.pl} platos{plate|m.pl} sucios{dirty|m.pl}; los{the|m.pl} chicos{kid|m.pl} ___ una{a|f} fiesta{party|f}.', base: 'hacer', hint: 'guess, perf.', gloss: 'to have (a party)', a: ['habrán hecho'], p: 'ellos', en: 'There are a lot of dirty plates; the kids must have had a party.', why: 'A guess about the recent past: habrán plus hecho, the irregular participle of hacer.' },
    { c: 'future-prob', s: 'Para{by} cuando{the time} yo{I} llegue{arrive}, ¿ustedes{you (plural)} ya{already} ___?', base: 'comer', hint: 'perfecto', gloss: 'to eat', a: ['habrán comido'], p: 'ellos', en: 'By the time I arrive, will you already have eaten?', why: 'Finished before a future moment. Ustedes takes the ellos form: habrán comido.' },
    { c: 'future-prob', s: 'Para{by} las{the|f.pl} cinco{five} el{the|m} mecánico{mechanic|m} ya{already} ___ el{the|m} carro{car|m}.', base: 'arreglar', hint: 'perfecto', gloss: 'to fix', a: ['habrá arreglado'], p: 'él', en: 'By five the mechanic will already have fixed the car.', why: 'Para las cinco sets a future point: habrá arreglado.' },
    { c: 'future-prob', s: '¡Qué{how} raro{strange|m}! No{not} encuentro{I find} el{the|m} mensaje{message|m}; lo{it|m} ___.', base: 'borrar', hint: 'yo, guess, perf.', gloss: 'to delete', a: ['habré borrado'], p: 'yo', en: 'How strange! I can’t find the message; I must have deleted it.', why: 'A guess about your own recent past: habré borrado, with lo before habré.' },
    { c: 'future-prob', s: 'Lucía{Lucía} tiene{has} los{the|m.pl} ojos{eye|m.pl} rojos{red|m.pl}; ___.', base: 'llorar', hint: 'guess, perf.', gloss: 'to cry', a: ['habrá llorado'], p: 'él', en: 'Lucía’s eyes are red; she must have been crying.', why: 'A guess about the recent past from what you see: habrá llorado.' },
    { c: 'future-prob', s: 'Cuando{when} cumplas{you turn} treinta{thirty} años{year|m.pl}, ya{already} ___ medio{half} mundo{world|m}.', base: 'recorrer', hint: 'tú, perfecto', gloss: 'to travel around', a: ['habrás recorrido'], p: 'tú', en: 'By the time you turn thirty, you will already have travelled half the world.', why: 'Done before a future moment: habrás recorrido.' },
    { c: 'future-prob', s: '¿Cuántos{how many|m.pl} kilómetros{kilometre|m.pl} ___ hoy{today}? Estoy{I am} agotada{exhausted|f}.', base: 'caminar', hint: 'nosotros, guess, perf.', gloss: 'to walk', a: ['habremos caminado'], p: 'nosotros', en: 'I wonder how many kilometres we have walked today. I am exhausted.', why: 'Wondering about the recent past: futuro perfecto, habremos caminado.' },
    { c: 'future-prob', s: 'El{the|m} paquete{parcel|m} no{not} ha{has} llegado{arrived}; ___ en{in} el{the|m} correo{post|m}.', base: 'perderse', hint: 'guess, perf.', gloss: 'to get lost', a: ['se habrá perdido'], p: 'él', en: 'The parcel hasn’t arrived; it must have got lost in the post.', why: 'A guess about the recent past: se habrá perdido, with se before habrá.' },
    { c: 'future-prob', s: 'Para{by} el{the|m} año{year|m} que_viene{next} los{the|m.pl} obreros{worker|m.pl} ya{already} ___ el{the|m} puente{bridge|m}.', base: 'construir', hint: 'perfecto', gloss: 'to build', a: ['habrán construido'], p: 'ellos', en: 'By next year the workers will already have built the bridge.', why: 'Finished by a point in the future: habrán construido.' },

    // Ir a o futuro
    { c: 'future-choice', s: 'Este{this|m} fin_de_semana{weekend|m} ___ a{(personal a)} mis{my|m.pl} padres{parents|m.pl}.', base: 'visitar', hint: 'yo, ir a', gloss: 'to visit', a: ['voy a visitar', 'visitaré'], p: 'yo', en: 'This weekend I am going to visit my parents.', why: 'A plan already made: ir a is the natural choice, voy a visitar. Visitaré is correct too but sounds more formal.' },
    { c: 'future-choice', s: 'Tranquila{don’t worry|f}, yo{I} te{you} ___ con{with} la{the|f} mudanza{move|f}.', base: 'ayudar', hint: 'futuro', gloss: 'to help', a: ['ayudaré', 'voy a ayudar'], p: 'yo', en: 'Don’t worry, I will help you with the move.', why: 'A promise: futuro simple, ayudaré. Te voy a ayudar is also heard.' },
    { c: 'future-choice', s: 'Mira{look}, el{the|m} niño{child|m} ___.', base: 'caerse', hint: 'ir a', gloss: 'to fall', a: ['se va a caer', 'va a caerse'], p: 'él', en: 'Look, the child is going to fall.', why: 'Evidence right in front of you: only ir a sounds natural. Se caerá would be a prediction with no clear evidence.' },
    { c: 'future-choice', s: 'Dentro_de{in} cincuenta{fifty} años{year|m.pl} la{the|f} gente{people|f} ___ en{on} Marte{Mars}.', base: 'vivir', hint: 'futuro', gloss: 'to live', a: ['vivirá', 'va a vivir'], p: 'él', en: 'In fifty years people will live on Mars.', why: 'A distant prediction: vivirá. Va a vivir is possible but less usual so far ahead. Gente is singular.' },
    { c: 'future-choice', s: 'Esta{this|f} noche{night|f} nosotros{we} ___ en{at} casa{home|f}.', base: 'quedarse', hint: 'ir a', gloss: 'to stay', a: ['nos vamos a quedar', 'vamos a quedarnos', 'nos quedaremos'], p: 'nosotros', en: 'Tonight we are going to stay at home.', why: 'A plan for tonight: ir a, with the pronoun before vamos or attached: nos vamos a quedar, vamos a quedarnos.' },
    { c: 'future-choice', s: '¿Qué{what} ___ ustedes{you (plural)} después_de{after} la{the|f} universidad{university|f}?', base: 'hacer', hint: 'ir a', gloss: 'to do', a: ['van a hacer', 'harán'], p: 'ellos', en: 'What are you going to do after university?', why: 'Asking about plans: van a hacer. Harán is fine too. Ustedes takes the ellos form.' },
    { c: 'future-choice', s: 'No{not} sé{I know} qué{what} hora{time|f} es{it is}, ___ las{the|f.pl} nueve{nine}.', base: 'ser', hint: 'guess', gloss: 'to be', a: ['serán'], p: 'ellos', en: 'I don’t know what time it is, it must be about nine.', why: 'A guess about the present takes the futuro simple only: serán las nueve.' },
    { c: 'future-choice', s: 'Te{you} lo{it|m} ___ mañana{tomorrow} sin_falta{without fail}.', base: 'devolver', hint: 'yo, futuro', gloss: 'to give back', a: ['devolveré', 'voy a devolver'], p: 'yo', en: 'I will give it back to you tomorrow without fail.', why: 'A promise: devolveré. In speech te lo voy a devolver is just as common.' },
    { c: 'future-choice', s: 'El{the|m} próximo{next|m} verano{summer|m} mis{my|m.pl} amigos{friend|m.pl} ___ un{a|m} viaje{trip|m} a{to} Japón{Japan}.', base: 'hacer', hint: 'ir a', gloss: 'to make', a: ['van a hacer', 'harán'], p: 'ellos', en: 'Next summer my friends are going to take a trip to Japan.', why: 'A plan: van a hacer. Harán works too, a little more formal.' },
    { c: 'future-choice', s: 'Ya{already} lo{it|m} tengo{I have} decidido{decided|m}: ___ este{this|m} trabajo{job|m}.', base: 'dejar', hint: 'yo, ir a', gloss: 'to leave, to quit', a: ['voy a dejar', 'dejaré'], p: 'yo', en: 'I have already decided: I am going to quit this job.', why: 'A decision already made: ir a, voy a dejar. Dejaré is possible but sounds more solemn.' },
    { c: 'future-choice', s: 'Creo{I think} que{that} mañana{tomorrow} ___ sol{sun|m}.', base: 'hacer', hint: 'it, futuro', gloss: 'to be (weather)', a: ['hará', 'va a hacer'], p: 'él', en: 'I think it will be sunny tomorrow.', why: 'A weather prediction: both work. Hará sol is forecast style, va a hacer sol is the everyday one.' },
    { c: 'future-choice', s: 'Cuando{when} sea{I am} mayor{older}, ___ médica{doctor|f}.', base: 'ser', hint: 'yo, futuro', gloss: 'to be', a: ['seré', 'voy a ser'], p: 'yo', en: 'When I grow up, I will be a doctor.', why: 'The distant future after cuando sea mayor: seré médica. Voy a ser is also fine.' },
    { c: 'future-choice', s: 'La_próxima_semana{next week|f} el{the|m} médico{doctor|m} me{me} ___ los{the|m.pl} resultados{result|m.pl}.', base: 'dar', hint: 'ir a', gloss: 'to give', a: ['va a dar', 'dará'], p: 'él', en: 'Next week the doctor is going to give me the results.', why: 'A fixed arrangement in the near future: va a dar. Dará is equally correct.' },
    { c: 'future-choice', s: 'Tú{you} ___ tarde{late} otra_vez{again}, seguro{for sure}.', base: 'llegar', hint: 'futuro', gloss: 'to arrive', a: ['llegarás', 'vas a llegar'], p: 'tú', en: 'You will be late again, for sure.', why: 'A prediction from what you know of the person: llegarás. Vas a llegar works as well.' },
    { c: 'future-choice', s: 'Mañana{tomorrow} ___ temprano{early} para{to} tomar{catch} el{the|m} tren{train|m}.', base: 'levantarse', hint: 'yo, ir a', gloss: 'to get up', a: ['me voy a levantar', 'voy a levantarme', 'me levantaré'], p: 'yo', en: 'Tomorrow I am going to get up early to catch the train.', why: 'A plan: ir a, with the pronoun before voy or attached. Me levantaré is also correct.' },
    { c: 'future-choice', s: 'Los{the|m.pl} científicos{scientist|m.pl} ___ una{a|f} cura{cure|f} algún_día{one day|m}.', base: 'encontrar', hint: 'futuro', gloss: 'to find', a: ['encontrarán', 'van a encontrar'], p: 'ellos', en: 'Scientists will find a cure one day.', why: 'Algún día is the distant, uncertain future: encontrarán. Van a encontrar is possible but less usual here.' },
    { c: 'future-choice', s: 'Cuidado{careful} con{with} ese{that|m} vaso{glass|m}, ___.', base: 'romperse', hint: 'ir a', gloss: 'to break', a: ['se va a romper', 'va a romperse'], p: 'él', en: 'Careful with that glass, it is going to break.', why: 'Evidence right in front of you: ir a, se va a romper.' },
    { c: 'future-choice', s: 'Te{you} prometo{I promise} que{that} nunca{never} más{again} ___ tarde{late}.', base: 'llegar', hint: 'yo, futuro', gloss: 'to arrive', a: ['llegaré', 'voy a llegar'], p: 'yo', en: 'I promise you I will never be late again.', why: 'A promise: futuro simple, llegaré. Voy a llegar is also heard.' },
    { c: 'future-choice', s: '¿Dónde{where} ___ Ana{Ana}? No{not} contesta{answers} el{the|m} teléfono{phone|m}.', base: 'estar', hint: 'guess', gloss: 'to be', a: ['estará'], p: 'él', en: 'I wonder where Ana is. She isn’t answering the phone.', why: 'A guess about the present takes only the futuro: estará. Va a estar would be about the future.' },
    { c: 'future-choice', s: 'Ya{already} compramos{we bought} los{the|m.pl} boletos{tickets|m.pl}: en{in} julio{July} ___ a{to} Cartagena{Cartagena}.', base: 'viajar', hint: 'nosotros, ir a', gloss: 'to travel', a: ['vamos a viajar', 'viajaremos'], p: 'nosotros', en: 'We have already bought the tickets: in July we are going to travel to Cartagena.', why: 'A plan already made: ir a is the natural choice, vamos a viajar. Viajaremos is correct but sounds more formal.' },
    { c: 'future-choice', s: 'En{in} el{the|m} futuro{future|m} los{the|m.pl} robots{robot|m.pl} ___ muchos{many|m.pl} trabajos{job|m.pl}.', base: 'hacer', hint: 'futuro', gloss: 'to do', a: ['harán', 'van a hacer'], p: 'ellos', en: 'In the future robots will do a lot of jobs.', why: 'A general prediction about the distant future: futuro simple, harán. Van a hacer is also fine.' },
    { c: 'future-choice', s: 'La{the|f} batería{battery|f} del{of the|m} celular{cell phone|m} está{is} al{at} uno{one} por_ciento{per cent}; ___.', base: 'apagarse', hint: 'ir a', gloss: 'to switch off', a: ['se va a apagar', 'va a apagarse'], p: 'él', en: 'The phone battery is at one per cent; it is going to switch off.', why: 'Evidence right in front of you: ir a, se va a apagar. Se apagará would sound like a prediction with no evidence.' },
    { c: 'future-choice', s: 'Tu{your|m} hermano{brother|m} no{not} ha{has} salido{come out} de{of} su{his} cuarto{room|m}; ___ dormido{asleep|m}.', base: 'estar', hint: 'guess', gloss: 'to be', a: ['estará'], p: 'él', en: 'Your brother hasn’t come out of his room; he must be asleep.', why: 'A guess about now takes only the futuro: estará. Va a estar would be about later.' },
    { c: 'future-choice', s: 'Ya{already} reservé{I booked} la{the|f} cancha{court|f}: mañana{tomorrow} ___ tenis{tennis|m} con{with} Andrés{Andrés}.', base: 'jugar', hint: 'yo, ir a', gloss: 'to play', a: ['voy a jugar', 'jugaré'], p: 'yo', en: 'I have already booked the court: tomorrow I am going to play tennis with Andrés.', why: 'A plan already made: ir a is the natural choice, voy a jugar. Jugaré is correct but sounds more formal.' },
    { c: 'future-choice', s: 'No{don’t} le{him} digas{tell} nada{anything} a{(to)} papá{dad|m}; yo{I} se{him} lo{it|m} ___ esta{this|f} noche{night|f}.', base: 'contar', hint: 'futuro', gloss: 'to tell', a: ['contaré', 'voy a contar'], p: 'yo', en: 'Don’t tell Dad anything; I will tell him tonight.', why: 'A promise to take care of it: futuro simple, contaré. Se lo voy a contar is also heard.' },
    { c: 'future-choice', s: 'Dentro_de{in} unos{a few|m.pl} siglos{century|m.pl} el{the|m} hielo{ice|m} del{of the|m} Polo_Norte{North Pole|m} ___.', base: 'desaparecer', hint: 'futuro', gloss: 'to disappear', a: ['desaparecerá', 'va a desaparecer'], p: 'él', en: 'In a few centuries the ice at the North Pole will disappear.', why: 'A prediction about the distant future: desaparecerá. Va a desaparecer is possible but less usual so far ahead.' },
    { c: 'future-choice', s: 'Apúrate{hurry up}, que{because} la{the|f} película{film|f} ___ en{in} cinco{five} minutos{minute|m.pl}.', base: 'empezar', hint: 'ir a', gloss: 'to start', a: ['va a empezar', 'empezará'], p: 'él', en: 'Hurry up, the film is going to start in five minutes.', why: 'Something about to happen: ir a, va a empezar. Empezará is correct too.' },
    { c: 'future-choice', s: 'Son{it is} las{the|f.pl} cuatro{four} y{and} cincuenta{fifty} y{and} nueve{nine}: ya{any moment now} ___ las{the|f.pl} cinco{five}.', base: 'ser', hint: 'ir a', gloss: 'to be', a: ['van a ser'], p: 'ellos', en: 'It is four fifty-nine: it is about to be five.', why: 'The clock is about to strike five: van a ser las cinco. Serán las cinco would be a guess, and here you know the time.' },
    { c: 'future-choice', s: '¿Cuánto{how much} ___ un{an|m} apartamento{apartment|m} en{in} este{this|m} barrio{neighbourhood|m}?', base: 'costar', hint: 'guess', gloss: 'to cost', a: ['costará'], p: 'él', en: 'I wonder how much an apartment costs in this neighbourhood.', why: 'Wondering about a price now: only the futuro, costará. Va a costar would be about a future price.' },
    { c: 'future-choice', s: 'Ya{already} lo{it|m} hablamos{we talked about}: el{the|m} año{year|m} que_viene{next} ___ un{a|m} perro{dog|m}.', base: 'adoptar', hint: 'nosotros, ir a', gloss: 'to adopt', a: ['vamos a adoptar', 'adoptaremos'], p: 'nosotros', en: 'We have talked it over: next year we are going to adopt a dog.', why: 'A decision already made: ir a, vamos a adoptar. Adoptaremos is correct but sounds more formal.' },
    { c: 'future-choice', s: 'Según{according to} el{the|m} pronóstico{forecast|m} oficial{official}, mañana{tomorrow} ___ fuertes{strong|m.pl} vientos{wind|m.pl} en{on} la{the|f} costa{coast|f}.', base: 'soplar', hint: 'futuro', gloss: 'to blow', a: ['soplarán', 'van a soplar'], p: 'ellos', en: 'According to the official forecast, strong winds will blow on the coast tomorrow.', why: 'A formal forecast: futuro simple, soplarán. Van a soplar is the everyday version. Vientos is plural, so -án.' },
    { c: 'future-choice', s: 'El{the|m} cielo{sky|m} se{itself} está{is} poniendo{turning} negro{black|m}: ___ una{a|f} tormenta{storm|f}.', base: 'haber', hint: 'hay, ir a', gloss: 'there is (hay)', a: ['va a haber', 'habrá'], p: 'él', en: 'The sky is turning black: there is going to be a storm.', why: 'The sky shows it coming, so ir a fits best: va a haber. Habrá is also fine as a plain prediction.' },
    { c: 'future-choice', s: 'Los{the|m.pl} albañiles{builder|m.pl} prometen{promise} que{that} ___ la{the|f} obra{work|f} antes_de{before} Navidad{Christmas|f}.', base: 'terminar', hint: 'futuro', gloss: 'to finish', a: ['terminarán', 'van a terminar'], p: 'ellos', en: 'The builders promise that they will finish the work before Christmas.', why: 'A promise: futuro simple, terminarán. Van a terminar is also heard.' },
    { c: 'future-choice', s: '¿Tú{you} ___ el{the|m} bus{bus|m} o{or} te{you} llevo{take} yo{I}?', base: 'tomar', hint: 'ir a', gloss: 'to take', a: ['vas a tomar', 'tomarás'], p: 'tú', en: 'Are you going to take the bus or shall I drive you?', why: 'Asking about someone’s plan: ir a, vas a tomar. Tomarás is possible but sounds stiff here.' },
    { c: 'future-choice', s: 'Hay{there are} muchas{a lot of|f.pl} luces{light|f.pl} en{in} la{the|f} casa{house|f} de{of} los{the|m.pl} vecinos{neighbour|m.pl}; ___ una{a|f} fiesta{party|f}.', base: 'tener', hint: 'guess', gloss: 'to have', a: ['tendrán'], p: 'ellos', en: 'The neighbours’ house is all lit up; they must be having a party.', why: 'A guess about what is happening now: only the futuro, tendrán. Van a tener would be a plan for later.' },
    { c: 'future-choice', s: 'Cuando{when} tengas{you are} mi{my} edad{age|f}, lo{it|m} ___.', base: 'entender', hint: 'tú, futuro', gloss: 'to understand', a: ['entenderás', 'vas a entender'], p: 'tú', en: 'When you are my age, you will understand.', why: 'The distant future: futuro simple, entenderás. Lo vas a entender is also fine.' },
    { c: 'future-choice', s: '¡Ya{already} son{it is} las{the|f.pl} dos{two}! Ven{come}, ___ algo{something} en{at} la{the|f} esquina{corner|f}.', base: 'comer', hint: 'nosotros, ir a', gloss: 'to eat', a: ['vamos a comer'], p: 'nosotros', en: 'It is already two! Come on, let’s eat something at the corner.', why: 'Vamos a plus the infinitive here means let’s: vamos a comer. Comeremos cannot make a suggestion like this.' },
    { c: 'future-choice', s: 'Me{me} trataron{they treated} fatal{terribly}: nunca{never} más{again} ___ a{to} ese{that|m} restaurante{restaurant|m}.', base: 'volver', hint: 'yo, futuro', gloss: 'to go back', a: ['volveré', 'voy a volver'], p: 'yo', en: 'They treated me terribly: I will never go back to that restaurant.', why: 'A firm resolution: volveré sounds final and emphatic. Voy a volver is just as common in speech.' },
    { c: 'future-choice', s: 'Atención{attention}, señores{ladies and gentlemen|m.pl} pasajeros{passenger|m.pl}: el{the|m} tren{train|m} ___ con{with} diez{ten} minutos{minute|m.pl} de{of} retraso{delay|m}.', base: 'salir', hint: 'futuro', gloss: 'to leave', a: ['saldrá', 'va a salir'], p: 'él', en: 'Attention, passengers: the train will leave ten minutes late.', why: 'A formal announcement: futuro simple, saldrá. Va a salir is the everyday version.' },
    { c: 'future-choice', s: 'Llevas{you have gone} todo{all|m} el{the|m} día{day|m} sin{without} comer{eating}; ___ hambre{hunger|f}, ¿no{right}?', base: 'tener', hint: 'tú, guess', gloss: 'to have', a: ['tendrás'], p: 'tú', en: 'You have gone all day without eating; you must be hungry, right?', why: 'A guess about how you feel now: only the futuro, tendrás. Vas a tener hambre would mean later.' },
    { c: 'future-choice', s: 'Ustedes{you (plural)} ya{already} tienen{have} los{the|m.pl} pasajes{ticket|m.pl}; ¿cuándo{when} ___?', base: 'irse', hint: 'ir a', gloss: 'to leave', a: ['se van a ir', 'van a irse', 'se irán'], p: 'ellos', en: 'You already have the tickets; when are you leaving?', why: 'Asking about a plan: ir a, se van a ir or van a irse. Se irán is correct too. Ustedes takes the ellos form.' },
    { c: 'future-choice', s: 'Tranquilo{don’t worry|m}, abuelo{grandpa|m}: te{you} ___ todas_las_semanas{every week}.', base: 'escribir', hint: 'nosotros, futuro', gloss: 'to write', a: ['escribiremos', 'vamos a escribir'], p: 'nosotros', en: 'Don’t worry, Grandpa: we will write to you every week.', why: 'A promise: futuro simple, escribiremos. Te vamos a escribir is also heard.' },
  ],
};
